<?php

$configArray = array(

	'meta' => array(
		'name' => 'Elegant',
		'desc' => 'Elegant is a timeless and flexible template.   The sage and camel palette compliments a wide variety of subjects.  Its great for engagements, weddings, seniors, children, and more.  Classic, clean design elements showcase your work without distraction.  Elegant has a traditional look that appeals to a wide spectrum of clients.',
	),


	'options' => array(
		'boxy_date_bg_color_bind'                               => 'on',
		'masthead_slideshow_bg_color'                           => '#fdfdfc',
		'post_header_postdate_letterspacing'                    => '1px',
		'primary_nav_menu_dropdown_bg_hover_color_bind'         => 'on',
		'blog_bg_color'                                         => '#e8e9d9',
		'body_bg_color'                                         => '#fdfdfc',
		'blog_border'                                           => 'dropshadow',
		'blog_bg_img_repeat'                                    => 'no-repeat',
		'blog_bg_img_position'                                  => 'top center',
		'headerlayout'                                          => 'logocenter_nav_masthead',
		'header_bg_color_bind'                                  => 'on',
		'masthead_display'                                      => 'static',
		'header_bg_color'                                       => '#1e1e1e',
		'primary_nav_menu_link_font_family'                     => 'Georgia, Times, serif',
		'primary_nav_menu_link_text_transform'                  => 'uppercase',
		'primary_nav_menu_link_font_color'                      => '#000000',
		'primary_nav_menu_link_font_size'                       => '13',
		'primary_nav_menu_bg_color'                             => '#88b2ab',
		'primary_nav_menu_dropdown_bg_hover_color'              => '#88b2ab',
		'primary_nav_menu_dropdown_bg_color'                    => '#88b2ab',
		'primary_nav_menu_link_spacing_between'                 => '35',
		'bio_include'                                           => 'no',
		'biopic_align'                                          => 'right',
		'biopic_border_color'                                   => '#1e1e1e',
		'bio_bg'                                                => 'color',
		'bio_bg_color'                                          => '#ffffff',
		'bio_border_color'                                      => '#cccccc',
		'post_header_align'                                     => 'center',
		'post_header_margin_below'                              => '14',
		'postdate_placement'                                    => 'above',
		'post_title_link_font_size'                             => '27',
		'post_header_border'                                    => 'image',
		'post_header_postdate_text_transform'                   => 'uppercase',
		'post_header_postdate_margin_bottom'                    => '15',
		'categories_in_post_footer'                             => 'yes',
		'tags_in_post_footer'                                   => 'yes',
		'gen_font_family'                                       => 'Georgia, Times, serif',
		'gen_line_height'                                       => '1.75',
		'gen_font_color'                                        => '#444444',
		'gen_link_font_color'                                   => '#502914',
		'header_font_style'                                     => 'normal',
		'header_text_transform'                                 => 'uppercase',
		'header_font_color'                                     => '#111111',
		'comments_layout'                                       => 'minima',
		'comments_area_lr_margin_control'                       => 'set',
		'comments_body_area_bg_color_bind'                      => 'on',
		'comments_header_bg_color_bind'                         => 'on',
		'comments_area_border_color'                            => '#bbbaba',
		'comments_area_border_width'                            => '1',
		'comments_area_border_style'                            => 'solid',
		'comments_header_show_article_author'                   => 'false',
		'comments_header_lr_padding'                            => '30',
		'comments_header_link_font_size'                        => '17',
		'comments_header_link_font_style'                       => 'italic',
		'comments_header_font_color_bind'                       => 'on',
		'comments_header_post_interaction_link_font_size'       => '12',
		'comments_header_post_interaction_link_font_style'      => 'normal',
		'comments_header_post_interaction_link_text_transform'  => 'uppercase',
		'comments_header_post_interaction_link_font_color_bind' => 'on',
		'comment_author_link_font_weight'                       => '700',
		'comment_author_link_text_transform'                    => 'uppercase',
		'comment_author_link_font_color_bind'                   => 'on',
		'comment_timestamp_display'                             => 'left',
		'comment_timestamp_font_weight'                         => '400',
		'comment_timestamp_text_transform'                      => 'uppercase',
		'comment_timestamp_font_color'                          => '#46585e',
		'comment_tb_padding'                                    => '10',
		'comment_lr_padding'                                    => '8',
		'comments_body_area_lr_margin'                          => '125',
		'comment_tb_margin'                                     => '6',
		'comment_bottom_border_onoff'                           => 'on',
		'comment_alt_bg_color_bind'                             => '',
		'comments_post_interact_display'                        => 'button',
		'comments_header_bg_color'                              => '#c9dacd',
		'comments_header_font_color'                            => '#000000',
		'comments_header_post_interaction_link_font_color'      => '#333333',
		'comment_author_link_font_color'                        => '#244758',
		'comment_meta_margin_bottom'                            => '5',
		'comments_body_area_bg_color'                           => '#ffffff',
		'footer_bg_color'                                       => '#c9dacd',
		'footer_headings_font_family'                           => 'Georgia, Times, serif',
		'footer_headings_text_transform'                        => 'none',
		'footer_headings_font_color'                            => '#222222',
		'footer_font_color'                                     => '#000000',
		'footer_link_font_color'                                => '#555555',
		'gen_link_font_color_bind'                              => 'on',
		'post_header_postdate_font_size'                        => '11',
		'post_header_postdate_font_family'                      => 'Arial, Helvetica, sans-serif',
		'post_header_postdate_font_color_bind'                  => 'on',
		'post_header_postdate_font_color'                       => '#ffffff',
		'postdate_advanced_switch'                              => 'on',
		'postdate_bg_color_bind'                                => 'on',
		'postdate_bg_color'                                     => '#a8ab9b',
		'postdate_border_top'                                   => 'on',
		'postdate_border_bottom'                                => 'on',
		'postdate_border_color'                                 => '#ffffff',
		'postdate_border_width'                                 => '3',
		'postdate_border_style'                                 => 'double',
		'postdate_lr_padding'                                   => '18',
		'postdate_tb_padding'                                   => '4',
		'comments_body_area_bg_img_repeat'                      => 'no-repeat',
		'comments_body_area_bg_img_position'                    => 'top center',
		'comments_scrollbox_height'                             => '400',
		'comments_body_area_tb_margin'                          => '0',
		'post_title_link_letterspacing'                         => '1px',
	),


	'activation_widgets' => array(
		'fixed-sidebar' => 'empty',
	),


	'imgs' => array(
		'blog_bg'                                  => 'elegant_blog_bg.jpg',
		'logo'                                     => 'elegant_logo.jpg',
		'masthead_image1'                          => 'elegant_masthead_image.jpg',
		'post_header_separator'                    => 'elegant_post_header_separator.jpg',
		'comments_header_addacomment_link_icon'    => 'elegant_comments_header_addacomment_link_icon.gif',
		'comments_header_linktothispost_link_icon' => 'elegant_comments_header_linktothispost_link_icon.gif',
		'comments_header_emailafriend_link_icon'   => 'elegant_comments_header_emailafriend_link_icon.gif',
		'comments_body_area_bg'                    => 'elegant_comments_body_area_bg.jpg',
	),


	'remote_files' => array(

		'elegant_blog_bg.jpg' => array(
			'hash'   => 'dec1db02f4653cd8d23ef3847e960482',
			'width'  => '1800',
			'height' => '1200',
			'size'   => '67',
		),

		'elegant_comments_body_area_bg.jpg' => array(
			'hash'   => 'e720802f879a26fc4f2d537021d00506',
			'width'  => '1000',
			'height' => '496',
			'size'   => '8',
		),

		'elegant_comments_header_addacomment_link_icon.gif' => array(
			'hash'   => 'bcfa7b33ee5bb99763af767f7ba1693e',
			'width'  => '14',
			'height' => '11',
			'size'   => '1',
		),

		'elegant_comments_header_emailafriend_link_icon.gif' => array(
			'hash'   => '71cef411695c139e089b1d05e0aa6750',
			'width'  => '16',
			'height' => '11',
			'size'   => '1',
		),

		'elegant_comments_header_linktothispost_link_icon.gif' => array(
			'hash'   => 'a8776b3348e365b81260b3cabe33404a',
			'width'  => '14',
			'height' => '7',
			'size'   => '1',
		),

		'elegant_logo.jpg' => array(
			'hash'   => 'b780cccf6e64856740d7c41482a73d26',
			'width'  => '450',
			'height' => '94',
			'size'   => '5',
		),

		'elegant_masthead_image.jpg' => array(
			'hash'   => '020a8529e85a926ac84e0fc7c3944787',
			'width'  => '960',
			'height' => '337',
			'size'   => '68',
		),

		'elegant_post_header_separator.jpg' => array(
			'hash'   => '04488ec22967307f0c8391c6ea5f3528',
			'width'  => '651',
			'height' => '18',
			'size'   => '2',
		),
	),

);

