<?php

$configArray = array(

	'blank'             => '',
	'auto_auto_upgrade' => 'true',
	'dev_test_mode'     => 'disabled',

	// call to action
	'call_to_action_enable'           => 'false',
	'call_to_action_location'         => 'below_comments',
	'call_to_action_on_home'          => 'true',
	'call_to_action_on_single'        => 'true',
	'call_to_action_on_single'        => 'true',
	'call_to_action_separator'        => 'off',
	'call_to_action_separator_text'   => '|',
	'call_to_action_items_align'      => 'center',
	'call_to_action_items_lr_spacing' => '20',
	'call_to_action_items_tb_spacing' => '15',
	'call_to_action_area_top_padding' => '20',
	'call_to_action_area_btm_padding' => '20',


	// mobile
	'mobile_enable'                                                => 'true',
	'mobile_masthead_use_desktop_settings'                         => 'true',
	'mobile_show_logo_on_single'                                   => 'true',
	'mobile_logo_use_desktop'                                      => 'true',
	'mobile_masthead_use_desktop_settings'                         => 'true',
	'translate_mobile_loading'                                     => 'loading',
	'translate_mobile_error_loading'                               => 'Error Loading Page',
	'mobile_font_family'                                           => 'Helvetica, Arial, sans-serif',
	'mobile_font_color'                                            => '#333333',
	'mobile_headline_font_family'                                  => 'Helvetica, Arial, sans-serif',
	'mobile_headline_font_weight'                                  => '700',
	'mobile_headline_font_style'                                   => 'normal',
	'mobile_headline_font_color'                                   => '#333333',
	'mobile_headline_text_transform'                               => 'none',
	'mobile_link_font_color'                                       => '#2489CE',
	'mobile_link_decoration'                                       => 'none',
	'mobile_link_hover_decoration'                                 => 'underline',
	'mobile_link_hover_font_color_bind'                            => '',
	'mobile_link_visited_font_color_bind'                          => '',
	'mobile_button_font_family'                                    => '',
	'mobile_button_font_weight'                                    => '700',
	'mobile_button_font_style'                                     => 'normal',
	'mobile_button_text_transform'                                 => 'none',
	'mobile_button_font_color'                                     => '#444444',
	'mobile_article_title_font_size'                               => '25',
	'mobile_article_excerpt_title_font_color_bind'                 => '',
	'mobile_article_excerpt_text_font_color_bind'                  => '',
	'mobile_article_title_font_color_bind'                         => '',
	'mobile_article_meta_below_title_link_font_size'               => '12',
	'mobile_article_meta_below_title_link_font_weight'             => '400',
	'mobile_article_meta_below_title_link_font_style'              => 'italic',
	'mobile_article_meta_below_title_font_color_bind'              => '',
	'mobile_article_meta_below_title_link_font_color_bind'         => '',
	'mobile_article_meta_below_title_link_visited_font_color_bind' => '',
	'mobile_article_meta_below_title_link_hover_font_color_bind'   => '',
	'mobile_article_text_link_font_family'                         => '',
	'mobile_article_text_link_font_size'                           => '14',
	'mobile_article_text_link_line_height'                         => '1.25',
	'mobile_article_text_link_font_weight'                         => '400',
	'mobile_article_text_link_font_style'                          => 'normal',
	'mobile_content_bg_color_bind'                                 => '',
	'mobile_button_bg_color'                                       => '#eeeeee',
	'mobile_content_bg_color_bind'                                 => '',
	'mobile_comment_header_bg_color'                               => '#efefef',
	'mobile_comment_inputs_bg_color'                               => '#ffffff',
	'mobile_comment_input_font_color_bind'                         => '',
	'mobile_comment_font_color_bind'                               => '',
	'mobile_comment_header_font_color_bind'                        => '',
	'mobile_excerpt_list_border_color'                             => '#cccccc',
	'mobile_excerpt_list_border_width'                             => '1',
	'mobile_excerpt_list_border_style'                             => 'solid',
	'mobile_footer_color_scheme'                                   => 'black',
	'mobile_ajax_links_enabled'                                    => 'true',

	'mobile_nav_menu_structure' => json_encode( array(
		'mobile_nav_menu_item_1' => 'mobile_nav_menu_item_1',
		'mobile_nav_menu_item_2' => 'mobile_nav_menu_item_2',
		'mobile_nav_menu_item_3' => 'mobile_nav_menu_item_3',
		'mobile_nav_menu_item_4' => 'mobile_nav_menu_item_4',
		'mobile_nav_menu_item_5' => 'mobile_nav_menu_item_5',
	) ),


	'mobile_nav_menu_item_1' => json_encode( array(
		'text'          => 'Search',
		'type'          => 'special',
		'specialType'   => 'inline_search',
		'searchBtnText' => 'Search',
	) ),

	'mobile_nav_menu_item_2' => json_encode( array(
		'text'                  => 'Archives',
		'type'                  => 'internal',
		'internalType'          => 'archives',
		'archivesNestThreshold' => '10',
	) ),

	'mobile_nav_menu_item_3' => json_encode( array(
		'text'         => 'Categories',
		'type'         => 'internal',
		'internalType' => 'categories',
	) ),

	'mobile_nav_menu_item_4' => json_encode( array(
		'text'         => 'Pages',
		'type'         => 'internal',
		'internalType' => 'pages',
	) ),

	'mobile_nav_menu_item_5' => json_encode( array(
		'text'         => 'Home',
		'type'         => 'internal',
		'internalType' => 'home',
	) ),


	'primary_nav_menu_structure' => json_encode( array(
		'primary_nav_menu_item_1' => 'primary_nav_menu_item_1',
		'primary_nav_menu_item_2' => 'primary_nav_menu_item_2',
		'primary_nav_menu_item_3' => 'primary_nav_menu_item_3',
		'primary_nav_menu_item_4' => 'primary_nav_menu_item_4',
		'primary_nav_menu_item_5' => 'primary_nav_menu_item_5',
	) ),

	'primary_nav_menu_item_1' => json_encode( array(
		'text'                  => 'Archives',
		'type'                  => 'internal',
		'internalType'          => 'archives',
		'archivesNestThreshold' => '10',
	) ),

	'primary_nav_menu_item_2' => json_encode( array(
		'text'         => 'Categories',
		'type'         => 'internal',
		'internalType' => 'categories',
	) ),

	'primary_nav_menu_item_3' => json_encode( array(
		'text'        => 'Contact',
		'type'        => 'special',
		'specialType' => 'show_contact_form',
	) ),

	'primary_nav_menu_item_4' => json_encode( array(
		'text'         => 'Subscribe',
		'type'         => 'internal',
		'internalType' => 'rss',
	) ),

	'primary_nav_menu_item_5' => json_encode( array(
		'text'          => 'Search',
		'type'          => 'special',
		'specialType'   => 'inline_search',
		'searchBtnText' => 'Search',
	) ),
	'primary_nav_menu_split_after_id' => '',

	'secondary_nav_menu_structure'        => '',
	'secondary_nav_menu_border_top'       => 'off',
	'secondary_nav_menu_border_bottom'    => 'off',
	'secondary_nav_menu_btm_border_width' => '1',
	'secondary_nav_menu_top_border_width' => '1',
	'secondary_nav_menu_placement'        => '3',
	'secondary_nav_menu_split_after_id'   => '',
	'nav_secondary_bg_color'              => '#ffffff',
	'nav_secondary_bg_color_bind'         => 'on',

	'secondary_nav_menu_bg_img_repeat'                => 'repeat',
	'secondary_nav_menu_bg_img_position'              => 'top left',
	'secondary_nav_menu_bg_img_attachment'            => 'scroll',
	'secondary_nav_menu_bg_color'                     => '#232323',
	'secondary_nav_menu_align'                        => 'left',
	'secondary_nav_menu_dropdown_bg_color'            => '',
	'secondary_nav_menu_link_font_size'               => '12',
	'secondary_nav_menu_link_font_color'              => '#cccccc',
	'secondary_nav_menu_link_font_color_bind'         => 'on',
	'secondary_nav_menu_link_hover_font_color'        => '#ffffff',
	'secondary_nav_menu_link_hover_font_color_bind'   => '',
	'secondary_nav_menu_link_visited_font_color'      => '#cccccc',
	'secondary_nav_menu_link_visited_font_color_bind' => '',
	'secondary_nav_menu_link_font_style'              => 'normal',
	'secondary_nav_menu_link_decoration'              => 'none',
	'secondary_nav_menu_link_hover_decoration'        => 'underline',
	'secondary_nav_menu_link_text_transform'          => 'none',
	'secondary_nav_menu_dropdown_bg_hover_color'      => '#ff9900',
	'secondary_nav_menu_dropdown_link_textsize'       => '11',
	'secondary_nav_menu_dropdown_opacity'             => '93',
	'secondary_nav_menu_border_top_onoff'             => 'off',
	'secondary_nav_menu_border_bottom_onoff'          => 'off',
	'secondary_nav_menu_bg_color_bind'                => 'on',
	'secondary_nav_menu_dropdown_bg_hover_color'      => 'on',
	'secondary_nav_menu_btm_border_width'             => '1',
	'secondary_nav_menu_top_border_style'             => 'solid',
	'secondary_nav_menu_btm_border_style'             => 'solid',

	'primary_nav_menu_onoff'   => 'on',
	'secondary_nav_menu_onoff' => 'on',
	'lazyload_imgs'            => 'true',
	'lazyload_loading_opacity' => '60',
	'mobile_content_margin'    => '15',

	// drawers
	'foo'                                     => 'bar', // for test
	'drawer_default_opacity'                  => '85',
	'drawer_padding'                          => '20',
	'drawer_tab_font_color'                   => '#ffffff',
	'drawer_tab_font_size'                    => '12',
	'drawer_tab_font_family'                  => 'Arial, Helvetica, sans-serif',
	'drawer_tab_rounded_corners'              => 'on',
	'drawer_default_bg_color'                 => '#000000',
	'drawer_widget_headlines_font_color'      => '#ffffff',
	'drawer_widget_headlines_font_color_bind' => 'on',
	'drawer_tab_text_transform'               => 'uppercase',

	// sidebar
	'sidebar_bg_img_repeat'        => 'repeat',
	'sidebar_bg_img_position'      => 'top left',
	'sidebar_bg_img_attachment'    => 'scroll',
	'sidebar_border_switch'        => 'on',
	'sidebar'                      => 'left',
	'sidebar_width'                => '200',
	'sidebar_padding'              => '30',
	'sidebar_border_color'         => '#666666',
	'sidebar_border_width'         => '1',
	'sidebar_border_style'         => 'dotted',
	'sidebar_on_home'              => 'yes',
	'sidebar_on_single'            => 'yes',
	'sidebar_on_page'              => 'yes',
	'sidebar_on_archive'           => 'yes',
	'sidebar_widget_margin_bottom' => '35',
	'drawer_widget_btm_margin'     => '35',

	// background customizations
	'blog_border_style'            => 'solid',
	'masthead_top_splitter'        => '0',
	'masthead_btm_splitter'        => '0',
	'menu_top_splitter'            => '0',
	'menu_btm_splitter'            => '0',
	'logo_top_splitter'            => '0',
	'logo_btm_splitter'            => '0',
	'bio_top_splitter'             => '0',
	'bio_btm_splitter'             => '0',
	'post_splitter'                => '0',
	'archive_post_splitter'        => '0',
	'body_bg_img_attachment'       => 'scroll',
	'body_bg_img_repeat'           => 'repeat',
	'body_bg_img_position'         => 'top left',
	'body_bg_color'                => '#ffffff',
	'body_bg_color_bind'           => 'on',
	'blog_border_shadow_width'     => 'wide',
	'blog_bg_color'                => '#454746',
	'blog_bg_color_bind'           => 'on',
	'blog_bg_img_position'         => 'top left',
	'blog_bg_img_attachment'       => 'scroll',
	'blog_bg_img_repeat'           => 'repeat',
	'blog_bg_inner_color_bind'     => '',
	'blog_bg_inner_img_position'   => 'top left',
	'blog_bg_inner_img_attachment' => 'scroll',
	'blog_bg_inner_img_repeat'     => 'repeat-x',
	'blog_border'                  => 'border',
	'blog_border_color'            => '#232323',
	'blog_border_width'            => '16',
	'blog_border_visible_sides'    => 'left_and_right_only',
	'blog_top_margin'              => '0',
	'blog_btm_margin'              => '0',
	'content_margin'               => '30',
	'prophoto_classic_bar'         => 'off',
	'prophoto_classic_bar_color'   => '#666666',
	'prophoto_classic_bar_height'  => '20',

	// fonts
	'gen_font_family'           => 'Arial, Helvetica, sans-serif',
	'gen_font_color'            => '#666666',
	'gen_font_size'             => '13',
	'gen_font_style'            => 'normal',
	'gen_font_weight'           => '400',
	'gen_text_transform'        => 'none',
	'header_font_size'          => '24',
	'header_font_color'         => '#0c7ead',
	'header_font_style'         => 'italic',
	'header_font_family'        => 'Georgia, Times, serif',
	'header_text_transform'     => 'none',
	'gen_link_font_color'       => '#0c7ead',
	'gen_link_hover_font_color' => '#0c7ead',
	'gen_link_decoration'       => 'none',
	'gen_link_hover_decoration' => 'underline',
	'gen_link_font_style'       => 'normal',
	'gen_margin_below'          => '13',
	'gen_line_height'           => '1.5',

	// header options
	'headerlayout'              => 'logomasthead_nav',
	'header_bg_color'           => '#232323',
	'header_bg_color_bind'      => '',
	'masthead_top_border'       => 'off',
	'masthead_btm_border'       => 'off',
	'logo_linkurl'              => pp::site()->url,
	'mobile_logo_linkurl'       => pp::site()->url,
	'logo_swf_switch'           => 'off',
	'masthead_top_border_width' => '1',
	'masthead_btm_border_width' => '1',

	// navigation options
	'primary_nav_menu_bg_img_repeat'                => 'repeat',
	'primary_nav_menu_bg_img_position'              => 'top left',
	'primary_nav_menu_bg_img_attachment'            => 'scroll',
	'primary_nav_menu_bg_color'                     => '#232323',
	'primary_nav_menu_align'                        => 'left',
	'primary_nav_menu_dropdown_bg_color'            => '',
	'primary_nav_menu_link_font_size'               => '14',
	'primary_nav_menu_link_font_color'              => '#cccccc',
	'primary_nav_menu_link_font_color_bind'         => 'on',
	'primary_nav_menu_link_hover_font_color'        => '#ffffff',
	'primary_nav_menu_link_hover_font_color_bind'   => '',
	'primary_nav_menu_link_font_family'             => 'Arial, Helvetica, sans-serif',
	'primary_nav_menu_link_visited_font_color'      => '#cccccc',
	'primary_nav_menu_link_visited_font_color_bind' => '',
	'primary_nav_menu_link_font_style'              => 'normal',
	'primary_nav_menu_link_decoration'              => 'none',
	'primary_nav_menu_link_hover_decoration'        => 'underline',
	'primary_nav_menu_link_text_transform'          => 'none',
	'primary_nav_menu_dropdown_bg_hover_color'      => '#ff9900',
	'primary_nav_menu_dropdown_link_textsize'       => '11',
	'primary_nav_menu_dropdown_opacity'             => '93',
	'primary_nav_menu_border_top_onoff'             => 'off',
	'primary_nav_menu_border_bottom_onoff'          => 'off',
	'primary_nav_menu_bg_color_bind'                => 'on',
	'primary_nav_menu_dropdown_bg_hover_color'      => 'on',
	'primary_nav_menu_btm_border_width'             => '1',
	'primary_nav_menu_top_border_style'             => 'solid',
	'primary_nav_menu_btm_border_style'             => 'solid',
	'subscribebyemail_lang'                         => 'en_US',
	'twitter_id'                                    => 'prophotoblogs',


	// bio options
	'bio_bg_img_repeat'           => 'repeat',
	'bio_bg_img_position'         => 'top left',
	'bio_bg_img_attachment'       => 'scroll',
	'bio_inner_bg_img_repeat'     => 'repeat',
	'bio_inner_bg_img_position'   => 'top left',
	'bio_inner_bg_img_attachment' => 'scroll',
	'bio_bg_color_bind'           => 'on',
	'biopic_display'              => 'normal',
	'bio_top_padding'             => '30',
	'bio_btm_padding'             => '30',
	'bio_widget_margin_btm'       => '30',
	'biopic_align'                => 'left',
	'bio_include'                 => 'yes',
	'biopic_border_color'         => '#d7d6d6',
	'biopic_border_width'         => '10',
	'biopic_border_style'         => 'solid',
	'bio_border'                  => 'border',
	'bio_border_style'            => 'solid',
	'bio_border_width'            => '1',
	'bio_border_color'            => '#e6e6e6',
	'use_hidden_bio'              => 'no',
	'bio_home'                    => 'on',
	'bio_pages_minimize'          => 'none',
	'bio_home'                    => 'on',
	'bio_sig_float'               => 'left',
	'bio_sig_top_margin'          => '0',
	'bio_sig_left_margin'         => '0',
	'bio_sig_right_margin'        => '0',
	'bio_twitter'                 => 'off',
	'bio_twitter_style'           => 'smooth',
	'twitter_name'                => 'prophotoblogs',
	'biopic_border'               => 'on',

	// contact form options
	'contact_btm_border'               => 'on',
	'contact_btm_border_width'         => '1',
	'contact_btm_border_color'         => '#cccccc',
	'contact_btm_border_style'         => 'solid',
	'contact_bg_img_repeat'            => 'repeat',
	'contact_bg_img_position'          => 'top left',
	'contact_bg_img_attachment'        => 'scroll',
	'contact_success_msg'              => 'Form submitted successfully, thank you.',
	'contact_success_bg_color'         => '#ACDFA4',
	'contact_success_text_color'       => '#333333',
	'contact_error_msg'                => 'Error submitting form, please try again.',
	'contact_error_bg_color'           => '#DD7373',
	'contact_error_text_color'         => '#333333',
	'anti_spam_question_1'             => 'What color is the sky?',
	'anti_spam_question_2'             => '2 + 2 = ?',
	'anti_spam_question_3'             => 'What day comes after Saturday?',
	'anti_spam_answer_1'               => 'blue',
	'anti_spam_answer_2'               => '4*four',
	'anti_spam_answer_3'               => 'sunday',
	'anti_spam_explanation'            => '(required - to prevent spam)',
	'contactform_required_text'        => '(required)',
	'contactform_yourinformation_text' => 'Your Information:',
	'contactform_name_text'            => 'Name',
	'contactform_email_text'           => 'Email',
	'contactform_yourmessage_text'     => 'Your Message:',
	'contactform_message_text'         => 'Message',
	'contactform_submit_text'          => 'submit',
	'contactform_ajax'                 => 'on',
	'contactform_antispam_enable'      => 'on',
	'contact_sendmail_from'            => '',
	'contact_form_invalid_email'       => 'enter valid email',
	'contact_remote_send'              => 'off',

	// content: post header
	'comment_count_in_post_header'  => 'no',
	'categories_in_post_header'     => 'yes',
	'tags_in_post_header'           => 'no',
	'postdate_placement'            => 'below',
	'boxy_date_bg_color'            => '#eaeaea',
	'boxy_date_font_size'           => '12',
	'boxy_date_align'               => 'left',
	'boxy_date_month_color'         => '#666666',
	'boxy_date_year_color'          => '#666666',
	'boxy_date_day_color'           => '#555555',
	'postdate_display'              => 'normal',
	'postdate_advanced_switch'      => 'off',
	'post_title_link_letterspacing' => 'normal',

	// content
	'paginate_post_navigation'          => 'true',
	'max_paginated_links'               => '18',
	'pagination_prev_text'              => '&laquo; Prev',
	'pagination_next_text'              => 'Next &raquo;',
	'pagination_show_prev_next'         => 'true',
	'feedburner'                        => '',
	'modify_feed_images'                => 'false',
	'feed_thumbnail_type'               => 'medium',
	'modify_feed_images_alert'          => 'NOTE: the images in this feed have been downsized or removed for copyright reasons. To see them in their unmodified state, please view the original post by ^clicking here^.',
	'watermark_position'                => 'middle center',
	'watermark_alpha'                   => '25',
	'post_bg_img_repeat'                => 'repeat',
	'post_bg_img_position'              => 'top left',
	'post_bg_img_attachment'            => 'scroll',
	'post_header_margin_above'          => '30',
	'post_title_link_decoration'        => 'none',
	'post_title_link_hover_decoration'  => 'underline',
	'post_title_margin_below'           => '6',
	'show_post_published_time'          => 'no',
	'dateformat'                        => 'l, F j, Y',
	'category_list_divider'             => ', ',
	'category_list_prependinc'          => 'yes',
	'category_list_prepend'             => 'Posted in ',
	'read_more_link_text'               => 'View full post &raquo;',
	'indexcontent'                      => 'full',
	'post_pic_margin_top'               => '15',
	'post_pic_margin_bottom'            => '15',
	'post_header_align'                 => 'left',
	'post_header_border'                => 'off',
	'post_header_border_width'          => '1',
	'post_header_border_style'          => 'solid',
	'post_header_border_color'          => '#cccccc',
	'post_header_border_margin'         => '15',
	'post_header_border_padding'        => '5',
	'post_divider'                      => 'line',
	'post_sep_border_width'             => '1',
	'post_sep_border_style'             => 'dotted',
	'post_sep_border_color'             => '#cccccc',
	'padding_below_post'                => '30',
	'tag_list_prepend'                  => 'Tags:',
	'tag_list_divider'                  => ', ',
	'post_header_margin_below'          => '25',
	'tags_on_home'                      => 'yes',
	'tags_on_single'                    => 'yes',
	'tags_on_archive'                   => 'yes',
	'tags_on_tags'                      => 'yes',
	'post_pic_margin_top'               => '15',
	'post_pic_margin_bottom'            => '15',
	'archive_padding_below_post'        => '30',
	'archive_post_sep_border_width'     => '1',
	'archive_post_sep_border_color'     => '#cccccc',
	'archive_post_sep_border_style'     => 'dotted',
	'excerpts_on_home'                  => '',
	'excerpts_on_archive'               => 'true',
	'excerpts_on_category'              => 'true',
	'excerpts_on_tag'                   => 'true',
	'excerpts_on_author'                => 'true',
	'excerpts_on_search'                => 'true',
	'show_excerpt_image'                => 'true',
	'dig_for_excerpt_image'             => 'true',
	'excerpt_image_position'            => 'before_text',
	'excerpt_image_size'                => 'thumbnail',
	'excerpt_style'                     => 'standard',
	'post_sep_align'                    => 'center',
	'post_pic_border_color'             => '#cccccc',
	'post_pic_border_width'             => '0',
	'post_pic_border_style'             => 'solid',
	'post_pic_shadow_enable'            => 'false',
	'post_pic_shadow_vertical_offset'   => '6',
	'post_pic_shadow_horizontal_offset' => '6',
	'post_pic_shadow_blur'              => '5',
	'post_pic_shadow_color'             => '#888888',
	'watermark_startdate'               => '',
	'like_btn_enable'                   => 'false',
	'like_btn_layout'                   => 'standard',
	'like_btn_verb'                     => 'like',
	'like_btn_color_scheme'             => 'light',
	'like_btn_show_advanced'            => 'false',
	'like_btn_filter_priority'          => 10,
	'like_btn_margin_top'               => '10',
	'like_btn_margin_btm'               => '10',
	'like_btn_on_home'                  => 'true',
	'like_btn_on_single'                => 'true',
	'like_btn_on_page'                  => '',
	'like_btn_with_send_btn'            => 'false',
	'gd_img_downsizing'                 => 'enabled',
	'gd_img_downsizing_max_size'        => '6000',
	'watermark_size_threshold'          => '400',
	'pinterest_prevent_pins'            => 'false',

	// grids
	'excerpt_grid_cols'                            => '3',
	'excerpt_grid_rows'                            => '3',
	'grid_img_text_below_gutter'                   => '20',
	'grid_img_rollover_text'                       => '0',
	'grid_img_rollover_text_overlay_bg_color'      => '#ffffff',
	'grid_img_rollover_text_overlay_bg_color_bind' => 'on',
	'grid_img_rollover_text_overlay_bg_opacity'    => '85',
	'excerpt_grid_style'                           => 'img_text_below',

	// comments options
	'comments_enable'                             => 'true',
	'comments_area_border_style'                  => 'solid',
	'comments_header_bg_color_bind'               => '',
	'comments_header_bg_img_repeat'               => 'repeat',
	'comments_header_bg_img_position'             => 'top left',
	'comments_header_bg_img_attachment'           => 'scroll',
	'comments_area_border_width'                  => '1',
	'comments_header_lr_padding'                  => '0',
	'comment_meta_margin_bottom'                  => '8',
	'comment_tb_padding'                          => '0',
	'comments_body_area_lr_margin'                => '10',
	'comment_tb_margin'                           => '5',
	'comment_lr_padding'                          => '5',
	'comments_header_repeat'                      => 'repeat',
	'comments_header_position'                    => 'top left',
	'comments_header_attachment'                  => 'scroll',
	'comments_body_area_tb_margin'                => '5',
	'comments_scrollbox_height'                   => '220',
	'comments_in_scrollbox_on_home'               => 'true',
	'comments_in_scrollbox_on_singular'           => 'false',
	'comments_body_area_bg_img_repeat'            => 'repeat',
	'comments_body_area_bg_img_position'          => 'top left',
	'comments_body_area_bg_img_attachment'        => 'scroll',
	'comments_show_avatars'                       => 'false',
	'comment_avatar_size'                         => '25',
	'comment_avatar_align'                        => 'left',
	'comment_avatar_padding'                      => '8',
	'comments_on_home_start_hidden'               => 'true',
	'comments_layout'                             => 'tabbed',
	'comment_timestamp_display'                   => 'right',
	'comment_timestamp_color'                     => '#cccccc',
	'comments_header_addacomment_link_text'       => 'add a comment',
	'comments_header_linktothispost_link_text'    => 'link to this post',
	'comments_header_emailafriend_link_text'      => 'email a friend',
	'comments_minima_show_text'                   => 'show',
	'comments_minima_hide_text'                   => 'hide',
	'comments_header_link_font_size'              => '13',
	'comments_header_link_font_family'            => 'Georgia, Times, serif',
	'comment_bg_color'                            => '#ffffff',
	'comment_bg_color_bind'                       => '',
	'comment_text_and_link_font_size'             => '11',
	'comments_link_font_family'                   => 'Arial, Helvetica, sans-serif',
	'comments_link_font_style'                    => 'normal',
	'comments_link_decoration'                    => 'underline',
	'comments_link_hover_decoration'              => 'none',
	'comment_bottom_border_onoff'                 => 'off',
	'comment_bottom_border_width'                 => '1',
	'comment_bottom_border_color'                 => '#cccccc',
	'comment_bottom_border_style'                 => 'dotted',
	'comment_awaiting_moderation_text'            => '(Your comment is awaiting moderation)',
	'comment_awaiting_moderation_font_style'      => 'italic',
	'comments_header_linktothispost_link_include' => 'yes',
	'comments_header_emailafriend_link_include'   => 'yes',
	'comments_header_emailafriend_link_subject'   => 'I saw this post and thought of you',
	'comments_header_emailafriend_link_body'      => 'Check out this post: %post_url%',
	'comments_area_border_color'                  => "#cccccc",
	'comment_author_link_target'                  => '_self',
	'comment_alt_bg_color_bind'                   => 'on',
	'comment_alt_bg_color'                        => '#eaeaea',
	'comments_header_show_article_author'         => 'true',
	'comments_show_hide_method'                   => 'button',
	'comment_meta_position'                       => 'above',
	'comments_area_lr_margin_control'             => 'inherit',
	'comments_area_lr_margin'                     => '0',
	'reverse_comments'                            => 'false',
	'comments_post_interact_display'              => 'text',
	'comments_header_post_interact_link_spacing'  => '5',
	'comment_header_border_top'                   => 'on',
	'comment_header_border_bottom'                => 'on',
	'comments_ajax_adding_enabled'                => 'true',


	// archive, category, tag, search, author
	'archivecontent'                   => 'excerpt',
	'archive_h2_font_size'             => '19',
	'archive_h2_font_color'            => '#666666',
	'archive_h2_font_style'            => 'normal',
	'archive_h2_text_transform'        => 'none',
	'archive_h2_font_weight'           => '400',
	'comments_show_on_archive'         => 'false',
	'comments_on_archive_start_hidden' => 'hide',
	'archive_post_divider'             => 'same',
	'archive_content'                  => 'full',
	'category_content'                 => 'full',


	// footer options
	'footer_bg_img_repeat'              => 'repeat',
	'footer_bg_img_position'            => 'top left',
	'footer_bg_img_attachment'          => 'scroll',
	'footer_include'                    => 'yes',
	'footer_bg_color_bind'              => 'on',
	'footer_bg_color'                   => '#232323',
	'footer_headings_font_family'       => 'Arial, Helvetica, sans-serif',
	'footer_headings_font_color'        => '#ffffff',
	'footer_headings_font_size'         => '17',
	'footer_headings_margin_below'      => '10',
	'footer_headings_font_style'        => 'normal',
	'footer_link_font_size'             => '13',
	'footer_widget_margin_below'        => '30',
	'footer_subscribebyemail'           => 'off',
	'footer_subscribebyemail_placement' => 'left',
	'footer_subscribebyemail_header'    => 'Subscribe by email',
	'footer_subscribebyemail_note'      => 'enter your email address to receive notification via email whenever there is a new post.',
	'footer_subscribebyemail_submit'    => 'subscribe',


	// slideshow gallery options
	'slideshow_splash_screen_position'    => 'middle',
	'slideshow_thumb_paging_animation'    => 'easeOutExpo@900',
	'slideshow_disable_full_screen'       => 'false',
	'slideshow_show_timer'                => 'true',
	'slideshow_btns_color'                => '#ffffff',
	'slideshow_bg_color'                  => '#000000',
	'slideshow_splash_screen_height'      => '30',
	'slideshow_splash_screen_opacity'     => '80',
	'slideshow_title_font_color'          => '#ffffff',
	'slideshow_title_font_family'         => '"Century Gothic", Helvetica, Arial, sans-serif',
	'slideshow_title_font_size'           => '33',
	'slideshow_subtitle_font_size'        => '22',
	'slideshow_start_playing'             => 'true',
	'slideshow_loop_show'                 => 'true',
	'slideshow_hold_time'                 => '2.5',
	'slideshow_transition_type'           => 'fade',
	'slideshow_transition_time'           => '1.2',
	'slideshow_controls_position'         => 'bottom',
	'slideshow_controls_overlaid'         => 'true',
	'slideshow_controls_autohide'         => 'true',
	'slideshow_controls_autohide_time'    => '2.2',
	'slideshow_controls_bg_opacity'       => '45',
	'slideshow_btns_opacity'              => '40',
	'slideshow_thumb_size'                => '60',
	'slideshow_thumb_border_width'        => '1',
	'slideshow_thumb_border_color'        => '#777777',
	'slideshow_active_thumb_border_color' => '#ffffff',
	'slideshow_thumb_opacity'             => '75',
	'slideshow_active_thumb_opacity'      => '100',
	'slideshow_thumb_size'                => '60',
	'slideshow_thumb_padding'             => '10',
	'slideshow_mp3_autostart'             => 'true',
	'slideshow_mp3_loop'                  => 'true',


	// settings options
	'seo_title_home'                        => '%blog_name% &raquo; %blog_description%',
	'seo_title_unknown_page_type'           => '%blog_name% &raquo; %blog_description%',
	'seo_title_single'                      => '%post_title% &raquo; %blog_name%',
	'seo_title_page'                        => '%page_title% &raquo; %blog_name%',
	'seo_title_front_page'                  => '%page_title% &raquo; %blog_name%',
	'seo_title_category'                    => '%category_name% &raquo; %blog_name%',
	'seo_title_archive'                     => '%archive_date% &raquo; %blog_name%',
	'seo_title_search'                      => 'Search results for: %search_query% &raquo; %blog_name%',
	'seo_title_tag'                         => 'Posts tagged: "%tag_name%" &raquo; %blog_name%',
	'seo_title_author'                      => 'Posts by %author_name% &raquo; %blog_name%',
	'seo_meta_desc'                         => pp::site()->tagline,
	'seo_tags_for_keywords'                 => 'true',
	'seo_meta_use_excerpts'                 => 'true',
	'seo_meta_auto_generate'                => 'true',
	'seo_disable'                           => 'false',
	'google_analytics_code'                 => '',
	'noindex_home'                          => '',
	'seo_meta_keywords'                     => '',
	'statcounter_analytics_code'            => '',
	'txn_id'                                => '',
	'purch_time'                            => '',
	'payer_email'                           => '',
	'link_removal_verified_hash'            => '',
	'custom_copyright'                      => '',
	'audioplayer'                           => 'off',
	'audioplayer_autostart'                 => 'yes',
	'audioplayer_loop'                      => 'yes',
	'audioplayer_center_bg'                 => '#f8f8f8',
	'audioplayer_text'                      => '#666666',
	'audioplayer_left_bg'                   => '#eeeeee',
	'audioplayer_left_icon'                 => '#666666',
	'audioplayer_right_bg'                  => '#cccccc',
	'audioplayer_right_icon'                => '#666666',
	'audioplayer_right_bg_hover'            => '#999999',
	'audioplayer_right_icon_hover'          => '#ffffff',
	'audioplayer_slider'                    => '#666666',
	'audioplayer_loader'                    => '#9FFFB8',
	'audioplayer_track'                     => '#ffffff',
	'audioplayer_track_border'              => '#666666',
	'audio_on_home'                         => 'yes',
	'audio_on_single'                       => 'no',
	'audio_on_pages'                        => 'no',
	'audio_on_archive'                      => 'no',
	'audio_hidden'                          => 'off',
	'show_ad_banners'                       => 'false',
	'ad_banners_area_lr_margin'             => '70',
	'ad_banners_margin_right'               => '15',
	'ad_banners_margin_btm'                 => '20',
	'ad_banners_border_color'               => '#cccccc',
	'older_posts_link_text'                 => '&laquo; Older posts',
	'newer_posts_link_text'                 => 'Newer posts &raquo;',
	'older_posts_link_align'                => 'left',
	'newer_posts_link_align'                => 'right',
	'blog_width'                            => '960',
	'backup_reminder'                       => 'on',
	'backup_email'                          => get_option( 'admin_email' ),
	'show_hidden'                           => 'hide',
	'image_protection'                      => 'clicks',
	'maintenance_message'                   => 'This site is temporarily unavailable while customizations are being made.  Please check back soon.  Thanks for your patience!',
	'maintenance_mode'                      => 'off',
	'pathfixer_old_urls'                    => '',
	'override_css'                          => '',
	'custom_js'                             => '',
	'insert_into_head'                      => '',
	'post_signature'                        => '',
	'post_signature_on_home'                => 'true',
	'post_signature_on_single'              => '',
	'post_signature_on_page'                => '',
	'post_signature_filter_priority'        => 9,
	'dev_hide_options'                      => 'false',
	'designed_for_prophoto_store'           => 'false',
	'des_html_mark'                         => '',
	'facebook_language'                     => 'en_US',
	'facebook_blog_posts_page_title'        => '',
	'facebook_blog_posts_page_desc'         => '',
	'facebook_static_front_page_title'      => '',
	'facebook_static_front_page_desc'       => '',
	'facebook_admins'                       => '',
	'fb_comments_enable'                    => 'false',
	'fb_comments_also_show_unique_wp'       => 'true',
	'fb_comments_add_new'                   => 'fb_only',
	'fb_comments_colorscheme'               => 'light',
	'fb_comments_num_shown_nonsingle'       => '5',
	'fb_comments_num_shown_single'          => '50',
	// translation
	'translate_by'                               => 'by',
	'translate_commentform_message'              => 'Your email is <em>never</em> published or shared.',
	'translate_comments'                         => 'comments',
	'translate_comment'                          => 'comment',
	'translate_no'                               => 'no',
	'translate_comments_required'                => 'Required fields are marked',
	'translate_comment_form_author_label'        => 'Name',
	'translate_comment_form_email_label'         => 'Email',
	'translate_comment_form_url_label'           => 'Website',
	'translate_comment_form_comment_text_label'  => 'Comment',
	'translate_comment_form_submit_button_label' => 'Post Comment',
	'translate_search_notfound_header'           => 'Nothing found',
	'translate_search_notfound_text'             => 'Sorry, but nothing matched your search criteria. Please try again with some different keywords.',
	'translate_search_results'                   => 'Search Results for:',
	'translate_search_notfound_button'           => 'Find',
	'translate_archives_monthly'                 => 'Monthly Archives:',
	'translate_archives_yearly'                  => 'Yearly Archives:',
	'translate_blog_archives'                    => 'Blog Archives',
	'translate_tag_archives'                     => 'Tag Archives:',
	'translate_category_archives'                => 'Category Archives:',
	'translate_author_archives'                  => 'Author Archives:',
	'translate_404_header'                       => 'Not Found',
	'translate_404_text'                         => 'Apologies, but we were unable to find what you were looking for. Perhaps searching will help.',
	'translate_lightbox_image'                   => 'Image',
	'translate_lightbox_of'                      => 'of',
	'translate_comments_cancel_reply'            => 'Cancel Reply',
	'translate_comment_form_error_message'       => 'There was an error submitting your comment.  Please try again.',
	'translate_password_protected'               => ppString::id( 'wp_password_protect_phrase' ),
	'translate_mobile_prev_post_link'            => 'prev post',
	'translate_mobile_next_post_link'            => 'next post',

	// galleries
	'lightbox_border_width'          => '10',
	'lightbox_bg_color'              => '#ffffff',
	'lightbox_font_size'             => '10',
	'lightbox_font_family'           => 'Verdana, Tahoma, sans-serif',
	'lightbox_font_color'            => '#666666',
	'lightbox_overlay_color'         => '#000000',
	'lightbox_overlay_opacity'       => '80',
	'lightbox_resize_speed'          => '400',
	'lightbox_image_fadespeed'       => '400',
	'lightbox_fixed_navigation'      => 'false',
	'lightbox_nav_btns_opacity'      => '65',
	'lightbox_nav_btns_fadespeed'    => '200',
	'lightbox_thumb_default_size'    => '90',
	'lightbox_thumb_opacity'         => '65',
	'lightbox_thumb_mouseover_speed' => '200',
	'lightbox_thumb_mouseout_speed'  => '500',
	'lightbox_thumb_margin'          => '5',
	'lightbox_main_img_center'       => 'true',

	'not_registered' => 'true',
);

foreach ( array( '', 'mobile_' ) as $prefix ) {
	$configArray[$prefix . 'masthead_display']                   = 'slideshow';
	$configArray[$prefix . 'masthead_modify']                    = 'false';
	$configArray[$prefix . 'modified_masthead_display']          = 'none';
	$configArray[$prefix . 'masthead_slideshow_loop_images']     = 'true';
	$configArray[$prefix . 'masthead_slideshow_image_order']     = 'sequential';
	$configArray[$prefix . 'masthead_slideshow_hold_time']       = '6';
	$configArray[$prefix . 'masthead_slideshow_transition_time'] = '2';
	$configArray[$prefix . 'masthead_slideshow_transition_type'] = 'crossfade';
	$configArray[$prefix . 'masthead_slideshow_bg_color']        = '#121212';
	$configArray[$prefix . 'masthead_slideshow_bg_color_bind']   = 'on';
}


// widget area menu
for ( $i = 1; $i <= pp::num()->maxWidgetMenus; $i++ ) {
	$configArray['widget_menu_'.$i.'_structure']             = '';
	$configArray['widget_menu_'.$i.'_li_margin_btm']         = '12';
	$configArray['widget_menu_'.$i.'_sub_li_margin_btm']     = '10';
	$configArray['widget_menu_'.$i.'_sub_sub_li_margin_btm'] = '8';
	$configArray['widget_menu_'.$i.'_li_list_style']         = 'disc';
}

// masthead image links
for ( $i = 1; $i <= pp::num()->maxMastheadImages; $i++ ) {
	$configArray['masthead_image'.$i.'_linkurl'] = '';
}

// sliding drawers
for ( $i = 1; $i <= pp::num()->maxSidebarDrawers; $i++ ) {
	$configArray['drawer_content_width_'.$i] = '200';
	$configArray['drawer_tab_text_'.$i]      = 'More info';
}

// contact form custom fields
for ( $i = 1; $i <= pp::num()->maxContactFormCustomFields; $i++ ) {
	$configArray['contact_customfield' . $i . '_required'] = 'no';
}

// contact form custom fields
for ( $i = 1; $i <= pp::num()->maxCallToActionItems; $i++ ) {
	$configArray['call_to_action_' . $i]                                = 'off';
	$configArray['call_to_action_display_' . $i]                        = 'text';
	$configArray['call_to_action_fb_like_layout_' . $i]                 = 'button_count';
	$configArray['call_to_action_fb_like_with_send_' . $i]              = 'false';
	$configArray['call_to_action_target_' . $i]                         = '_self';
	$configArray['call_to_action_' . $i . '_emailafriend_link_subject'] = 'I saw this post and thought of you';
	$configArray['call_to_action_' . $i . '_emailafriend_link_body']    = 'Check out this post: %post_url%';
}

// extra bg images
for ( $i = 1; $i <= pp::num()->maxExtraBgImgs; $i++ ) {
	$configArray['extra_bg_img_' . $i . '_repeat']     = 'repeat';
	$configArray['extra_bg_img_' . $i . '_position']   = 'top left';
	$configArray['extra_bg_img_' . $i . '_attachment'] = 'scroll';
}


