<?php

$configArray = array(

	'meta' => array(
		'name' => 'Vandelay',
		'desc' => 'Chevrons, blood orange, and faux bois backdrop?  The Vandelay template is the hipster’s ultimate tool.  Customize this new design from <a href="http://www.lalunecreative.com">La Lune Creative</a> to showcase your seniors, portraits, and lifestyle photos.  The modern hunting lodge styling gives this template an edge for those working with younger clients.',
	),

	'options' => array(
		'ad_banners_area_lr_margin'                                   => '10',
		'ad_banners_border_color'                                     => '#ffffff',
		'ad_banners_margin_right'                                     => '10',
		'bio_bg'                                                      => 'color',
		'bio_bg_color'                                                => '#ffffff',
		'bio_border'                                                  => 'image',
		'bio_border_color'                                            => '#ebebeb',
		'bio_btm_padding'                                             => '25',
		'bio_front_page'                                              => 'on',
		'bio_gutter_width'                                            => '40',
		'bio_header_font_color'                                       => '#d56835',
		'bio_header_font_color_bind'                                  => 'on',
		'bio_header_font_family'                                      => 'BebasNeueRegular, \"Century Gothic\", Helvetica, Arial, sans-serif',
		'bio_header_font_size'                                        => '20',
		'bio_header_font_weight'                                      => '400',
		'bio_header_text_transform'                                   => 'uppercase',
		'bio_headline_margin_btm'                                     => '10',
		'bio_link_decoration'                                         => 'none',
		'bio_link_hover_decoration'                                   => 'none',
		'bio_lr_padding'                                              => '25',
		'bio_para_font_size'                                          => '12',
		'bio_top_padding'                                             => '25',
		'bio_widget_margin_btm'                                       => '',
		'biopic_border'                                               => 'off',
		'blog_bg_color'                                               => '#1f0f0a',
		'blog_bg_img_attachment'                                      => 'fixed',
		'blog_bg_img_position'                                        => 'center center',
		'blog_border'                                                 => 'none',
		'blog_border_color'                                           => '#e1e1e1',
		'blog_border_visible_sides'                                   => 'all_four_sides',
		'blog_border_width'                                           => '1',
		'blog_btm_margin'                                             => '30',
		'blog_top_margin'                                             => '30',
		'blog_width'                                                  => '900',
		'call_to_action_1'                                            => 'share_on_facebook',
		'call_to_action_2'                                            => 'tweet_this_url',
		'call_to_action_3'                                            => 'email_this_url',
		'call_to_action_4'                                            => 'show_contact_form',
		'call_to_action_area_btm_padding'                             => '10',
		'call_to_action_area_top_padding'                             => '0',
		'call_to_action_enable'                                       => 'true',
		'call_to_action_font_color'                                   => '#d56835',
		'call_to_action_font_color_bind'                              => 'on',
		'call_to_action_items_lr_spacing'                             => '10',
		'call_to_action_items_tb_spacing'                             => '5',
		'call_to_action_link_font_family'                             => 'BebasNeueRegular, \"Century Gothic\", Helvetica, Arial, sans-serif',
		'call_to_action_link_font_size'                               => '14',
		'call_to_action_location'                                     => 'above_comments',
		'call_to_action_separator'                                    => 'text',
		'call_to_action_text_1'                                       => 'Facebook Share',
		'call_to_action_text_2'                                       => 'Tweet Post',
		'call_to_action_text_3'                                       => 'Email Post',
		'call_to_action_text_4'                                       => 'Contact Me',
		'category_list_divider'                                       => ' | ',
		'category_list_prepend'                                       => 'Posted in: ',
		'comment_alt_bg_color_bind'                                   => '',
		'comment_author_link_font_color'                              => '#d56835',
		'comment_author_link_font_color_bind'                         => 'on',
		'comment_author_link_hover_decoration'                        => 'underline',
		'comment_bottom_border_color'                                 => '#ebebeb',
		'comment_bottom_border_onoff'                                 => 'on',
		'comment_bottom_border_style'                                 => 'solid',
		'comment_count_in_post_header'                                => '',
		'comment_header_border_bottom'                                => '',
		'comment_header_border_top'                                   => '',
		'comment_meta_position'                                       => 'inline',
		'comment_tb_margin'                                           => '8',
		'comment_tb_padding'                                          => '10',
		'comment_text_and_link_line_height'                           => '1.25',
		'comment_timestamp_font_color'                                => '#636363',
		'comments_addacomment_text'                                   => 'comment',
		'comments_area_border_color'                                  => '#ffffff',
		'comments_area_border_style'                                  => 'double',
		'comments_area_border_width'                                  => '0',
		'comments_area_lr_margin_control'                             => 'set',
		'comments_body_area_bg_color'                                 => '#ebebeb',
		'comments_body_area_lr_margin'                                => '5',
		'comments_body_area_tb_margin'                                => '10',
		'comments_header_addacomment_link_text'                       => 'comment',
		'comments_header_bg_color'                                    => '#d56835',
		'comments_header_bg_color_bind'                               => 'on',
		'comments_header_emailafriend_link_include'                   => 'no',
		'comments_header_emailafriend_link_text'                      => 'email post',
		'comments_header_font_color'                                  => '#999999',
		'comments_header_font_color_bind'                             => 'on',
		'comments_header_link_decoration'                             => 'none',
		'comments_header_link_font_color'                             => '#ffffff',
		'comments_header_link_font_color_bind'                        => 'on',
		'comments_header_link_font_family'                            => 'BebasNeueRegular, \"Century Gothic\", Helvetica, Arial, sans-serif',
		'comments_header_link_font_size'                              => '15',
		'comments_header_link_font_style'                             => 'normal',
		'comments_header_link_font_weight'                            => '400',
		'comments_header_link_hover_decoration'                       => 'none',
		'comments_header_link_hover_font_color'                       => '#ffffff',
		'comments_header_link_hover_font_color_bind'                  => 'on',
		'comments_header_link_text_transform'                         => 'uppercase',
		'comments_header_linktothispost_link_include'                 => 'no',
		'comments_header_lr_padding'                                  => '25',
		'comments_header_post_interact_link_spacing'                  => '15',
		'comments_header_post_interaction_link_decoration'            => 'none',
		'comments_header_post_interaction_link_font_color'            => '#ffffff',
		'comments_header_post_interaction_link_font_color_bind'       => 'on',
		'comments_header_post_interaction_link_font_size'             => '15',
		'comments_header_post_interaction_link_font_style'            => 'normal',
		'comments_header_post_interaction_link_font_weight'           => '400',
		'comments_header_post_interaction_link_hover_decoration'      => 'none',
		'comments_header_post_interaction_link_hover_font_color'      => '#979796',
		'comments_header_post_interaction_link_hover_font_color_bind' => 'on',
		'comments_header_post_interaction_link_text_transform'        => 'uppercase',
		'comments_header_post_interaction_link_visited_font_color'    => '#006C99',
		'comments_header_show_article_author'                         => 'false',
		'comments_header_tb_padding'                                  => '8',
		'comments_layout'                                             => 'minima',
		'comments_linktothispost_text'                                => 'link post',
		'comments_scrollbox_height'                                   => '230',
		'comments_show_hide_method'                                   => 'text',
		'contact_btm_border_color'                                    => '#ebebeb',
		'content_margin'                                              => '25',
		'custom_font_1'                                               => '{"slug":"BebasNeue","name":"BebasNeueRegular"}',
		'custom_font_1_fallback'                                      => '\"Century Gothic\", Helvetica, Arial, sans-serif',
		'dateformat'                                                  => 'custom',
		'dateformat_custom'                                           => 'M . j . Y',
		'excerpt_style'                                               => 'grid',
		'featured_galleries_converted'                                => 'true',
		'footer_bg_color'                                             => '#d56835',
		'footer_col_padding'                                          => '20',
		'footer_font_color'                                           => '#ffffff',
		'footer_font_color_bind'                                      => 'on',
		'footer_headings_font_family'                                 => 'BebasNeueRegular, \"Century Gothic\", Helvetica, Arial, sans-serif',
		'footer_headings_font_size'                                   => '16',
		'footer_headings_font_weight'                                 => '400',
		'footer_headings_text_transform'                              => 'uppercase',
		'footer_include'                                              => 'no',
		'footer_left_padding'                                         => '20',
		'footer_link_font_color'                                      => '#ffffff',
		'footer_link_font_color_bind'                                 => 'on',
		'footer_link_font_size'                                       => '12',
		'footer_link_hover_decoration'                                => 'none',
		'footer_link_hover_font_color'                                => '#ffffff',
		'footer_link_hover_font_color_bind'                           => 'on',
		'footer_right_padding'                                        => '20',
		'footer_widget_margin_below'                                  => '20',
		'gen_font_color'                                              => '#636363',
		'gen_font_family'                                             => 'Helvetica, Arial, sans-serif',
		'gen_font_size'                                               => '12',
		'gen_line_height'                                             => '1.25',
		'gen_link_font_color'                                         => '#d56835',
		'gen_link_font_color_bind'                                    => 'on',
		'gen_link_hover_decoration'                                   => 'none',
		'gen_link_hover_font_color'                                   => '#999999',
		'gen_link_hover_font_color_bind'                              => 'on',
		'gen_link_visited_font_color'                                 => '#999999',
		'grid_img_rollover_text_gutter'                               => '10',
		'grid_img_rollover_text_overlay_bg_opacity'                   => '95',
		'grid_img_text_below_gutter'                                  => '10',
		'grid_img_text_below_title_link_font_family'                  => 'BebasNeueRegular, \"Century Gothic\", Helvetica, Arial, sans-serif',
		'grid_img_text_below_title_link_font_size'                    => '16',
		'grid_img_text_below_title_link_font_weight'                  => '400',
		'grid_img_text_below_title_link_text_transform'               => 'uppercase',
		'header_bg_color'                                             => '#ffffff',
		'header_font_color'                                           => '#636363',
		'header_font_family'                                          => 'BebasNeueRegular, \"Century Gothic\", Helvetica, Arial, sans-serif',
		'header_font_size'                                            => '18',
		'header_font_style'                                           => 'normal',
		'header_font_weight'                                          => '400',
		'header_letterspacing'                                        => 'normal',
		'header_text_transform'                                       => 'uppercase',
		'headerlayout'                                                => 'logocenter_masthead_nav',
		'lightbox_bg_color'                                           => '#999999',
		'lightbox_font_color'                                         => '#999999',
		'lightbox_overlay_color'                                      => '#ffffff',
		'lightbox_thumb_default_size'                                 => '70',
		'like_btn_color_scheme'                                       => 'dark',
		'like_btn_enable'                                             => 'true',
		'like_btn_layout'                                             => 'button_count',
		'like_btn_margin_btm'                                         => '5',
		'masthead_border_bottom_color'                                => '#ffffff',
		'masthead_border_bottom_style'                                => 'solid',
		'masthead_border_bottom_width'                                => '5',
		'masthead_border_top_color'                                   => '#ffffff',
		'masthead_border_top_style'                                   => 'solid',
		'masthead_border_top_width'                                   => '5',
		'masthead_btm_border_color'                                   => '#000000',
		'masthead_btm_border_style'                                   => 'solid',
		'masthead_slideshow_bg_color'                                 => '#1f0f0a',
		'masthead_slideshow_hold_time'                                => '4',
		'masthead_top_border_color'                                   => '#000000',
		'masthead_top_border_style'                                   => 'solid',
		'menu_btm_splitter'                                           => '10',
		'menu_top_splitter'                                           => '10',
		'nav_below_link_decoration'                                   => 'none',
		'nav_below_link_font_family'                                  => 'BebasNeueRegular, \"Century Gothic\", Helvetica, Arial, sans-serif',
		'nav_below_link_font_size'                                    => '14',
		'nav_below_link_font_weight'                                  => '400',
		'nav_below_link_text_transform'                               => 'uppercase',
		'newer_posts_link_text'                                       => 'NEXT »',
		'older_posts_link_text'                                       => '« PREVIOUS',
		'pagination_next_text'                                        => 'Next »',
		'pagination_prev_text'                                        => '« Prev',
		'portfoliotarget'                                             => '_blank',
		'post_divider'                                                => 'none',
		'post_footer_meta_link_decoration'                            => 'none',
		'post_footer_meta_link_font_family'                           => '\"Century Gothic\", Helvetica, Arial, sans-serif',
		'post_footer_meta_link_font_size'                             => '11',
		'post_footer_meta_link_hover_font_color'                      => '#999999',
		'post_footer_meta_link_hover_font_color_bind'                 => 'on',
		'post_footer_meta_link_text_transform'                        => 'lowercase',
		'post_header_align'                                           => 'center',
		'post_header_border_color'                                    => '#d56835',
		'post_header_border_margin'                                   => '20',
		'post_header_border_width'                                    => '2',
		'post_header_margin_above'                                    => '20',
		'post_header_margin_below'                                    => '20',
		'post_header_meta_font_color'                                 => '#666',
		'post_header_meta_link_font_size'                             => '10',
		'post_header_meta_link_hover_decoration'                      => 'none',
		'post_header_postdate_font_color'                             => '#979796',
		'post_header_postdate_font_color_bind'                        => 'on',
		'post_header_postdate_font_family'                            => 'Helvetica, Arial, sans-serif',
		'post_header_postdate_font_size'                              => '12',
		'post_header_postdate_font_style'                             => 'normal',
		'post_header_postdate_font_weight'                            => '400',
		'post_header_postdate_letterspacing'                          => '-1px',
		'post_header_postdate_margin_bottom'                          => '10',
		'post_header_postdate_text_transform'                         => 'uppercase',
		'post_pic_border_color'                                       => '#000000',
		'post_pic_margin_bottom'                                      => '2',
		'post_text_link_font_color'                                   => '#d56835',
		'post_text_link_font_color_bind'                              => 'on',
		'post_text_link_hover_font_color'                             => '#999999',
		'post_text_link_hover_font_color_bind'                        => 'on',
		'post_title_link_font_color'                                  => '#979796',
		'post_title_link_font_color_bind'                             => 'on',
		'post_title_link_font_family'                                 => 'BebasNeueRegular, \"Century Gothic\", Helvetica, Arial, sans-serif',
		'post_title_link_font_size'                                   => '24',
		'post_title_link_font_weight'                                 => '400',
		'post_title_link_hover_decoration'                            => 'none',
		'post_title_link_hover_font_color'                            => '#d56835',
		'post_title_link_hover_font_color_bind'                       => 'on',
		'post_title_link_margin_bottom'                               => '5',
		'post_title_link_text_transform'                              => 'uppercase',
		'postdate_border_color'                                       => '#000000',
		'postdate_border_style'                                       => 'solid',
		'postdate_display'                                            => 'off',
		'postdate_placement'                                          => 'withtitle',
		'primary_nav_menu_bg_color'                                   => '#828282',
		'primary_nav_menu_bg_color_bind'                              => '',
		'primary_nav_menu_btm_border_color'                           => '#979796',
		'primary_nav_menu_btm_border_width'                           => '2',
		'primary_nav_menu_dropdown_bg_color'                          => '#d56835',
		'primary_nav_menu_dropdown_bg_color_bind'                     => 'on',
		'primary_nav_menu_dropdown_bg_hover_color'                    => '#ffffff',
		'primary_nav_menu_dropdown_bg_hover_color_bind'               => 'on',
		'primary_nav_menu_dropdown_opacity'                           => '100',
		'primary_nav_menu_edge_padding'                               => '0',
		'primary_nav_menu_item_1'                                     => '{"type":"internal","internalType":"home","text":"Home","iconNotConstrained":true,"pageID":"","pageLoadMethod":"standard","categoryName":"","archivesNestThreshold":"","numRecentPosts":"","galleryID":"","galleryDisplay":"","specialType":"email","email":"","twitterID":"","numTweets":"8","searchBtnText":"Search","subscribeByEmailPrefill":"Enter email","subscribeByEmailBtnText":"Subscribe by email","customHTML":"","url":"","target":"","anchor":"img","iconAlign":"left","titleAttr":"","customClasses":"","menu_item_id":"primary_nav_menu_item_1","excludedPageIDs":""}',
		'primary_nav_menu_item_11'                                    => '{"text":"Categories","type":"internal","iconNotConstrained":true,"internalType":"categories","pageID":"","pageLoadMethod":"standard","categoryName":"","archivesNestThreshold":"","numRecentPosts":"","galleryID":"","galleryDisplay":"","specialType":"email","email":"","twitterID":"","numTweets":"8","searchBtnText":"Search","subscribeByEmailPrefill":"Enter email","subscribeByEmailBtnText":"Subscribe by email","customHTML":"","url":"","target":"","anchor":"img","iconAlign":"left","titleAttr":"","customClasses":"","menu_item_id":"primary_nav_menu_item_11","excludedPageIDs":""}',
		'primary_nav_menu_item_14'                                    => '{"text":"Portfolio","type":"manual","iconNotConstrained":true,"internalType":"page","pageID":"","pageLoadMethod":"standard","categoryName":"","archivesNestThreshold":"","numRecentPosts":"","galleryID":"","galleryDisplay":"","specialType":"email","email":"","twitterID":"","numTweets":"8","searchBtnText":"Search","subscribeByEmailPrefill":"Enter email","subscribeByEmailBtnText":"Subscribe by email","customHTML":"","url":"","target":"","anchor":"img","iconAlign":"left","titleAttr":"","customClasses":"","menu_item_id":"primary_nav_menu_item_14","excludedPageIDs":""}',
		'primary_nav_menu_item_15'                                    => '{"text":"Archives","type":"internal","iconNotConstrained":true,"internalType":"archives","pageID":"","pageLoadMethod":"standard","categoryName":"","archivesNestThreshold":"6","numRecentPosts":"","galleryID":"","galleryDisplay":"","specialType":"email","email":"","twitterID":"","numTweets":"8","searchBtnText":"Search","subscribeByEmailPrefill":"Enter email","subscribeByEmailBtnText":"Subscribe by email","customHTML":"","url":"","target":"","anchor":"img","iconAlign":"left","titleAttr":"","customClasses":"","menu_item_id":"primary_nav_menu_item_15","excludedPageIDs":""}',
		'primary_nav_menu_item_16'                                    => '{"text":"Galleries","type":"container","iconNotConstrained":true,"internalType":"gallery","pageID":"","pageLoadMethod":"standard","categoryName":"","archivesNestThreshold":"","numRecentPosts":"","galleryID":"","galleryDisplay":"slideshow_in_slidedown","specialType":"email","email":"","twitterID":"","numTweets":"8","searchBtnText":"Search","subscribeByEmailPrefill":"Enter email","subscribeByEmailBtnText":"Subscribe by email","customHTML":"","url":"","target":"","anchor":"img","iconAlign":"left","titleAttr":"","customClasses":"","menu_item_id":"primary_nav_menu_item_16","excludedPageIDs":""}',
		'primary_nav_menu_item_17'                                    => '{"text":"Subscribe","type":"internal","iconNotConstrained":true,"internalType":"rss","pageID":"","pageLoadMethod":"standard","categoryName":"","archivesNestThreshold":"","numRecentPosts":"","galleryID":"","galleryDisplay":"","specialType":"email","email":"","twitterID":"","numTweets":"8","searchBtnText":"Search","subscribeByEmailPrefill":"Enter email","subscribeByEmailBtnText":"Subscribe by email","customHTML":"","url":"","target":"","anchor":"img","iconAlign":"left","titleAttr":"","customClasses":"","menu_item_id":"primary_nav_menu_item_17","excludedPageIDs":""}',
		'primary_nav_menu_item_9'                                     => '{"type":"special","specialType":"show_contact_form","text":"Contact","iconNotConstrained":true,"internalType":"page","pageID":"","pageLoadMethod":"standard","categoryName":"","archivesNestThreshold":"","numRecentPosts":"","galleryID":"","galleryDisplay":"","email":"","twitterID":"","numTweets":"8","searchBtnText":"Search","subscribeByEmailPrefill":"Enter email","subscribeByEmailBtnText":"Subscribe by email","customHTML":"","url":"","target":"","anchor":"img","iconAlign":"left","titleAttr":"","customClasses":"","menu_item_id":"primary_nav_menu_item_9","excludedPageIDs":""}',
		'primary_nav_menu_link_font_color'                            => '#ffffff',
		'primary_nav_menu_link_font_family'                           => '',
		'primary_nav_menu_link_font_weight'                           => '400',
		'primary_nav_menu_link_hover_decoration'                      => 'none',
		'primary_nav_menu_link_hover_font_color'                      => '#d56835',
		'primary_nav_menu_link_hover_font_color_bind'                 => 'on',
		'primary_nav_menu_link_letterspacing'                         => 'normal',
		'primary_nav_menu_link_spacing_between'                       => '8',
		'primary_nav_menu_link_tb_padding'                            => '9',
		'primary_nav_menu_link_text_transform'                        => 'uppercase',
		'primary_nav_menu_link_visited_font_color'                    => '#999999',
		'primary_nav_menu_split_after_id'                             => 'primary_nav_menu_item_11',
		'primary_nav_menu_structure'                                  => '{"primary_nav_menu_item_1":"primary_nav_menu_item_1", "primary_nav_menu_item_14":"primary_nav_menu_item_14", "primary_nav_menu_item_16":"primary_nav_menu_item_16", "primary_nav_menu_item_11":"primary_nav_menu_item_11", "primary_nav_menu_item_15":"primary_nav_menu_item_15", "primary_nav_menu_item_9":"primary_nav_menu_item_9", "primary_nav_menu_item_17":"primary_nav_menu_item_17"}',
		'primary_nav_menu_top_border_color'                           => '#979796',
		'primary_nav_menu_top_border_width'                           => '2',
		'sidebar_bg_color'                                            => '#d56835',
		'sidebar_bg_color_bind'                                       => 'on',
		'sidebar_border_color'                                        => '#ebebeb',
		'sidebar_border_style'                                        => 'solid',
		'sidebar_headlines_font_color'                                => '#979796',
		'sidebar_headlines_font_color_bind'                           => 'on',
		'sidebar_headlines_font_family'                               => 'Helvetica, Arial, sans-serif',
		'sidebar_headlines_font_size'                                 => '12',
		'sidebar_headlines_font_style'                                => 'normal',
		'sidebar_headlines_font_weight'                               => '700',
		'sidebar_headlines_margin_bottom'                             => '10',
		'sidebar_headlines_text_transform'                            => 'uppercase',
		'sidebar_link_font_color'                                     => '#ebc305',
		'sidebar_link_font_family'                                    => 'Helvetica, Arial, sans-serif',
		'sidebar_link_hover_font_color'                               => '#979796',
		'sidebar_link_hover_font_color_bind'                          => 'on',
		'sidebar_on_archive'                                          => '',
		'sidebar_on_page'                                             => '',
		'sidebar_on_single'                                           => '',
		'sidebar_padding'                                             => '10',
		'sidebar_text_font_color'                                     => '#8e8e8e',
		'sidebar_text_font_color_bind'                                => 'on',
		'sidebar_text_font_family'                                    => 'Helvetica, Arial, sans-serif',
		'sidebar_text_font_size'                                      => '11',
		'sidebar_widget_margin_bottom'                                => '20',
		'sidebar_width'                                               => '155',
		'slideshow_bg_color'                                          => '#000000',
		'slideshow_controls_overlaid'                                 => 'true',
		'slideshow_disable_full_screen'                               => 'true',
		'slideshow_splash_screen_color'                               => '#000000',
		'slideshow_splash_screen_height'                              => '30',
		'slideshow_splash_screen_opacity'                             => '70',
		'slideshow_subtitle_font_size'                                => '12',
		'slideshow_thumb_border_color'                                => '#AAAAAA',
		'slideshow_title_font_color'                                  => '#ffffff',
		'slideshow_title_font_family'                                 => 'Arial, Helvetica, sans-serif',
		'slideshow_title_font_size'                                   => '16',
		'slideshow_transition_type'                                   => 'crossfade',
		'tag_list_divider'                                            => ' | ',
		'tag_list_prepend'                                            => 'Tags: ',
		'tags_in_post_header'                                         => '',
		'watermark_alpha'                                             => '100',
		'watermark_position'                                          => 'bottom center',
	),

	'activation_widgets' => array(
		'bio-col-1' => array(
			'1' => array(
				'pp-grid' => array(
					'title' => 'Featured',
					'gridOptionData' => '{"type":"recent_posts","rows":"2","cols":"2","style":"img_rollover_text"}',
				),

			),

		),

		'bio-col-2' => array(
			'1' => array(
				'pp-sliding-twitter' => array(
					'title'         => 'Twitter',
					'image'         => '1',
					'pos_top'       => '10',
					'tweet_height'  => '87',
					'pos_left'      => '50',
					'tweet_width'   => '225',
					'twitter_name'  => 'prophotoblogs',
					'twitter_count' => '1',
					'loading_text'  => 'loading...',
					'font'          => '\'Century Gothic\', Helvetica, Arial, sans-serif',
					'fontsize'      => '11',
				),

			),

		),

		'bio-spanning-col' => 'empty',
		'bio-col-3'        => 'empty',
		'bio-col-4'        => 'empty',
		'fixed-sidebar'    => 'empty',

	),

	'imgs' => array(
		'bio_separator'             => 'vandelay_bio_separator.png',
		'biopic1'                   => 'vandelay_biopic1.png',
		'blog_bg'                   => 'vandelay_blog_bg.jpg',
		'grid_article_img_fallback' => 'vandelay_grid_article_img_fallback.jpg',
		'lazyload_loading'          => 'vandelay_lazyload_loading.gif',
		'logo'                      => 'vandelay_logo.png',
		'masthead_image1'           => 'vandelay_masthead_image1.jpg',
		'masthead_image2'           => 'vandelay_masthead_image2.jpg',
		'masthead_image3'           => 'vandelay_masthead_image3.jpg',
		'primary_nav_menu_item_1'   => 'vandelay_primary_nav_menu_item_1.png',
		'primary_nav_menu_item_11'  => 'vandelay_primary_nav_menu_item_11.png',
		'primary_nav_menu_item_14'  => 'vandelay_primary_nav_menu_item_14.png',
		'primary_nav_menu_item_15'  => 'vandelay_primary_nav_menu_item_15.png',
		'primary_nav_menu_item_16'  => 'vandelay_primary_nav_menu_item_16.png',
		'primary_nav_menu_item_17'  => 'vandelay_primary_nav_menu_item_17.png',
		'primary_nav_menu_item_9'   => 'vandelay_primary_nav_menu_item_9.png',
		'widget_custom_image_1'     => 'vandelay_widget_custom_image_1.png',
	),

	'remote_files' => array(

		'BebasNeue-webfont.eot' => array(
			'hash' => 'e9264b2a65e166ef2391249b58f768d1',
		),

		'BebasNeue-webfont.svg' => array(
			'hash' => '6a07c2eada830bf77698256a810680ec',
		),

		'BebasNeue-webfont.ttf' => array(
			'hash' => '09fda78767949f0dd44e43e446ea2b19',
		),

		'BebasNeue-webfont.woff' => array(
			'hash' => '6f04d3d6e28184a5ace603e80b97433e',
		),

		'vandelay_bio_separator.png' => array(
			'hash'   => '9f5e7651baf2848b9a3ffcae05b10574',
			'width'  => '900',
			'height' => '12',
			'size'   => '8',
		),

		'vandelay_biopic1.png' => array(
			'hash'   => '18007d0a3974280a2c95837e6ead1f0b',
			'width'  => '275',
			'height' => '183',
			'size'   => '73',
		),

		'vandelay_blog_bg.jpg' => array(
			'hash'   => '699c3d042551be64296efcfdbf262609',
			'width'  => '1680',
			'height' => '1050',
			'size'   => '365',
		),

		'vandelay_grid_article_img_fallback.jpg' => array(
			'hash'   => 'f0893891f05634d496aa62d3372c1dd4',
			'width'  => '419',
			'height' => '250',
			'size'   => '17',
		),

		'vandelay_lazyload_loading.gif' => array(
			'hash'   => '1abbed1a8f2d463c7f7a62d3a9d163fd',
			'width'  => '31',
			'height' => '31',
			'size'   => '3',
		),

		'vandelay_logo.png' => array(
			'hash'   => '69a5a2eaa238fd9cbe51dd600c0edb82',
			'width'  => '295',
			'height' => '164',
			'size'   => '24',
		),

		'vandelay_masthead_image1.jpg' => array(
			'hash'   => '13debb7951649a9c498b8f39912810fb',
			'width'  => '900',
			'height' => '400',
			'size'   => '148',
		),

		'vandelay_masthead_image2.jpg' => array(
			'hash'   => '20904eec94fb48a3adccc261cba51e2e',
			'width'  => '900',
			'height' => '400',
			'size'   => '80',
		),

		'vandelay_masthead_image3.jpg' => array(
			'hash'   => 'c85a25fe654707940b9b70cba3e17061',
			'width'  => '900',
			'height' => '400',
			'size'   => '62',
		),

		'vandelay_primary_nav_menu_item_1.png' => array(
			'hash'   => '363f97f6249b62a4a1990e244cc43e78',
			'width'  => '131',
			'height' => '40',
			'size'   => '1',
		),

		'vandelay_primary_nav_menu_item_11.png' => array(
			'hash'   => '482eb065767046dae4f2b49559309917',
			'width'  => '160',
			'height' => '40',
			'size'   => '2',
		),

		'vandelay_primary_nav_menu_item_14.png' => array(
			'hash'   => 'fb7cd2681a5e4f644166c60b72c45ca8',
			'width'  => '160',
			'height' => '40',
			'size'   => '2',
		),

		'vandelay_primary_nav_menu_item_15.png' => array(
			'hash'   => '198c119dd1fda0192473d1946cb5bd55',
			'width'  => '160',
			'height' => '40',
			'size'   => '2',
		),

		'vandelay_primary_nav_menu_item_16.png' => array(
			'hash'   => 'c3b3db56dd779c34648adcd6eadd47f8',
			'width'  => '160',
			'height' => '40',
			'size'   => '2',
		),

		'vandelay_primary_nav_menu_item_17.png' => array(
			'hash'   => 'c2794a55042598a112c605e826ecc66b',
			'width'  => '131',
			'height' => '40',
			'size'   => '1',
		),

		'vandelay_primary_nav_menu_item_9.png' => array(
			'hash'   => '3e4ac48d4fdc597b967b437925a11fda',
			'width'  => '160',
			'height' => '40',
			'size'   => '2',
		),

		'vandelay_widget_custom_image_1.png' => array(
			'hash'   => '1a2a5c95d66715fd7bbc41eb3e055212',
			'width'  => '297',
			'height' => '89',
			'size'   => '4',
		),
	),
);


