<?php

$configArray = array(

	'meta' => array(
		'name' => 'Emilie',
		'desc' => 'What happens when you combine cute scrapbooking elements and Old World whimsy? Probably something that looks a lot like this charming new starter design from <a href="http://www.swoone.com">Swoone</a>. Emilie is just the right balance beautiful floral elements, unique secondary illustrations, and playful fonts. It\'s perfect for infant, children\'s, lifestyle and portrait photographers.',
	),

	'options' => array(
		'archive_h2_font_color'                                       => '#7d892e',
		'archive_h2_font_family'                                      => 'Palatino, Georgia, serif',
		'archive_h2_font_size'                                        => '16',
		'archive_h2_font_weight'                                      => '400',
		'archive_h2_text_transform'                                   => 'uppercase',
		'bio_bg'                                                      => 'color',
		'bio_bg_color'                                                => '#ffffff',
		'bio_bg_color_bind'                                           => '',
		'bio_bg_img_position'                                         => 'top center',
		'bio_bg_img_repeat'                                           => 'repeat-y',
		'bio_border'                                                  => 'image',
		'bio_border_color'                                            => '#cccccc',
		'bio_btm_padding'                                             => '10',
		'bio_gutter_width'                                            => '10',
		'bio_header_font_color'                                       => '#C8D686',
		'bio_header_font_color_bind'                                  => 'on',
		'bio_header_font_family'                                      => 'LobsterTwoRegular, Arial, Helvetica, sans-serif',
		'bio_header_font_size'                                        => '28',
		'bio_header_font_style'                                       => 'normal',
		'bio_header_font_weight'                                      => '400',
		'bio_header_text_transform'                                   => 'none',
		'bio_lr_padding'                                              => '92',
		'bio_para_font_family'                                        => 'CopseRegular, Arial, Helvetica, sans-serif',
		'bio_widget_margin_btm'                                       => '5',
		'biopic_border'                                               => 'off',
		'biopic_border_color'                                         => '#1e1e1e',
		'blog_bg_color'                                               => '#ffffff',
		'blog_bg_color_bind'                                          => '',
		'blog_bg_img_position'                                        => 'top center',
		'blog_bg_inner_img_position'                                  => 'top center',
		'blog_bg_inner_img_repeat'                                    => 'no-repeat',
		'blog_border'                                                 => 'none',
		'blog_top_margin'                                             => '32',
		'blog_width'                                                  => '1057',
		'body_bg_color'                                               => '#fdfdfc',
		'body_bg_color_bind'                                          => '',
		'boxy_date_bg_color_bind'                                     => 'on',
		'call_to_action_1'                                            => 'back_to_top',
		'call_to_action_2'                                            => 'show_contact_form',
		'call_to_action_3'                                            => 'email_this_url',
		'call_to_action_enable'                                       => 'true',
		'call_to_action_font_color'                                   => '#7D892E',
		'call_to_action_font_color_bind'                              => 'on',
		'call_to_action_items_lr_spacing'                             => '36',
		'call_to_action_link_font_color'                              => '#8b8062',
		'call_to_action_link_font_color_bind'                         => 'on',
		'call_to_action_link_font_family'                             => 'CopseRegular, Arial, Helvetica, sans-serif',
		'call_to_action_link_font_size'                               => '14',
		'call_to_action_link_hover_font_color'                        => '#7D892E',
		'call_to_action_link_hover_font_color_bind'                   => 'on',
		'call_to_action_location'                                     => 'above_comments',
		'call_to_action_separator'                                    => 'image',
		'call_to_action_text_1'                                       => 'BACK TO TOP',
		'call_to_action_text_2'                                       => 'CONTACT ME',
		'call_to_action_text_3'                                       => 'EMAIL POST TO FRIEND',
		'categories_in_post_footer'                                   => 'yes',
		'categories_in_post_header'                                   => '',
		'comment_alt_bg_color_bind'                                   => '',
		'comment_author_link_font_color'                              => '#7d892e',
		'comment_author_link_font_color_bind'                         => 'on',
		'comment_author_link_font_weight'                             => '700',
		'comment_author_link_text_transform'                          => 'uppercase',
		'comment_bottom_border_color'                                 => '#8b8062',
		'comment_bottom_border_onoff'                                 => 'on',
		'comment_bottom_border_style'                                 => 'solid',
		'comment_count_in_post_header'                                => '',
		'comment_header_border_bottom'                                => '',
		'comment_header_border_top'                                   => '',
		'comment_lr_padding'                                          => '8',
		'comment_meta_margin_bottom'                                  => '5',
		'comment_tb_margin'                                           => '6',
		'comment_tb_padding'                                          => '10',
		'comment_timestamp_display'                                   => 'left',
		'comment_timestamp_font_color'                                => '#8b8062',
		'comment_timestamp_font_weight'                               => '400',
		'comment_timestamp_text_transform'                            => 'uppercase',
		'comments_addacomment_text'                                   => 'Comment',
		'comments_area_border_color'                                  => '#bbbaba',
		'comments_area_border_width'                                  => '0',
		'comments_area_lr_margin'                                     => '75',
		'comments_area_lr_margin_control'                             => 'set',
		'comments_body_area_bg_color'                                 => '#ffffff',
		'comments_body_area_bg_img_position'                          => 'top center',
		'comments_body_area_bg_img_repeat'                            => 'no-repeat',
		'comments_body_area_lr_margin'                                => '0',
		'comments_body_area_tb_margin'                                => '0',
		'comments_header_bg_color'                                    => '#c9dacd',
		'comments_header_bg_img_position'                             => 'top center',
		'comments_header_bg_img_repeat'                               => 'no-repeat',
		'comments_header_emailafriend_link_include'                   => 'no',
		'comments_header_emailafriend_link_text'                      => 'Email',
		'comments_header_font_color'                                  => '#8b8062',
		'comments_header_font_color_bind'                             => 'on',
		'comments_header_link_font_color'                             => '#8b8062',
		'comments_header_link_font_color_bind'                        => 'on',
		'comments_header_link_font_family'                            => 'CopseRegular, Arial, Helvetica, sans-serif',
		'comments_header_link_font_size'                              => '18',
		'comments_header_link_font_style'                             => 'normal',
		'comments_header_link_hover_decoration'                       => 'none',
		'comments_header_link_hover_font_color'                       => '#c8d686',
		'comments_header_link_hover_font_color_bind'                  => 'on',
		'comments_header_link_text_transform'                         => 'none',
		'comments_header_lr_padding'                                  => '25',
		'comments_header_post_interact_link_spacing'                  => '25',
		'comments_header_post_interaction_link_font_color'            => '#8b8062',
		'comments_header_post_interaction_link_font_color_bind'       => 'on',
		'comments_header_post_interaction_link_font_family'           => 'CopseRegular, Arial, Helvetica, sans-serif',
		'comments_header_post_interaction_link_font_size'             => '18',
		'comments_header_post_interaction_link_font_style'            => 'normal',
		'comments_header_post_interaction_link_hover_decoration'      => 'none',
		'comments_header_post_interaction_link_hover_font_color'      => '#c8d686',
		'comments_header_post_interaction_link_hover_font_color_bind' => 'on',
		'comments_header_post_interaction_link_text_transform'        => 'none',
		'comments_header_show_article_author'                         => 'false',
		'comments_header_tb_padding'                                  => '30',
		'comments_layout'                                             => 'minima',
		'comments_linktothispost_text'                                => 'Link',
		'comments_minima_hide_text'                                   => 'Hide',
		'comments_minima_show_text'                                   => 'Show',
		'comments_scrollbox_height'                                   => '400',
		'comments_show_hide_method'                                   => 'text',
		'contact_bg_img_position'                                     => 'top center',
		'contact_bg_img_repeat'                                       => 'repeat-y',
		'contact_btm_border'                                          => 'off',
		'contact_error_bg_color'                                      => '#ff8497',
		'contact_error_text_color'                                    => '#8b8062',
		'contact_success_bg_color'                                    => '#c8d686',
		'contact_success_text_color'                                  => '#8b8062',
		'content_margin'                                              => '75',
		'custom_font_1'                                               => '{"slug":"LobsterTwo-Regular","name":"LobsterTwoRegular"}',
		'custom_font_2'                                               => '{"slug":"Copse-Regular","name":"CopseRegular"}',
		'dateformat'                                                  => 'F j, Y',
		'drawer_default_bg_color'                                     => '#8b8062',
		'drawer_default_opacity'                                      => '100',
		'drawer_tab_font_color'                                       => '#F6F6EC',
		'drawer_tab_font_family'                                      => '',
		'drawer_widget_headlines_font_color'                          => '#c8d686',
		'drawer_widget_text_font_color'                               => '#F6F6EC',
		'drawer_widget_text_font_color_bind'                          => 'on',
		'drawer_widget_text_font_family'                              => 'Palatino, Georgia, serif',
		'excerpt_grid_rows'                                           => '6',
		'excerpt_grid_style'                                          => 'img_rollover_text',
		'excerpt_style'                                               => 'grid',
		'featured_galleries_converted'                                => 'true',
		'footer_bg_color'                                             => '#c9dacd',
		'footer_bg_color_bind'                                        => '',
		'footer_bg_img_position'                                      => 'top center',
		'footer_bg_img_repeat'                                        => 'repeat-y',
		'footer_font_color'                                           => '#8b8062',
		'footer_font_color_bind'                                      => 'on',
		'footer_headings_font_color'                                  => '#ff8497',
		'footer_headings_font_family'                                 => 'CopseRegular, Arial, Helvetica, sans-serif',
		'footer_headings_font_size'                                   => '19',
		'footer_headings_text_transform'                              => 'none',
		'footer_link_font_color'                                      => '#7d892e',
		'footer_link_font_color_bind'                                 => 'on',
		'footer_link_font_family'                                     => 'CopseRegular, Arial, Helvetica, sans-serif',
		'footer_link_hover_decoration'                                => 'none',
		'footer_link_hover_font_color'                                => '#c8d686',
		'footer_link_hover_font_color_bind'                           => 'on',
		'gen_font_color'                                              => '#8b8062',
		'gen_font_family'                                             => 'Palatino, Georgia, serif',
		'gen_line_height'                                             => '1.75',
		'gen_link_font_color'                                         => '#c8d686',
		'gen_link_font_color_bind'                                    => 'on',
		'gen_link_hover_decoration'                                   => 'none',
		'gen_link_hover_font_color'                                   => '#7d892e',
		'gen_link_hover_font_color_bind'                              => 'on',
		'grid_img_rollover_text_gutter'                               => '20',
		'header_bg_color'                                             => '#1e1e1e',
		'header_font_color'                                           => '#ff8497',
		'header_font_family'                                          => 'LobsterTwoRegular, Arial, Helvetica, sans-serif',
		'header_font_size'                                            => '28',
		'header_font_style'                                           => 'normal',
		'header_font_weight'                                          => '400',
		'header_letterspacing'                                        => 'normal',
		'headerlayout'                                                => 'logocenter_masthead_nav',
		'masthead_display'                                            => 'static',
		'masthead_slideshow_bg_color'                                 => '#fdfdfc',
		'masthead_slideshow_loop_images'                              => '1',
		'masthead_slideshow_transition_time'                          => '0.4',
		'mobile_article_excerpt_text_font_color'                      => '#8B8062',
		'mobile_article_excerpt_text_font_color_bind'                 => 'on',
		'mobile_article_excerpt_text_font_family'                     => 'CopseRegular, Arial, Helvetica, sans-serif',
		'mobile_article_excerpt_title_font_color'                     => '#8B8062',
		'mobile_article_excerpt_title_font_color_bind'                => 'on',
		'mobile_article_excerpt_title_font_family'                    => 'CopseRegular, Arial, Helvetica, sans-serif',
		'mobile_article_meta_below_title_font_color'                  => '#8B8062',
		'mobile_article_meta_below_title_font_color_bind'             => 'on',
		'mobile_article_meta_below_title_link_font_family'            => 'CopseRegular, Arial, Helvetica, sans-serif',
		'mobile_article_meta_below_title_link_hover_font_color'       => '#8B8062',
		'mobile_article_meta_below_title_link_hover_font_color_bind'  => 'on',
		'mobile_article_text_font_color'                              => '#8B8062',
		'mobile_article_text_font_color_bind'                         => 'on',
		'mobile_article_text_link_font_family'                        => 'CopseRegular, Arial, Helvetica, sans-serif',
		'mobile_article_title_font_color'                             => '#FF8497',
		'mobile_article_title_font_color_bind'                        => 'on',
		'mobile_article_title_font_family'                            => 'LobsterTwoRegular, Arial, Helvetica, sans-serif',
		'mobile_article_title_text_transform'                         => '',
		'mobile_button_bg_color'                                      => '#F6F6EC',
		'mobile_button_border_color'                                  => '#F6F6EC',
		'mobile_button_font_color'                                    => '#8B8062',
		'mobile_button_font_family'                                   => 'CopseRegular, Arial, Helvetica, sans-serif',
		'mobile_comments_area_bg_color'                               => '#F6F6EC',
		'mobile_comments_area_bg_color_bind'                          => 'on',
		'mobile_comments_area_font_color'                             => '#8B8062',
		'mobile_comments_area_font_color_bind'                        => 'on',
		'mobile_content_bg_color'                                     => '#F6F6EC',
		'mobile_content_bg_color_bind'                                => 'on',
		'mobile_font_color'                                           => '#8B8062',
		'mobile_font_family'                                          => 'CopseRegular, Arial, Helvetica, sans-serif',
		'mobile_footer_color_scheme'                                  => 'white',
		'mobile_headline_font_color'                                  => '#FF8497',
		'mobile_headline_font_family'                                 => 'LobsterTwoRegular, Arial, Helvetica, sans-serif',
		'mobile_link_font_color'                                      => '#5E6823',
		'mobile_logo_use_desktop'                                     => 'false',
		'mobile_masthead_display'                                     => 'off',
		'mobile_masthead_use_desktop_settings'                        => 'false',
		'mobile_post_comment_btn_bg_color'                            => '#F6F6EC',
		'mobile_post_comment_btn_bg_color_bind'                       => 'on',
		'nav_below_link_font_color'                                   => '#8b8062',
		'nav_below_link_font_color_bind'                              => 'on',
		'nav_below_link_font_family'                                  => 'CopseRegular, Arial, Helvetica, sans-serif',
		'nav_below_link_font_size'                                    => '11',
		'nav_below_link_font_weight'                                  => '700',
		'nav_below_link_hover_font_color'                             => '#8b8062',
		'nav_below_link_hover_font_color_bind'                        => 'on',
		'nav_below_link_text_transform'                               => 'uppercase',
		'nav_below_link_visited_font_color'                           => '#8b8062',
		'nav_below_link_visited_font_color_bind'                      => 'on',
		'nav_bg_img_position'                                         => 'top center',
		'nav_bg_img_repeat'                                           => 'no-repeat',
		'override_css'                                                => '/* start custom CSS for \"Emilie\" starter-design */
#primary-nav {
	padding-top: 15px;
	background-repeat: no-repeat;
	height: 50px;
}
#contact-form form.with-widget-content { margin-left: 48%; }
#contact-form #widget-content { padding-left: 9.5%; }
#contact-form textarea { width: 86%; }
/* end custom CSS for \"Emilie\" starter-design */
',
		'padding_below_post'                            => '25',
		'page_bg_img_position'                          => 'top center',
		'page_bg_img_repeat'                            => 'no-repeat',
		'pagination_next_text'                          => 'Next »',
		'pagination_prev_text'                          => '« Prev',
		'portfoliotarget'                               => '_blank',
		'post_bg_img_position'                          => 'top center',
		'post_bg_img_repeat'                            => 'no-repeat',
		'post_divider'                                  => 'image',
		'post_footer_meta_font_color'                   => '#8b8062',
		'post_footer_meta_font_color_bind'              => 'on',
		'post_footer_meta_link_font_color'              => '#7d892e',
		'post_footer_meta_link_font_color_bind'         => 'on',
		'post_footer_meta_link_font_family'             => 'CopseRegular, Arial, Helvetica, sans-serif',
		'post_footer_meta_link_font_size'               => '12',
		'post_footer_meta_link_font_weight'             => '400',
		'post_footer_meta_link_hover_decoration'        => 'none',
		'post_footer_meta_link_hover_font_color'        => '#c8d686',
		'post_footer_meta_link_hover_font_color_bind'   => 'on',
		'post_footer_meta_link_text_transform'          => 'uppercase',
		'post_header_align'                             => 'left',
		'post_header_margin_above'                      => '32',
		'post_header_margin_below'                      => '42',
		'post_header_meta_font_color'                   => '#8b8062',
		'post_header_meta_font_color_bind'              => 'on',
		'post_header_meta_link_font_color'              => '#7d892e',
		'post_header_meta_link_font_color_bind'         => 'on',
		'post_header_meta_link_font_family'             => 'CopseRegular, Arial, Helvetica, sans-serif',
		'post_header_meta_link_font_size'               => '12',
		'post_header_meta_link_font_weight'             => '400',
		'post_header_meta_link_hover_decoration'        => 'none',
		'post_header_meta_link_hover_font_color'        => '#c8d686',
		'post_header_meta_link_hover_font_color_bind'   => 'on',
		'post_header_meta_link_text_transform'          => 'uppercase',
		'post_header_postdate_font_color'               => '#8b8062',
		'post_header_postdate_font_color_bind'          => 'on',
		'post_header_postdate_font_family'              => 'CopseRegular, Arial, Helvetica, sans-serif',
		'post_header_postdate_font_size'                => '18',
		'post_header_postdate_font_style'               => 'normal',
		'post_header_postdate_font_weight'              => '400',
		'post_header_postdate_letterspacing'            => 'normal',
		'post_header_postdate_margin_bottom'            => '15',
		'post_header_postdate_text_transform'           => 'none',
		'post_pic_border_color'                         => '#ffffff',
		'post_text_font_color'                          => '#8b8062',
		'post_text_font_color_bind'                     => 'on',
		'post_text_font_family'                         => 'CopseRegular, Arial, Helvetica, sans-serif',
		'post_text_link_font_color'                     => '#8b8062',
		'post_text_link_font_color_bind'                => 'on',
		'post_text_link_font_family'                    => 'CopseRegular, Arial, Helvetica, sans-serif',
		'post_text_link_hover_font_color'               => '#C8D686',
		'post_text_link_hover_font_color_bind'          => 'on',
		'post_title_link_font_color'                    => '#FF8497',
		'post_title_link_font_color_bind'               => 'on',
		'post_title_link_font_family'                   => 'LobsterTwoRegular, Arial, Helvetica, sans-serif',
		'post_title_link_font_size'                     => '30',
		'post_title_link_font_style'                    => 'normal',
		'post_title_link_font_weight'                   => '400',
		'post_title_link_hover_decoration'              => 'none',
		'post_title_link_hover_font_color'              => '#FFBFA8',
		'post_title_link_hover_font_color_bind'         => 'on',
		'post_title_link_margin_bottom'                 => '5',
		'post_title_link_text_transform'                => 'none',
		'postdate_bg_color'                             => '#a8ab9b',
		'postdate_bg_color_bind'                        => 'on',
		'postdate_border_bottom'                        => 'on',
		'postdate_border_color'                         => '#ffffff',
		'postdate_border_style'                         => 'double',
		'postdate_border_top'                           => 'on',
		'postdate_border_width'                         => '3',
		'postdate_lr_padding'                           => '18',
		'postdate_placement'                            => 'withtitle',
		'postdate_tb_padding'                           => '4',
		'primary_nav_menu_align'                        => 'center',
		'primary_nav_menu_bg_color'                     => '#88b2ab',
		'primary_nav_menu_bg_color_bind'                => '',
		'primary_nav_menu_btm_border_color'             => '#F6F6EC',
		'primary_nav_menu_btm_border_width'             => '9',
		'primary_nav_menu_dropdown_bg_color'            => '#c8d686',
		'primary_nav_menu_dropdown_bg_color_bind'       => 'on',
		'primary_nav_menu_dropdown_bg_hover_color'      => '#d7e0ae',
		'primary_nav_menu_dropdown_bg_hover_color_bind' => 'on',
		'primary_nav_menu_dropdown_link_textsize'       => '12',
		'primary_nav_menu_item_1'                       => '{"type":"internal","internalType":"home","text":"Home"}',
		'primary_nav_menu_item_10'                      => '{"type":"manual","text":"WordPress Blog","url":"http://wordpress.org/news/"}',
		'primary_nav_menu_item_11'                      => '{"type":"manual","text":"WordPress Planet","url":"http://planet.wordpress.org/"}',
		'primary_nav_menu_item_12'                      => '{"type":"internal","internalType":"categories","text":"Categories"}',
		'primary_nav_menu_item_13'                      => '{"type":"internal","internalType":"rss","text":"Subscribe","anchor":"text"}',
		'primary_nav_menu_item_14'                      => '{"type":"special","searchBtnText":"search","text":"Search","specialType":"dropdown_search"}',
		'primary_nav_menu_item_15'                      => '{"type":"special","specialType":"show_contact_form","text":"Contact"}',
		'primary_nav_menu_item_2'                       => '{"type":"manual","url":"","text":"Portfolio","target":""}',
		'primary_nav_menu_item_3'                       => '{"type":"internal","internalType":"featured_slideshows","text":"Galleries"}',
		'primary_nav_menu_item_4'                       => '{"type":"container","text":"Links"}',
		'primary_nav_menu_item_5'                       => '{"type":"manual","text":"Documentation","url":"http://codex.wordpress.org/"}',
		'primary_nav_menu_item_6'                       => '{"type":"manual","text":"Plugins","url":"http://wordpress.org/extend/plugins/"}',
		'primary_nav_menu_item_7'                       => '{"type":"manual","text":"Suggest Ideas","url":"http://wordpress.org/extend/ideas/"}',
		'primary_nav_menu_item_8'                       => '{"type":"manual","text":"Support Forum","url":"http://wordpress.org/support/"}',
		'primary_nav_menu_item_9'                       => '{"type":"manual","text":"Themes","url":"http://wordpress.org/extend/themes/"}',
		'primary_nav_menu_link_font_color'              => '#8b8062',
		'primary_nav_menu_link_font_family'             => 'CopseRegular, Arial, Helvetica, sans-serif',
		'primary_nav_menu_link_font_weight'             => '400',
		'primary_nav_menu_link_hover_decoration'        => 'none',
		'primary_nav_menu_link_letterspacing'           => 'normal',
		'primary_nav_menu_link_spacing_between'         => '50',
		'primary_nav_menu_link_text_transform'          => 'uppercase',
		'primary_nav_menu_structure'                    => '{"primary_nav_menu_item_1":"primary_nav_menu_item_1","primary_nav_menu_item_2":"primary_nav_menu_item_2","primary_nav_menu_item_4":{"primary_nav_menu_item_5":"primary_nav_menu_item_5","primary_nav_menu_item_6":"primary_nav_menu_item_6","primary_nav_menu_item_7":"primary_nav_menu_item_7","primary_nav_menu_item_8":"primary_nav_menu_item_8","primary_nav_menu_item_9":"primary_nav_menu_item_9","primary_nav_menu_item_10":"primary_nav_menu_item_10","primary_nav_menu_item_11":"primary_nav_menu_item_11"},"primary_nav_menu_item_12":"primary_nav_menu_item_12","primary_nav_menu_item_13":"primary_nav_menu_item_13","primary_nav_menu_item_14":"primary_nav_menu_item_14","primary_nav_menu_item_15":"primary_nav_menu_item_15"}',
		'sidebar_border_switch'                         => 'off',
		'slideshow_bg_color'                            => '#F6F6EC',
		'slideshow_btns_color'                          => '#7d892e',
		'slideshow_subtitle_font_color'                 => '#ffbfa8',
		'slideshow_subtitle_font_color_bind'            => 'on',
		'slideshow_subtitle_font_family'                => 'CopseRegular, Arial, Helvetica, sans-serif',
		'slideshow_thumb_border_color'                  => '#ffffff',
		'slideshow_title_font_color'                    => '#ff8497',
		'slideshow_title_font_family'                   => 'LobsterTwoRegular, Arial, Helvetica, sans-serif',
		'tags_in_post_footer'                           => 'yes',
		'tags_in_post_header'                           => '',
		'widget_menu_1_item_1'                          => '{"text":"Facebook","type":"manual","url":"http://www.facebook.com/pages/Prophoto-Blogs/110888486694","anchor":"img"}',
		'widget_menu_1_item_2'                          => '{"text":"Twitter","type":"manual","url":"http://twitter.com/prophotoblogs","anchor":"img"}',
		'widget_menu_1_item_3'                          => '{"text":"RSS","type":"internal","internalType":"rss","anchor":"img"}',
		'widget_menu_1_li_list_style'                   => 'none',
		'widget_menu_1_structure'                       => '{"widget_menu_1_item_1":"widget_menu_1_item_1","widget_menu_1_item_2":"widget_menu_1_item_2", "widget_menu_1_item_3":"widget_menu_1_item_3"}',
		'widget_menu_1_sub_li_list_style'               => 'none',
		'widget_menu_1_sub_sub_li_list_style'           => 'none',
	),

	'activation_widgets' => array(

		'bio-spanning-col' => 'empty',

		'bio-col-1' => array(
			'1' => array(
				'pp-text' => array(
					'title' => 'Welcome to my blog!',
					'text' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit.
',
					'wpautop' => '1',
				),

			),

		),

		'bio-col-2' => array(
			'1' => array(
				'pp-vertical-nav-menu' => array(
					'title' => '',
					'widget_menu_num' => '1',
				),

			),

		),

		'bio-col-3'     => 'empty',
		'bio-col-4'     => 'empty',
		'fixed-sidebar' => 'empty',

	),

	'imgs' => array(
		'bio_bg'                       => 'emilie_all_content_areas_bg.png',
		'bio_separator'                => 'emilie_bio_separator.png',
		'biopic1'                      => 'emilie_biopic1.png',
		'blog_bg'                      => 'emilie_blog_bg.jpg',
		'blog_bg_inner'                => 'emilie_blog_bg_inner.png',
		'body_bg'                      => 'emilie_all_content_areas_bg.png',
		'call_to_action_separator_img' => 'emilie_call_to_action_separator_img.png',
		'comments_header_bg'           => 'emilie_comments_header_bg.png',
		'contact_bg'                   => 'emilie_all_content_areas_bg.png',
		'footer_bg'                    => 'emilie_all_content_areas_bg.png',
		'logo'                         => 'emilie_logo.png',
		'masthead_image1'              => 'emilie_masthead_image1.png',
		'mobile_logo'                  => 'emilie_mobile_logo.png',
		'post_bg'                      => 'emilie_post_bg.png',
		'post_sep'                     => 'emilie_post_sep.png',
		'primary_nav_menu_bg'          => 'emilie_primary_nav_menu_bg.png',
		'widget_custom_image_1'        => 'emilie_facebook.png',
		'widget_custom_image_2'        => 'emilie_twitter.png',
		'widget_custom_image_3'        => 'emilie_rss.png',
		'widget_menu_1_item_1'         => 'emilie_facebook.png',
		'widget_menu_1_item_2'         => 'emilie_twitter.png',
		'widget_menu_1_item_3'         => 'emilie_rss.png',
	),

	'remote_files' => array(

		'Copse-Regular-webfont.eot' => array(
			'hash' => '85fd1c595546889950ba28046c5b4141',
		),

		'Copse-Regular-webfont.svg' => array(
			'hash' => 'c96fc95898d6831355ba3efdf21bed33',
		),

		'Copse-Regular-webfont.ttf' => array(
			'hash' => '24af68d354bb10635db2567809b1f1a6',
		),

		'Copse-Regular-webfont.woff' => array(
			'hash' => '219a3b8de8337b95ccb27397af5e54b5',
		),

		'emilie_all_content_areas_bg.png' => array(
			'hash'   => '5e3167264998c2cad228ff0d7b898b8f',
			'width'  => '1056',
			'height' => '25',
			'size'   => '1',
		),

		'emilie_bio_separator.png' => array(
			'hash'   => '14e71eb670e230a30c3f7017c194c495',
			'width'  => '1056',
			'height' => '36',
			'size'   => '1',
		),

		'emilie_biopic1.png' => array(
			'hash'   => '67e171c120d133c7a3414c9a8e3728aa',
			'width'  => '306',
			'height' => '275',
			'size'   => '99',
		),

		'emilie_blog_bg.jpg' => array(
			'hash'   => '0b72d7469d8a764f1f3ecbc5810d3155',
			'width'  => '400',
			'height' => '400',
			'size'   => '27',
		),

		'emilie_blog_bg_inner.png' => array(
			'hash'   => 'ce8b33b45f8d56731e78426cda5a8154',
			'width'  => '1500',
			'height' => '547',
			'size'   => '222',
		),

		'emilie_call_to_action_separator_img.png' => array(
			'hash'   => 'd45d9e21d44ffc50edaee4764ea12843',
			'width'  => '22',
			'height' => '22',
			'size'   => '1',
		),

		'emilie_comments_header_bg.png' => array(
			'hash'   => '5b4b68d1b1456aca55697bc51e111b8b',
			'width'  => '1056',
			'height' => '73',
			'size'   => '50',
		),

		'emilie_facebook.png' => array(
			'hash'   => 'd7665e58aa36dc815944c945535fb638',
			'width'  => '175',
			'height' => '65',
			'size'   => '3',
		),

		'emilie_logo.png' => array(
			'hash'   => '411def6579764ed1392ecdd84cb5aa4e',
			'width'  => '1057',
			'height' => '145',
			'size'   => '7',
		),

		'emilie_masthead_image1.png' => array(
			'hash'   => 'dc41a45bd66d80dcb216e7f5a124e755',
			'width'  => '1057',
			'height' => '428',
			'size'   => '504',
		),

		'emilie_mobile_logo.png' => array(
			'hash'   => 'f3b41aa9ec4ba9409c7f855ef13527ca',
			'width'  => '1500',
			'height' => '531',
			'size'   => '162',
		),

		'emilie_post_bg.png' => array(
			'hash'   => '802b94b7636e5b55cbf53c0e1dd22b5d',
			'width'  => '1056',
			'height' => '88',
			'size'   => '13',
		),

		'emilie_post_sep.png' => array(
			'hash'   => '45e96dd2db3e6ec41c8bbec21c9925f9',
			'width'  => '1056',
			'height' => '73',
			'size'   => '8',
		),

		'emilie_primary_nav_menu_bg.png' => array(
			'hash'   => '78bc0b1fd5fbb5c16a1b1c79301839d6',
			'width'  => '1057',
			'height' => '65',
			'size'   => '29',
		),

		'emilie_rss.png' => array(
			'hash'   => '72e6ee552232dc4ba6259e587fb32c29',
			'width'  => '175',
			'height' => '65',
			'size'   => '3',
		),

		'emilie_twitter.png' => array(
			'hash'   => 'e920ccf800097ffea05405b117a268b7',
			'width'  => '175',
			'height' => '65',
			'size'   => '2',
		),
	),

);


