<?php

$configArray = array(

	'meta' => array(
		'name' => 'Grunge',
		'desc' => 'The first thing you notice about Grunge is the retro header.  Like a sticker you’d find on an old VW bus or the faded logo of your dad’s favorite t-shirt from the 70s.  Right away you settle in to the relaxed feel of this template.  Grunge rounds things out with the textures of walk through the concrete jungle.',
	),

	'options' => array(
		'bg_color'                                                      => '#000000',
		'body_bg_color'                                                 => '#e7e6e2',
		'bgimg_repeat'                                                  => 'repeat',
		'bgimg_attachment'                                              => 'fixed',
		'bgimg_position'                                                => 'top left',
		'headerlayout'                                                  => 'logocenter_masthead_nav',
		'masthead_top_border_color'                                     => '#000000',
		'masthead_top_border_style'                                     => 'solid',
		'masthead_btm_border_color'                                     => '#000000',
		'masthead_btm_border_style'                                     => 'solid',
		'masthead_display'                                              => 'off',
		'primary_nav_menu_link_font_family'                             => 'Helvetica, Arial, sans-serif',
		'primary_nav_menu_link_font_weight'                             => '400',
		'primary_nav_menu_link_text_transform'                          => 'uppercase',
		'primary_nav_menu_link_font_color'                              => '#fdc481',
		'primary_nav_menu_link_hover_decoration'                        => 'none',
		'primary_nav_menu_link_hover_font_color_bind'                   => 'on',
		'primary_nav_menu_link_visited_font_color_bind'                 => 'on',
		'primary_nav_menu_dropdown_link_font_color_bind'                => 'on',
		'primary_nav_menu_dropdown_link_hover_font_color_bind'          => 'on',
		'primary_nav_menu_link_font_size'                               => '15',
		'primary_nav_menu_dropdown_bg_color_bind'                       => 'on',
		'primary_nav_menu_dropdown_bg_color'                            => '#000000',
		'primary_nav_menu_dropdown_bg_hover_color_bind'                 => 'on',
		'primary_nav_menu_dropdown_opacity'                             => '85',
		'primary_nav_menu_link_spacing_between'                         => '40',
		'primary_nav_menu_top_border_color'                             => '#000000',
		'primary_nav_menu_top_border_style'                             => 'solid',
		'primary_nav_menu_btm_border_color'                             => '#000000',
		'primary_nav_menu_btm_border_style'                             => 'solid',
		'primary_nav_menu_link_hover_font_color'                        => '#59c281',
		'primary_nav_menu_link_visited_font_color'                      => '#fdc481',
		'bio_top_padding'                                               => '20',
		'bio_btm_padding'                                               => '20',
		'bio_gutter_width'                                              => '25',
		'bio_lr_padding'                                                => '18',
		'bio_header_font_color_bind'                                    => 'on',
		'bio_para_font_size'                                            => '12',
		'bio_para_font_family'                                          => 'Arial, Helvetica, sans-serif',
		'bio_para_font_weight'                                          => '400',
		'bio_para_font_style'                                           => 'normal',
		'bio_para_text_transform'                                       => 'none',
		'bio_para_font_color_bind'                                      => 'on',
		'bio_bg'                                                        => 'gradient',
		'bio_bg_color'                                                  => '#000000',
		'bio_border'                                                    => 'noborder',
		'gen_font_family'                                               => 'Helvetica, Arial, sans-serif',
		'gen_font_weight'                                               => '400',
		'gen_font_style'                                                => 'normal',
		'gen_text_transform'                                            => 'none',
		'gen_font_color'                                                => '#333333',
		'gen_link_font_weight'                                          => '400',
		'gen_link_text_transform'                                       => 'none',
		'gen_link_font_color_bind'                                      => 'on',
		'gen_link_font_color'                                           => '#36e4da',
		'header_font_size'                                              => '26',
		'header_font_family'                                            => '"Century Gothic", Helvetica, Arial, sans-serif',
		'header_font_weight'                                            => '400',
		'header_font_style'                                             => 'normal',
		'header_font_color'                                             => '#371f14',
		'post_header_margin_above'                                      => '48',
		'post_header_margin_below'                                      => '40',
		'postdate_display'                                              => 'boxy',
		'boxy_date_font_size'                                           => '14',
		'boxy_date_bg_color'                                            => '#000000',
		'boxy_date_align'                                               => 'right',
		'boxy_date_month_color'                                         => '#fdc481',
		'boxy_date_day_color'                                           => '#fdc481',
		'boxy_date_year_color'                                          => '#ffffff',
		'comment_count_in_post_header'                                  => 'yes',
		'post_title_link_font_size'                                     => '28',
		'post_title_link_font_weight'                                   => '400',
		'post_title_link_font_style'                                    => 'normal',
		'post_title_link_text_transform'                                => 'none',
		'post_title_link_font_color_bind'                               => 'on',
		'post_title_link_hover_font_color_bind'                         => 'on',
		'post_title_link_visited_font_color_bind'                       => 'on',
		'post_header_meta_link_font_size'                               => '14',
		'post_header_meta_link_font_family'                             => '"Century Gothic", Helvetica, Arial, sans-serif',
		'post_header_meta_link_font_weight'                             => '400',
		'post_header_meta_link_font_style'                              => 'italic',
		'post_header_meta_link_text_transform'                          => 'none',
		'post_header_meta_link_decoration'                              => 'none',
		'post_header_meta_font_color_bind'                              => 'on',
		'post_header_meta_link_font_color_bind'                         => 'on',
		'post_header_meta_link_hover_font_color_bind'                   => 'on',
		'post_header_meta_link_visited_font_color_bind'                 => 'on',
		'postdate_border_top'                                           => 'on',
		'postdate_border_bottom'                                        => 'on',
		'postdate_border_left'                                          => 'on',
		'postdate_border_right'                                         => 'on',
		'postdate_border_color'                                         => '#371f14',
		'postdate_border_width'                                         => '1',
		'postdate_border_style'                                         => 'solid',
		'post_pic_border_color'                                         => '#000000',
		'comments_layout'                                               => 'minima',
		'comments_area_lr_margin_control'                               => 'set',
		'comments_header_bg_color'                                      => '#ffffff',
		'comments_area_border_style'                                    => 'dashed',
		'comments_header_show_article_author'                           => 'false',
		'comments_header_lr_padding'                                    => '55',
		'comments_header_link_font_size'                                => '15',
		'comments_header_link_font_family'                              => '"Comic Sans MS", Arial, sans-serif',
		'comments_header_link_font_weight'                              => '700',
		'comments_header_link_font_style'                               => 'normal',
		'comments_header_link_text_transform'                           => 'none',
		'comments_header_link_decoration'                               => 'none',
		'comments_header_font_color_bind'                               => 'on',
		'comments_header_link_hover_decoration'                         => 'none',
		'comments_header_post_interaction_link_font_size'               => '13',
		'comments_header_post_interaction_link_font_family'             => 'Garamond, Palatino, Georgia, serif',
		'comments_header_post_interaction_link_font_weight'             => '400',
		'comments_header_post_interaction_link_font_style'              => 'normal',
		'comments_header_post_interaction_link_text_transform'          => 'uppercase',
		'comments_header_post_interaction_link_decoration'              => 'none',
		'comments_header_post_interaction_link_font_color_bind'         => 'on',
		'comments_header_post_interaction_link_hover_decoration'        => 'none',
		'comments_header_post_interaction_link_hover_font_color_bind'   => 'on',
		'comments_header_post_interaction_link_visited_font_color_bind' => 'on',
		'comments_show_hide_method'                                     => 'text',
		'comments_post_interact_display'                                => 'images',
		'comments_header_post_interact_link_spacing'                    => '20',
		'comments_header_emailafriend_link_include'                     => 'no',
		'comments_header_emailafriend_link_subject'                     => pp::site()->name,
		'comment_timestamp_font_color'                                  => '#888888',
		'comments_header_post_interaction_link_font_color'              => '#371f14',
		'comments_header_link_font_color_bind'                          => 'on',
		'comments_header_link_font_color'                               => '#454545',
		'comments_header_link_hover_font_color'                         => '#36e4da',
		'comments_header_post_interaction_link_hover_font_color'        => '#36e4da',
		'comments_header_post_interaction_link_visited_font_color'      => '#371f14',
		'postdate_bg_color'                                             => '#000000',
		'primary_nav_menu_dropdown_link_font_color'                     => '#fdc481',
		'primary_nav_menu_dropdown_link_hover_font_color'               => '#000000',
		'primary_nav_menu_bg_color'                                     => '#000000',
		'primary_nav_menu_dropdown_bg_hover_color'                      => '#fdc481',
		'post_title_link_font_color'                                    => '#000000',
		'post_title_link_hover_font_color'                              => '#000000',
		'post_title_link_visited_font_color'                            => '#000000',
		'post_header_meta_font_color'                                   => '#666666',
		'post_header_meta_link_font_color'                              => '#853c22',
		'post_header_meta_link_hover_font_color'                        => '#853c22',
		'post_header_meta_link_visited_font_color'                      => '#853c22',
		'bio_para_font_color'                                           => '#f0c898',
		'post_bg_img_repeat'                                            => 'no-repeat',
		'post_bg_img_position'                                          => 'top center',
		'post_bg_img_attachment'                                        => 'scroll',
		'bio_inner_bg_img_repeat'                                       => 'no-repeat',
		'bio_inner_bg_img_position'                                     => 'top right',
		'bio_header_font_color'                                         => '#E7E6E2',
		'blog_border'                                                   => 'none',
		'biopic_border_width'                                           => '0',
		'comments_area_lr_margin'                                       => '17',
		'comment_bg_color_bind'                                         => 'on',
		'comments_header_bg_img_repeat'                                 => 'no-repeat',
		'comments_header_bg_img_position'                               => 'bottom right',
		'comment_meta_position'                                         => 'inline',
		'comment_author_link_font_weight'                               => '700',
		'comment_author_link_text_transform'                            => 'uppercase',
		'comment_author_link_font_color_bind'                           => 'on',
		'comment_timestamp_text_transform'                              => 'uppercase',
		'comment_text_and_link_font_size'                               => '12',
		'comment_tb_padding'                                            => '7',
		'comment_lr_padding'                                            => '7',
		'comments_body_area_lr_margin'                                  => '13',
		'comments_body_area_tb_margin'                                  => '18',
		'comment_tb_margin'                                             => '10',
		'comments_header_bg_img_attachment'                             => 'scroll',
		'comment_author_link_font_color'                                => '#853C22',
		'comment_bg_color'                                              => '#d3d1ca',
		'comments_area_border_width'                                    => '0',
		'comment_alt_bg_color_bind'                                     => '',
		'comments_header_font_color'                                    => '#454545',
	),


	'activation_widgets' => array(
		'fixed-sidebar' => 'empty',
	),


	'imgs' => array(
		'blog_bg'                                   => 'grunge_blog_bg.jpg',
		'logo'                                      => 'grunge_logo.jpg',
		'biopic1'                                   => 'grunge_biopic1.jpg',
		'comments_header_addacomment_link_image'    => 'grunge_comments_header_addacomment_link_image.png',
		'comments_header_linktothispost_link_image' => 'grunge_comments_header_linktothispost_link_image.png',
		'comments_header_emailafriend_link_image'   => 'grunge_comments_header_emailafriend_link_image.png',
		'post_bg'                                   => 'grunge_post_bg.jpg',
		'bio_bg'                                    => 'grunge_bio_bg.jpg',
		'comments_header_bg'                        => 'grunge_comments_header_bg.png',
	),


	'remote_files' => array(

		'grunge_bio_bg.jpg' => array(
			'hash'   => 'bbf04a0d898526afccf38301194dc4a4',
			'width'  => '960',
			'height' => '340',
			'size'   => '14',
		),

		'grunge_biopic1.jpg' => array(
			'hash'   => '04d75f85f3fe107d184a16d80d10223e',
			'width'  => '590',
			'height' => '300',
			'size'   => '39',
		),

		'grunge_blog_bg.jpg' => array(
			'hash'   => '451ba6eae0dffcfa257a298f9ed0d3a5',
			'width'  => '244',
			'height' => '554',
			'size'   => '17',
		),

		'grunge_comments_header_addacomment_link_image.png' => array(
			'hash'   => '2841c4074db6a50ca488e557c4eebf5e',
			'width'  => '121',
			'height' => '23',
			'size'   => '1',
		),

		'grunge_comments_header_bg.png' => array(
			'hash'   => 'f251b6f3f76d8983cd266ac4f5f2625c',
			'width'  => '985',
			'height' => '41',
			'size'   => '1',
		),

		'grunge_comments_header_emailafriend_link_image.png' => array(
			'hash'   => '01e34a8be6639df0311d7ed53a677e8b',
			'width'  => '123',
			'height' => '23',
			'size'   => '1',
		),

		'grunge_comments_header_linktothispost_link_image.png' => array(
			'hash'   => '7e75f30701b7522af18899d39e67abd8',
			'width'  => '127',
			'height' => '23',
			'size'   => '1',
		),

		'grunge_logo.jpg' => array(
			'hash'   => 'cc3d0a5405c037958c83ad02108d882c',
			'width'  => '960',
			'height' => '138',
			'size'   => '19',
		),

		'grunge_post_bg.jpg' => array(
			'hash'   => 'ee86faae8bb988adc3259c774364142e',
			'width'  => '960',
			'height' => '299',
			'size'   => '11',
		),
	),

);

