<?php

$configArray = array(

	'meta' => array(
		'name' => 'Mercury',
		'desc' => 'With touch of retro funk and a masculine, modern twist, Mercury is perfect for those photogs looking for just a bit of edge. Designed for ProPhoto4 by <a href="http://www.swoone.com">Swoone</a>, Mercury uses a simple, clean layout easy for your clients to navigate while grabbing their attention with design elements that really pop.',
	),

	'options' => array(
		'archive_h2_font_color'                                       => '#29ABE2',
		'bio_include'                                                 => 'no',
		'blog_bg_color'                                               => '#EFF0EE',
		'blog_bg_img_attachment'                                      => 'fixed',
		'blog_bg_img_position'                                        => 'top center',
		'blog_border'                                                 => 'none',
		'blog_btm_margin'                                             => '30',
		'blog_top_margin'                                             => '30',
		'blog_width'                                                  => '980',
		'body_bg_color'                                               => '#fdfdfc',
		'body_bg_color_bind'                                          => '',
		'boxy_date_bg_color_bind'                                     => 'on',
		'call_to_action_1'                                            => 'back_to_top',
		'call_to_action_2'                                            => 'show_contact_form',
		'call_to_action_3'                                            => 'share_on_facebook',
		'call_to_action_4'                                            => 'tweet_this_url',
		'call_to_action_5'                                            => 'email_this_url',
		'call_to_action_area_btm_padding'                             => '7',
		'call_to_action_display_1'                                    => 'image',
		'call_to_action_display_2'                                    => 'image',
		'call_to_action_display_3'                                    => 'image',
		'call_to_action_display_4'                                    => 'image',
		'call_to_action_display_5'                                    => 'image',
		'call_to_action_enable'                                       => 'true',
		'call_to_action_font_color'                                   => '#29ABE2',
		'call_to_action_font_color_bind'                              => 'on',
		'call_to_action_items_lr_spacing'                             => '14',
		'call_to_action_link_decoration'                              => 'none',
		'call_to_action_link_font_color'                              => '#29ABE2',
		'call_to_action_link_font_color_bind'                         => 'on',
		'call_to_action_link_font_family'                             => 'AliceRegular, Arial, Helvetica, sans-serif',
		'call_to_action_link_font_size'                               => '12',
		'call_to_action_link_hover_decoration'                        => 'none',
		'call_to_action_link_hover_font_color'                        => '#000000',
		'call_to_action_link_hover_font_color_bind'                   => 'on',
		'call_to_action_link_text_transform'                          => 'uppercase',
		'call_to_action_location'                                     => 'above_comments',
		'call_to_action_separator_text'                               => '•',
		'call_to_action_text_1'                                       => 'Back to Top',
		'call_to_action_text_2'                                       => 'Contact Me',
		'call_to_action_text_3'                                       => 'Share on Facebook',
		'call_to_action_text_4'                                       => 'Tweet this Post',
		'call_to_action_text_5'                                       => 'Email to a Friend',
		'categories_in_post_footer'                                   => 'yes',
		'categories_in_post_header'                                   => '',
		'comment_alt_bg_color_bind'                                   => '',
		'comment_author_link_font_color'                              => '#29ABE2',
		'comment_author_link_font_color_bind'                         => 'on',
		'comment_author_link_font_weight'                             => '700',
		'comment_author_link_text_transform'                          => 'none',
		'comment_bottom_border_color'                                 => '#666666',
		'comment_bottom_border_onoff'                                 => 'on',
		'comment_bottom_border_style'                                 => 'solid',
		'comment_count_in_post_header'                                => '',
		'comment_header_border_bottom'                                => '',
		'comment_header_border_top'                                   => '',
		'comment_lr_padding'                                          => '8',
		'comment_meta_margin_bottom'                                  => '5',
		'comment_tb_margin'                                           => '6',
		'comment_tb_padding'                                          => '10',
		'comment_text_and_link_font_family'                           => 'Times, Georgia, serif',
		'comment_timestamp_font_color'                                => '#29ABE2',
		'comment_timestamp_font_weight'                               => '700',
		'comment_timestamp_text_transform'                            => 'none',
		'comments_area_border_color'                                  => '#bbbaba',
		'comments_area_border_width'                                  => '0',
		'comments_area_lr_margin_control'                             => 'set',
		'comments_body_area_bg_color'                                 => '#ffffff',
		'comments_body_area_bg_img_position'                          => 'top center',
		'comments_body_area_bg_img_repeat'                            => 'no-repeat',
		'comments_body_area_tb_margin'                                => '0',
		'comments_header_bg_color'                                    => '#c9dacd',
		'comments_header_emailafriend_link_include'                   => 'no',
		'comments_header_font_color'                                  => '#000000',
		'comments_header_font_color_bind'                             => 'on',
		'comments_header_link_decoration'                             => 'none',
		'comments_header_link_font_color'                             => '#000000',
		'comments_header_link_font_color_bind'                        => 'on',
		'comments_header_link_font_family'                            => 'AliceRegular, Arial, Helvetica, sans-serif',
		'comments_header_link_font_style'                             => 'normal',
		'comments_header_link_hover_decoration'                       => 'none',
		'comments_header_link_hover_font_color'                       => '#29ABE2',
		'comments_header_link_hover_font_color_bind'                  => 'on',
		'comments_header_link_text_transform'                         => 'uppercase',
		'comments_header_linktothispost_link_include'                 => 'no',
		'comments_header_post_interact_link_spacing'                  => '15',
		'comments_header_post_interaction_link_font_color'            => '#000000',
		'comments_header_post_interaction_link_font_color_bind'       => 'on',
		'comments_header_post_interaction_link_font_family'           => 'AliceRegular, Arial, Helvetica, sans-serif',
		'comments_header_post_interaction_link_font_size'             => '13',
		'comments_header_post_interaction_link_font_style'            => 'normal',
		'comments_header_post_interaction_link_hover_decoration'      => 'none',
		'comments_header_post_interaction_link_hover_font_color'      => '#29ABE2',
		'comments_header_post_interaction_link_hover_font_color_bind' => 'on',
		'comments_header_post_interaction_link_text_transform'        => 'uppercase',
		'comments_header_show_article_author'                         => 'false',
		'comments_in_scrollbox_on_home'                               => 'false',
		'comments_layout'                                             => 'minima',
		'comments_minima_hide_text'                                   => 'Hide',
		'comments_minima_show_text'                                   => 'Show',
		'comments_scrollbox_height'                                   => '400',
		'comments_show_hide_method'                                   => 'text',
		'contact_btm_border'                                          => 'off',
		'contact_error_bg_color'                                      => '#B23323',
		'contact_error_text_color'                                    => '#000000',
		'contact_success_bg_color'                                    => '#2FA53F',
		'contact_success_text_color'                                  => '#000000',
		'content_margin'                                              => '0',
		'custom_font_1'                                               => '{"slug":"alice-regular","name":"AliceRegular"}',
		'dateformat'                                                  => 'm.d.y',
		'drawer_default_bg_color'                                     => '#29ABE2',
		'drawer_default_opacity'                                      => '100',
		'drawer_tab_font_color'                                       => '#000000',
		'drawer_tab_font_family'                                      => 'AliceRegular, Arial, Helvetica, sans-serif',
		'drawer_widget_headlines_font_color'                          => '#000000',
		'drawer_widget_headlines_font_family'                         => 'AliceRegular, Arial, Helvetica, sans-serif',
		'drawer_widget_headlines_font_size'                           => '17',
		'drawer_widget_text_font_family'                              => 'Times, Georgia, serif',
		'drawer_widget_text_font_size'                                => '13',
		'excerpt_style'                                               => 'grid',
		'featured_galleries_converted'                                => 'true',
		'footer_bg_color'                                             => '#c9dacd',
		'footer_bg_color_bind'                                        => '',
		'footer_font_color'                                           => '#000000',
		'footer_font_color_bind'                                      => 'on',
		'footer_headings_font_color'                                  => '#000000',
		'footer_headings_font_family'                                 => 'AliceRegular, Arial, Helvetica, sans-serif',
		'footer_headings_text_transform'                              => 'none',
		'footer_include'                                              => 'no',
		'footer_link_decoration'                                      => 'none',
		'footer_link_font_color'                                      => '#000000',
		'footer_link_font_color_bind'                                 => 'on',
		'footer_link_font_family'                                     => 'Times, Georgia, serif',
		'footer_link_hover_decoration'                                => 'none',
		'footer_link_hover_font_color'                                => '#29ABE2',
		'footer_link_hover_font_color_bind'                           => 'on',
		'gen_font_color'                                              => '#000000',
		'gen_font_family'                                             => 'Times, Georgia, serif',
		'gen_line_height'                                             => '1.75',
		'gen_link_font_color'                                         => '#29ABE2',
		'gen_link_font_color_bind'                                    => 'on',
		'gen_link_hover_decoration'                                   => '',
		'grid_img_text_below_gutter'                                  => '15',
		'grid_img_text_below_title_link_font_color'                   => '#000000',
		'grid_img_text_below_title_link_font_color_bind'              => 'on',
		'grid_img_text_below_title_link_font_family'                  => 'AliceRegular, Arial, Helvetica, sans-serif',
		'grid_img_text_below_title_link_font_size'                    => '13',
		'grid_img_text_below_title_link_font_style'                   => 'normal',
		'grid_img_text_below_title_link_font_weight'                  => '400',
		'grid_img_text_below_title_link_hover_decoration'             => 'none',
		'grid_img_text_below_title_link_hover_font_color'             => '#29ABE2',
		'grid_img_text_below_title_link_hover_font_color_bind'        => 'on',
		'grid_img_text_below_title_link_text_transform'               => 'none',
		'header_bg_color'                                             => '#1e1e1e',
		'header_font_color'                                           => '#29ABE2',
		'header_font_family'                                          => 'AliceRegular, Arial, Helvetica, sans-serif',
		'header_font_style'                                           => 'normal',
		'header_letterspacing'                                        => 'normal',
		'header_text_transform'                                       => 'uppercase',
		'headerlayout'                                                => 'pptclassic',
		'masthead_display'                                            => 'off',
		'masthead_slideshow_bg_color'                                 => '#fdfdfc',
		'masthead_slideshow_bg_color_bind'                            => '',
		'mobile_article_excerpt_text_font_family'                     => 'Times, Georgia, serif',
		'mobile_article_excerpt_title_font_family'                    => 'Times, Georgia, serif',
		'mobile_article_meta_below_title_link_font_family'            => 'Times, Georgia, serif',
		'mobile_article_text_link_font_family'                        => 'Times, Georgia, serif',
		'mobile_article_title_font_color'                             => '#29ABE2',
		'mobile_article_title_font_color_bind'                        => 'on',
		'mobile_article_title_font_family'                            => 'Times, Georgia, serif',
		'mobile_article_title_font_size'                              => '17',
		'mobile_article_title_text_transform'                         => 'uppercase',
		'mobile_button_bg_color'                                      => '#29ABE2',
		'mobile_button_border_color'                                  => '#29ABE2',
		'mobile_button_font_color'                                    => '#000000',
		'mobile_button_font_family'                                   => 'Times, Georgia, serif',
		'mobile_button_text_transform'                                => 'lowercase',
		'mobile_comments_area_link_font_family'                       => 'Times, Georgia, serif',
		'mobile_content_bg_img_position'                              => 'top left',
		'mobile_content_bg_img_repeat'                                => 'repeat',
		'mobile_excerpt_list_border_color'                            => '#000000',
		'mobile_excerpt_list_border_width'                            => '0',
		'mobile_font_color'                                           => '#000000',
		'mobile_font_family'                                          => 'Times, Georgia, serif',
		'mobile_footer_color_scheme'                                  => 'white',
		'mobile_headline_font_color'                                  => '#29ABE2',
		'mobile_headline_font_family'                                 => 'Times, Georgia, serif',
		'mobile_headline_font_weight'                                 => '400',
		'mobile_link_font_color'                                      => '#29ABE2',
		'mobile_logo_use_desktop'                                     => 'false',
		'mobile_masthead_display'                                     => 'off',
		'mobile_masthead_use_desktop_settings'                        => 'false',
		'mobile_nav_menu_item_6'                                      => '{"text":"Home","type":"internal","iconNotConstrained":true,"internalType":"home","pageID":"","categoryName":"","numRecentPosts":"","galleryID":"","galleryDisplay":"","specialType":"email","email":"","twitterID":"","numTweets":"8","searchBtnText":"Search","subscribeByEmailPrefill":"Enter email","subscribeByEmailBtnText":"Subscribe by email","customHTML":"","url":"","target":"","anchor":"text","iconAlign":"left","titleAttr":"","customClasses":"","menu_item_id":"mobile_nav_menu_item_6","excludedPageIDs":""}',
		'mobile_nav_menu_structure'                                   => '{"mobile_nav_menu_item_6":"mobile_nav_menu_item_6", "mobile_nav_menu_item_2":"mobile_nav_menu_item_2", "mobile_nav_menu_item_3":"mobile_nav_menu_item_3", "mobile_nav_menu_item_4":"mobile_nav_menu_item_4", "mobile_nav_menu_item_1":"mobile_nav_menu_item_1"}',
		'nav_below_link_font_color'                                   => '#29ABE2',
		'nav_below_link_font_color_bind'                              => 'on',
		'nav_below_link_font_family'                                  => 'AliceRegular, Arial, Helvetica, sans-serif',
		'nav_below_link_font_size'                                    => '17',
		'nav_below_link_hover_decoration'                             => 'none',
		'nav_below_link_hover_font_color'                             => '#000000',
		'nav_below_link_hover_font_color_bind'                        => 'on',
		'override_css'                                                => '/* custom CSS for \"Mercury\" starter design */
#sidebar { text-align: right; }
/* end custom CSS for \"Mercury\" starter design */
',
		'pagination_next_text'                                        => 'Next »',
		'pagination_prev_text'                                        => '« Prev',
		'post_divider'                                                => 'none',
		'post_footer_meta_font_color'                                 => '#000000',
		'post_footer_meta_font_color_bind'                            => 'on',
		'post_footer_meta_link_decoration'                            => 'none',
		'post_footer_meta_link_font_color'                            => '#000000',
		'post_footer_meta_link_font_color_bind'                       => 'on',
		'post_footer_meta_link_font_family'                           => 'Times, Georgia, serif',
		'post_footer_meta_link_font_size'                             => '13',
		'post_footer_meta_link_hover_decoration'                      => 'none',
		'post_footer_meta_link_hover_font_color'                      => '#29ABE2',
		'post_footer_meta_link_hover_font_color_bind'                 => 'on',
		'post_header_border'                                          => 'image',
		'post_header_margin_below'                                    => '14',
		'post_header_postdate_font_color'                             => '#000000',
		'post_header_postdate_font_color_bind'                        => 'on',
		'post_header_postdate_font_family'                            => 'AliceRegular, Arial, Helvetica, sans-serif',
		'post_header_postdate_font_size'                              => '27',
		'post_header_postdate_letterspacing'                          => '1px',
		'post_header_postdate_margin_bottom'                          => '15',
		'post_header_postdate_text_transform'                         => 'uppercase',
		'post_pic_border_color'                                       => '#ffffff',
		'post_pic_border_width'                                       => '6',
		'post_pic_margin_bottom'                                      => '9',
		'post_pic_margin_top'                                         => '9',
		'post_pic_shadow_blur'                                        => '2',
		'post_pic_shadow_enable'                                      => 'true',
		'post_pic_shadow_horizontal_offset'                           => '0',
		'post_pic_shadow_vertical_offset'                             => '0',
		'post_title_link_font_family'                                 => 'AliceRegular, Arial, Helvetica, sans-serif',
		'post_title_link_font_size'                                   => '27',
		'post_title_link_hover_decoration'                            => 'none',
		'post_title_link_letterspacing'                               => '1px',
		'postdate_bg_color'                                           => '#a8ab9b',
		'postdate_bg_color_bind'                                      => 'on',
		'postdate_border_bottom'                                      => 'on',
		'postdate_border_color'                                       => '#ffffff',
		'postdate_border_style'                                       => 'double',
		'postdate_border_top'                                         => 'on',
		'postdate_border_width'                                       => '3',
		'postdate_lr_padding'                                         => '18',
		'postdate_placement'                                          => 'withtitle',
		'postdate_tb_padding'                                         => '4',
		'primary_nav_menu_bg_color'                                   => '#88b2ab',
		'primary_nav_menu_border_top_onoff'                           => 'on',
		'primary_nav_menu_dropdown_bg_color'                          => '#88b2ab',
		'primary_nav_menu_dropdown_bg_hover_color'                    => '#88b2ab',
		'primary_nav_menu_dropdown_bg_hover_color_bind'               => 'on',
		'primary_nav_menu_link_font_color'                            => '#000000',
		'primary_nav_menu_link_font_family'                           => 'Georgia, Times, serif',
		'primary_nav_menu_link_font_size'                             => '13',
		'primary_nav_menu_link_letterspacing'                         => 'normal',
		'primary_nav_menu_link_spacing_between'                       => '35',
		'primary_nav_menu_link_text_transform'                        => 'uppercase',
		'primary_nav_menu_structure'                                  => '{}',
		'primary_nav_menu_top_border_color'                           => '#000000',
		'primary_nav_menu_top_border_width'                           => '6',
		'sidebar_border_switch'                                       => 'off',
		'sidebar_headlines_font_family'                               => 'AliceRegular, Arial, Helvetica, sans-serif',
		'sidebar_headlines_font_size'                                 => '16',
		'sidebar_headlines_margin_bottom'                             => '10',
		'sidebar_headlines_text_transform'                            => 'none',
		'sidebar_inner_padding_override'                              => '30',
		'sidebar_link_font_color'                                     => '#000000',
		'sidebar_link_font_color_bind'                                => 'on',
		'sidebar_link_hover_decoration'                               => 'none',
		'sidebar_link_hover_font_color'                               => '#29ABE2',
		'sidebar_link_hover_font_color_bind'                          => 'on',
		'sidebar_padding'                                             => '0',
		'sidebar_widget_margin_bottom'                                => '22',
		'sidebar_width'                                               => '225',
		'slideshow_controls_overlaid'                                 => 'false',
		'slideshow_subtitle_font_family'                              => 'Times, Georgia, serif',
		'slideshow_title_font_family'                                 => 'AliceRegular, Arial, Helvetica, sans-serif',
		'tags_in_post_footer'                                         => 'yes',
		'tags_in_post_header'                                         => '',
		'widget_menu_1_item_1'                                        => '{"text":"home","type":"internal","iconNotConstrained":true,"internalType":"home","pageID":"","categoryName":"","archivesNestThreshold":"","numRecentPosts":"","galleryID":"","galleryDisplay":"","specialType":"email","email":"","twitterID":"","numTweets":"8","searchBtnText":"Search","subscribeByEmailPrefill":"Enter email","subscribeByEmailBtnText":"Subscribe by email","customHTML":"","url":"","target":"","anchor":"text","iconAlign":"left","titleAttr":"","customClasses":"","menu_item_id":"widget_menu_1_item_1","excludedPageIDs":""}',
		'widget_menu_1_item_2'                                        => '{"text":"about","type":"container","iconNotConstrained":true,"internalType":"page","pageID":"","categoryName":"","archivesNestThreshold":"","numRecentPosts":"","galleryID":"","galleryDisplay":"","specialType":"email","email":"","twitterID":"","numTweets":"8","searchBtnText":"Search","subscribeByEmailPrefill":"Enter email","subscribeByEmailBtnText":"Subscribe by email","customHTML":"","url":"http:\/\/#","target":"","anchor":"text","iconAlign":"left","titleAttr":"","customClasses":"","menu_item_id":"widget_menu_1_item_2","excludedPageIDs":""}',
		'widget_menu_1_item_3'                                        => '{"text":"galleries","type":"manual","iconNotConstrained":true,"internalType":"page","pageID":"","categoryName":"","archivesNestThreshold":"","numRecentPosts":"","galleryID":"","galleryDisplay":"","specialType":"email","email":"","twitterID":"","numTweets":"8","searchBtnText":"Search","subscribeByEmailPrefill":"Enter email","subscribeByEmailBtnText":"Subscribe by email","customHTML":"","url":"","target":"","anchor":"text","iconAlign":"left","titleAttr":"","customClasses":"","menu_item_id":"widget_menu_1_item_3","excludedPageIDs":""}',
		'widget_menu_1_item_4'                                        => '{"text":"info","type":"manual","iconNotConstrained":true,"internalType":"page","pageID":"","categoryName":"","archivesNestThreshold":"","numRecentPosts":"","galleryID":"","galleryDisplay":"","specialType":"email","email":"","twitterID":"","numTweets":"8","searchBtnText":"Search","subscribeByEmailPrefill":"Enter email","subscribeByEmailBtnText":"Subscribe by email","customHTML":"","url":"http:\/\/#","target":"","anchor":"text","iconAlign":"left","titleAttr":"","customClasses":"","menu_item_id":"widget_menu_1_item_4","excludedPageIDs":""}',
		'widget_menu_1_item_6'                                        => '{"text":"contact","type":"special","iconNotConstrained":true,"internalType":"page","pageID":"","categoryName":"","archivesNestThreshold":"","numRecentPosts":"","galleryID":"","galleryDisplay":"","specialType":"show_contact_form","email":"","twitterID":"","numTweets":"8","searchBtnText":"Search","subscribeByEmailPrefill":"Enter email","subscribeByEmailBtnText":"Subscribe by email","customHTML":"","url":"","target":"","anchor":"text","iconAlign":"left","titleAttr":"","customClasses":"","menu_item_id":"widget_menu_1_item_6","excludedPageIDs":""}',
		'widget_menu_1_li_font_color'                                 => '#29ABE2',
		'widget_menu_1_li_font_color_bind'                            => 'on',
		'widget_menu_1_li_link_decoration'                            => 'none',
		'widget_menu_1_li_link_font_color'                            => '#29ABE2',
		'widget_menu_1_li_link_font_color_bind'                       => 'on',
		'widget_menu_1_li_link_font_family'                           => 'AliceRegular, Arial, Helvetica, sans-serif',
		'widget_menu_1_li_link_font_size'                             => '18',
		'widget_menu_1_li_link_hover_decoration'                      => 'none',
		'widget_menu_1_li_link_hover_font_color'                      => '#000000',
		'widget_menu_1_li_link_hover_font_color_bind'                 => 'on',
		'widget_menu_1_li_list_style'                                 => 'none',
		'widget_menu_1_li_margin_btm'                                 => '20',
		'widget_menu_1_structure'                                     => '{"widget_menu_1_item_1":"widget_menu_1_item_1", "widget_menu_1_item_3":"widget_menu_1_item_3", "widget_menu_1_item_2":"widget_menu_1_item_2", "widget_menu_1_item_4":"widget_menu_1_item_4", "widget_menu_1_item_6":"widget_menu_1_item_6"}',
		'widget_menu_1_sub_li_list_style'                             => 'none',
		'widget_menu_1_sub_sub_li_list_style'                         => 'none',
	),

	'activation_widgets' => array(


		'fixed-sidebar' => array(
			'1' => array(
				'pp-custom-icon' => array(
					'number' => '1',
					'link' => 'http://www.facebook.com/pages/Prophoto-Blogs/110888486694',
					'target' => '_blank',
					'title' => '',
					'note' => '',
				),

			),

			'2' => array(
				'pp-vertical-nav-menu' => array(
					'title' => '',
					'widget_menu_num' => '1',
				),

			),

			'3' => array(
				'pp-text' => array(
					'title' => 'Welcome to Mercury',
					'text' => 'With touch of retro funk and a masculine, modern twist, Mercury is perfect for those photogs looking for just a bit of edge. Mercury uses a simple, clean layout easy for your clients to navigate while grabbing their attention with design elements that really pop.',
					'wpautop' => '1',
				),

			),

		),

	),

	'imgs' => array(
		'blog_bg'                      => 'mercury_blog_bg.jpg',
		'blog_bg_inner'                => 'mercury_blog_bg_inner.png',
		'call_to_action_1'             => 'mercury_call_to_action_1.png',
		'call_to_action_2'             => 'mercury_call_to_action_2.png',
		'call_to_action_3'             => 'mercury_call_to_action_3.png',
		'call_to_action_4'             => 'mercury_call_to_action_4.png',
		'call_to_action_5'             => 'mercury_call_to_action_5.png',
		'grid_article_img_fallback'    => 'mercury_grid_article_img_fallback.png',
		'mobile_content_bg'            => 'mercury_mobile_content_bg.jpg',
		'mobile_logo'                  => 'mercury_mobile_logo.png',
		'sidebar_widget_sep_img'       => 'mercury_sidebar_widget_sep_img.png',
		'slideshow_splash_screen_logo' => 'mercury_slideshow_splash_screen_logo.png',
		'widget_custom_image_1'        => 'mercury_widget_custom_image_1.png',
		'widget_custom_image_2'        => 'mercury_widget_custom_image_2.png',
		'widget_custom_image_3'        => 'mercury_widget_custom_image_3.png',
		'widget_custom_image_4'        => 'mercury_widget_custom_image_4.png',
		'widget_custom_image_5'        => 'mercury_widget_custom_image_5.png',
	),

	'remote_files' => array(

		'alice-regular-webfont.eot' => array(
			'hash' => '152efe8cf2ce4088e2db13aee2ca712f',
		),

		'alice-regular-webfont.svg' => array(
			'hash' => '77dc551eda918d7db2c4f514ebb836b6',
		),

		'alice-regular-webfont.ttf' => array(
			'hash' => '3a51bf4f93a9307979644c83c3453930',
		),

		'alice-regular-webfont.woff' => array(
			'hash' => '103d22649fd4b9c5061c562e7a23fba6',
		),

		'mercury_blog_bg.jpg' => array(
			'hash'   => '9e08e12814426fd4816f8a7dc25bfebb',
			'width'  => '200',
			'height' => '307',
			'size'   => '3',
		),

		'mercury_blog_bg_inner.png' => array(
			'hash'   => '980f42e971d87341e06c774f471ae4e8',
			'width'  => '11',
			'height' => '30',
			'size'   => '1',
		),

		'mercury_call_to_action_1.png' => array(
			'hash'   => 'cb12efed2c6bd373c8111e13fa0f1f9f',
			'width'  => '130',
			'height' => '50',
			'size'   => '2',
		),

		'mercury_call_to_action_2.png' => array(
			'hash'   => '91464975e19b79bea7ea465cf2863b91',
			'width'  => '130',
			'height' => '50',
			'size'   => '1',
		),

		'mercury_call_to_action_3.png' => array(
			'hash'   => 'da40d5f95b37dd241c14a04e951504e8',
			'width'  => '130',
			'height' => '50',
			'size'   => '2',
		),

		'mercury_call_to_action_4.png' => array(
			'hash'   => 'd9723dc02e9e62183c76a2a689285c83',
			'width'  => '130',
			'height' => '50',
			'size'   => '1',
		),

		'mercury_call_to_action_5.png' => array(
			'hash'   => 'baf1b0e31083ddf3f9c8513b4a5caa34',
			'width'  => '130',
			'height' => '50',
			'size'   => '1',
		),

		'mercury_grid_article_img_fallback.png' => array(
			'hash'   => 'ba0160d10dca804ace71543f3014f94d',
			'width'  => '258',
			'height' => '243',
			'size'   => '13',
		),

		'mercury_mobile_content_bg.jpg' => array(
			'hash'   => '9e08e12814426fd4816f8a7dc25bfebb',
			'width'  => '200',
			'height' => '307',
			'size'   => '3',
		),

		'mercury_mobile_logo.png' => array(
			'hash'   => '0e03bc84ec99d57676f065eb5ed10caa',
			'width'  => '990',
			'height' => '402',
			'size'   => '36',
		),

		'mercury_sidebar_widget_sep_img.png' => array(
			'hash'   => '9c69e499066e3f06cb7ba921bd8889aa',
			'width'  => '258',
			'height' => '20',
			'size'   => '1',
		),

		'mercury_slideshow_splash_screen_logo.png' => array(
			'hash'   => '5085699ba1e076c553bab5a9d6d0aa3f',
			'width'  => '145',
			'height' => '125',
			'size'   => '3',
		),

		'mercury_widget_custom_image_1.png' => array(
			'hash'   => 'ba0160d10dca804ace71543f3014f94d',
			'width'  => '258',
			'height' => '243',
			'size'   => '13',
		),

		'mercury_widget_custom_image_2.png' => array(
			'hash'   => '33e085852346a370d51fd33f5c9df0b8',
			'width'  => '40',
			'height' => '40',
			'size'   => '1',
		),

		'mercury_widget_custom_image_3.png' => array(
			'hash'   => '2de3e16052809ae1bfaef2de7e9c5b44',
			'width'  => '40',
			'height' => '40',
			'size'   => '1',
		),

		'mercury_widget_custom_image_4.png' => array(
			'hash'   => '0bdec5e84ced8cccb255f644ce037847',
			'width'  => '40',
			'height' => '40',
			'size'   => '1',
		),

		'mercury_widget_custom_image_5.png' => array(
			'hash'   => '6f187f86e2fe44082eaa5d92dbac8355',
			'width'  => '40',
			'height' => '40',
			'size'   => '1',
		),
	),

);


