<?php

$configArray = array(

	'meta' => array(
		'name' => 'Minimalist',
		'desc' => 'Want a simple framework without distraction?  This is the template for you.  Grey and pale blue tones with a san serif font keep things subdued.  Easy navigation and clean lines assure that your photos are the main attraction.  Perfect for displaying sophisticated images.',
	),

	'options' => array(
		'primary_nav_menu_edge_padding'                                 => '0',
		'blog_border'                                                   => 'none',
		'blog_border_color'                                             => '#ffffff',
		'blog_top_margin'                                               => '20',
		'blog_width'                                                    => '760',
		'blog_bg_color'                                                 => '#ffffff',
		'headerlayout'                                                  => 'pptclassic',
		'masthead_top_border_color'                                     => '#000000',
		'masthead_top_border_style'                                     => 'solid',
		'masthead_btm_border_color'                                     => '#000000',
		'masthead_btm_border_style'                                     => 'solid',
		'masthead_display'                                              => 'off',
		'gen_font_size'                                                 => '12',
		'gen_font_weight'                                               => '400',
		'gen_font_style'                                                => 'normal',
		'gen_text_transform'                                            => 'none',
		'gen_line_height'                                               => '1.25',
		'gen_font_color'                                                => '#999999',
		'gen_link_text_transform'                                       => 'uppercase',
		'gen_link_decoration'                                           => 'underline',
		'gen_link_font_color_bind'                                      => 'on',
		'gen_link_hover_font_color_bind'                                => 'on',
		'gen_link_visited_font_color_bind'                              => 'on',
		'header_font_size'                                              => '12',
		'header_font_family'                                            => 'Arial, Helvetica, sans-serif',
		'header_font_weight'                                            => '400',
		'header_font_style'                                             => 'normal',
		'header_text_transform'                                         => 'uppercase',
		'header_font_color'                                             => '#388eb2',
		'primary_nav_menu_link_font_weight'                             => '400',
		'primary_nav_menu_link_text_transform'                          => 'uppercase',
		'primary_nav_menu_link_font_color'                              => '#999999',
		'primary_nav_menu_link_hover_decoration'                        => 'none',
		'primary_nav_menu_link_hover_font_color_bind'                   => 'on',
		'primary_nav_menu_link_visited_font_color_bind'                 => 'on',
		'primary_nav_menu_dropdown_link_font_color_bind'                => 'on',
		'primary_nav_menu_dropdown_link_hover_font_color_bind'          => 'on',
		'primary_nav_menu_link_font_size'                               => '10',
		'primary_nav_menu_dropdown_link_textsize'                       => '10',
		'primary_nav_menu_dropdown_bg_color_bind'                       => 'on',
		'primary_nav_menu_dropdown_opacity'                             => '100',
		'primary_nav_menu_top_border_color'                             => '#000000',
		'primary_nav_menu_top_border_style'                             => 'solid',
		'primary_nav_menu_btm_border_color'                             => '#000000',
		'primary_nav_menu_btm_border_style'                             => 'solid',
		'primary_nav_menu_link_hover_font_color'                        => '#006C99',
		'primary_nav_menu_link_visited_font_color'                      => '#999999',
		'primary_nav_menu_dropdown_link_font_color'                     => '#999999',
		'primary_nav_menu_dropdown_link_hover_font_color'               => '#006C99',
		'bio_include'                                                   => 'no',
		'bio_top_padding'                                               => '2',
		'bio_btm_padding'                                               => '2',
		'bio_widget_margin_btm'                                         => '10',
		'bio_header_font_size'                                          => '12',
		'bio_para_font_size'                                            => '12',
		'bio_bg'                                                        => 'color',
		'bio_bg_color'                                                  => '#ffffff',
		'bio_border'                                                    => 'noborder',
		'post_header_margin_above'                                      => '10',
		'post_header_margin_below'                                      => '5',
		'postdate_placement'                                            => 'withtitle',
		'dateformat'                                                    => 'm-d-Y',
		'post_title_link_font_size'                                     => '12',
		'post_title_link_font_weight'                                   => '700',
		'post_header_meta_link_font_size'                               => '12',
		'post_header_meta_link_hover_decoration'                        => 'none',
		'post_header_postdate_font_size'                                => '12',
		'post_header_postdate_font_color_bind'                          => 'on',
		'postdate_border_color'                                         => '#000000',
		'postdate_border_style'                                         => 'solid',
		'post_pic_margin_bottom'                                        => '2',
		'post_pic_border_color'                                         => '#000000',
		'post_divider'                                                  => 'none',
		'comments_layout'                                               => 'minima',
		'comments_area_border_style'                                    => 'solid',
		'comments_header_show_article_author'                           => 'false',
		'comments_header_link_font_size'                                => '11',
		'comments_header_link_font_family'                              => 'Arial, Helvetica, sans-serif',
		'comments_header_link_font_weight'                              => '400',
		'comments_header_link_font_style'                               => 'normal',
		'comments_header_link_text_transform'                           => 'uppercase',
		'comments_header_link_decoration'                               => 'none',
		'comments_header_font_color_bind'                               => 'on',
		'comments_header_link_font_color_bind'                          => 'on',
		'comments_header_link_hover_font_color_bind'                    => 'on',
		'comments_header_post_interaction_link_font_weight'             => '400',
		'comments_header_post_interaction_link_font_style'              => 'normal',
		'comments_header_post_interaction_link_text_transform'          => 'uppercase',
		'comments_header_post_interaction_link_decoration'              => 'none',
		'comments_header_post_interaction_link_font_color_bind'         => 'on',
		'comments_header_post_interaction_link_hover_decoration'        => 'underline',
		'comments_header_post_interaction_link_hover_font_color_bind'   => 'on',
		'comments_header_post_interaction_link_visited_font_color_bind' => 'on',
		'comments_show_hide_method'                                     => 'text',
		'comments_header_linktothispost_link_include'                   => 'no',
		'comments_header_emailafriend_link_include'                     => 'no',
		'comments_header_emailafriend_link_subject'                     => pp::site()->name,
		'comment_meta_position'                                         => 'inline',
		'comment_timestamp_display'                                     => 'off',
		'comment_timestamp_font_color'                                  => '#000000',
		'sidebar_border_color'                                          => '#cccccc',
		'footer_include'                                                => 'no',
		'footer_bg_color'                                               => '#fffffff',
		'footer_headings_font_size'                                     => '12',
		'footer_headings_font_color'                                    => '#999999',
		'footer_link_font_size'                                         => '11',
		'slideshow_bg_color'                                            => '#ffffff',
		'slideshow_splash_screen_color_bind'                            => 'on',
		'slideshow_splash_screen_color'                                 => '#ffffff',
		'slideshow_title_font_size'                                     => '16',
		'slideshow_title_font_family'                                   => 'Arial, Helvetica, sans-serif',
		'slideshow_title_font_color'                                    => '#388eb2',
		'slideshow_btns_color'                                          => '#388eb2',
		'slideshow_subtitle_font_size'                                  => '12',
		'slideshow_start_playing'                                       => 'false',
		'lightbox_bg_color'                                             => '#999999',
		'lightbox_font_color'                                           => '#999999',
		'lightbox_overlay_color'                                        => '#ffffff',
		'primary_nav_menu_dropdown_bg_color'                            => '#ffffff',
		'gen_link_font_color'                                           => '#999999',
		'gen_link_hover_font_color'                                     => '#388eb2',
		'gen_link_visited_font_color'                                   => '#999999',
		'comments_header_font_color'                                    => '#999999',
		'comments_header_link_font_color'                               => '#006C99',
		'comments_header_link_hover_font_color'                         => '#006C99',
		'comments_header_post_interaction_link_font_color'              => '#006C99',
		'comments_header_post_interaction_link_hover_font_color'        => '#006C99',
		'comments_header_post_interaction_link_visited_font_color'      => '#006C99',
		'post_bg_img_repeat'                                            => 'repeat',
		'post_bg_img_position'                                          => 'top left',
		'post_header_meta_font_color'                                   => '#666',
		'post_header_postdate_font_color'                               => '#9dbfcd',
		'content_margin'                                                => '0',
		'categories_in_post_header'                                     => '',
		'menu_btm_splitter'                                             => '17',
		'comments_header_bg_img_repeat'                                 => 'repeat',
		'comments_header_bg_img_position'                               => 'top left',
		'comment_author_link_font_color_bind'                           => 'on',
		'comment_tb_padding'                                            => '4',
		'comments_body_area_lr_margin'                                  => '5',
		'comments_body_area_tb_margin'                                  => '10',
		'comment_bottom_border_onoff'                                   => 'on',
		'comment_author_link_font_color'                                => '#9dbfcd',
		'comment_alt_bg_color_bind'                                     => '',
		'comment_tb_margin'                                             => '0',
		'comment_lr_padding'                                            => '0',
		'comments_header_tb_padding'                                    => '4',
		'comments_area_border_width'                                    => '0',
		'primary_nav_menu_bg_color_bind'                                => '',
	),


	'activation_widgets' => array(
		'fixed-sidebar' => 'empty',
	),


	'imgs' => array(
		'logo' => 'minimalist_logo.gif',
	),


	'remote_files' => array(

		'minimalist_logo.gif' => array(
			'hash'   => '0a01d67c6aa2c895fb3adeba707fd70d',
			'width'  => '180',
			'height' => '25',
			'size'   => '1',
		),

	),

);

