<?php

$configArray = array(

	'meta' => array(
		'name' => 'Late August',
		'desc' => 'The subtle grey pin striped background of Late August provides a perfect setting for your work.  Quiet tones and calligraphy scrolls add an element of class to this template design from <a href="http://www.swoone.com">Swoone</a>, while the rounded corners and casual script keeps things low-key.',
	),

	'options' => array(
		'archive_h2_font_color'                                       => '#808080',
		'archive_h2_font_family'                                      => 'DroidSansRegular, \"Lucida Grande\", \"Lucida Sans Unicode\", Tahoma, Verdana, sans-serif',
		'archive_h2_font_size'                                        => '16',
		'archive_h2_font_weight'                                      => '400',
		'archive_h2_text_transform'                                   => 'uppercase',
		'bio_bg'                                                      => 'color',
		'bio_bg_color'                                                => '#ffffff',
		'bio_bg_color_bind'                                           => '',
		'bio_bg_img_position'                                         => 'top center',
		'bio_bg_img_repeat'                                           => 'repeat-y',
		'bio_border'                                                  => 'image',
		'bio_border_color'                                            => '#cccccc',
		'bio_btm_padding'                                             => '0',
		'bio_gutter_width'                                            => '15',
		'bio_header_font_color'                                       => '#AEACBC',
		'bio_header_font_color_bind'                                  => 'on',
		'bio_header_font_size'                                        => '28',
		'bio_header_font_style'                                       => 'italic',
		'bio_header_font_weight'                                      => '400',
		'bio_header_text_transform'                                   => 'none',
		'bio_inner_bg_img_position'                                   => 'top center',
		'bio_inner_bg_img_repeat'                                     => 'repeat-y',
		'bio_lr_padding'                                              => '50',
		'bio_top_padding'                                             => '0',
		'bio_widget_margin_btm'                                       => '10',
		'biopic_border'                                               => 'off',
		'biopic_border_color'                                         => '#1e1e1e',
		'biopic_display'                                              => 'off',
		'blog_bg_color'                                               => '#ffffff',
		'blog_bg_color_bind'                                          => '',
		'blog_bg_img_position'                                        => 'top center',
		'blog_bg_secondary_img_position'                              => 'top left',
		'blog_bg_secondary_img_repeat'                                => 'repeat',
		'blog_border'                                                 => 'none',
		'blog_btm_margin'                                             => '16',
		'blog_width'                                                  => '980',
		'body_bg_color'                                               => '#fdfdfc',
		'body_bg_color_bind'                                          => '',
		'boxy_date_bg_color_bind'                                     => 'on',
		'call_to_action_1'                                            => 'back_to_top',
		'call_to_action_2'                                            => 'show_contact_form',
		'call_to_action_3'                                            => 'share_on_facebook',
		'call_to_action_4'                                            => 'tweet_this_url',
		'call_to_action_5'                                            => 'email_this_url',
		'call_to_action_enable'                                       => 'true',
		'call_to_action_font_color'                                   => '#AEACBC',
		'call_to_action_font_color_bind'                              => 'on',
		'call_to_action_link_font_color'                              => '#AEACBC',
		'call_to_action_link_font_color_bind'                         => 'on',
		'call_to_action_link_font_family'                             => 'DroidSansRegular, \"Lucida Grande\", \"Lucida Sans Unicode\", Tahoma, Verdana, sans-serif',
		'call_to_action_link_font_size'                               => '13',
		'call_to_action_link_font_weight'                             => '400',
		'call_to_action_link_hover_font_color'                        => '#808080',
		'call_to_action_link_hover_font_color_bind'                   => 'on',
		'call_to_action_link_text_transform'                          => 'uppercase',
		'call_to_action_link_visited_font_color'                      => '#000000',
		'call_to_action_separator'                                    => 'image',
		'call_to_action_separator_text'                               => '•',
		'call_to_action_text_1'                                       => 'Back to Top',
		'call_to_action_text_2'                                       => 'Contact Me',
		'call_to_action_text_3'                                       => 'Share on Facebook',
		'call_to_action_text_4'                                       => 'Tweet this Post',
		'call_to_action_text_5'                                       => 'Email to a Friend',
		'comment_alt_bg_color_bind'                                   => '',
		'comment_author_link_font_color'                              => '#808080',
		'comment_author_link_font_color_bind'                         => 'on',
		'comment_author_link_font_weight'                             => '700',
		'comment_author_link_text_transform'                          => 'uppercase',
		'comment_bottom_border_color'                                 => '#ffffff',
		'comment_bottom_border_onoff'                                 => 'on',
		'comment_bottom_border_style'                                 => 'solid',
		'comment_count_in_post_header'                                => '',
		'comment_header_border_bottom'                                => '',
		'comment_header_border_top'                                   => '',
		'comment_lr_padding'                                          => '8',
		'comment_meta_margin_bottom'                                  => '5',
		'comment_tb_margin'                                           => '6',
		'comment_tb_padding'                                          => '10',
		'comment_timestamp_display'                                   => 'left',
		'comment_timestamp_font_color'                                => '#808080',
		'comment_timestamp_font_weight'                               => '400',
		'comment_timestamp_text_transform'                            => 'uppercase',
		'comments_addacomment_text'                                   => 'Comment',
		'comments_area_border_color'                                  => '#ffffff',
		'comments_area_border_width'                                  => '0',
		'comments_area_lr_margin'                                     => '75',
		'comments_body_area_bg_color'                                 => '#ffffff',
		'comments_body_area_bg_img_position'                          => 'top center',
		'comments_body_area_bg_img_repeat'                            => 'no-repeat',
		'comments_body_area_lr_margin'                                => '0',
		'comments_body_area_tb_margin'                                => '0',
		'comments_header_addacomment_link_text'                       => 'Make a Comment',
		'comments_header_bg_color'                                    => '#c9dacd',
		'comments_header_bg_img_position'                             => 'top center',
		'comments_header_bg_img_repeat'                               => 'no-repeat',
		'comments_header_emailafriend_link_include'                   => 'no',
		'comments_header_emailafriend_link_text'                      => 'Email',
		'comments_header_font_color'                                  => '#808080',
		'comments_header_font_color_bind'                             => 'on',
		'comments_header_link_font_color'                             => '#808080',
		'comments_header_link_font_color_bind'                        => 'on',
		'comments_header_link_font_family'                            => 'DroidSansRegular, \"Lucida Grande\", \"Lucida Sans Unicode\", Tahoma, Verdana, sans-serif',
		'comments_header_link_font_style'                             => 'normal',
		'comments_header_link_hover_decoration'                       => 'none',
		'comments_header_link_hover_font_color'                       => '#ffffff',
		'comments_header_link_hover_font_color_bind'                  => 'on',
		'comments_header_link_text_transform'                         => 'uppercase',
		'comments_header_linktothispost_link_include'                 => 'no',
		'comments_header_post_interact_link_spacing'                  => '25',
		'comments_header_post_interaction_link_font_color'            => '#808080',
		'comments_header_post_interaction_link_font_color_bind'       => 'on',
		'comments_header_post_interaction_link_font_family'           => 'DroidSansRegular, \"Lucida Grande\", \"Lucida Sans Unicode\", Tahoma, Verdana, sans-serif',
		'comments_header_post_interaction_link_font_size'             => '13',
		'comments_header_post_interaction_link_font_style'            => 'normal',
		'comments_header_post_interaction_link_hover_decoration'      => 'none',
		'comments_header_post_interaction_link_hover_font_color'      => '#ffffff',
		'comments_header_post_interaction_link_hover_font_color_bind' => 'on',
		'comments_header_post_interaction_link_text_transform'        => 'uppercase',
		'comments_header_show_article_author'                         => 'false',
		'comments_header_tb_padding'                                  => '20',
		'comments_layout'                                             => 'minima',
		'comments_linktothispost_text'                                => 'Link',
		'comments_minima_hide_text'                                   => 'Hide',
		'comments_minima_show_text'                                   => 'Show',
		'comments_scrollbox_height'                                   => '400',
		'comments_show_hide_method'                                   => 'text',
		'contact_bg_img_position'                                     => 'top center',
		'contact_bg_img_repeat'                                       => 'repeat-y',
		'contact_btm_border'                                          => 'off',
		'contact_error_bg_color'                                      => '#CEB6B4',
		'contact_error_text_color'                                    => '#808080',
		'contact_success_bg_color'                                    => '#CCCEB4',
		'contact_success_text_color'                                  => '#808080',
		'content_margin'                                              => '60',
		'custom_font_1'                                               => '{"slug":"DroidSans","name":"DroidSansRegular"}',
		'custom_font_1_fallback'                                      => '\"Lucida Grande\", \"Lucida Sans Unicode\", Tahoma, Verdana, sans-serif',
		'custom_font_2'                                               => '{"slug":"LobsterTwo-Regular","name":"LobsterTwoRegular"}',
		'custom_font_2_fallback'                                      => '\"Lucida Grande\", \"Lucida Sans Unicode\", Tahoma, Verdana, sans-serif',
		'dateformat'                                                  => 'F j, Y',
		'drawer_default_bg_color'                                     => '#ECEBEF',
		'drawer_default_opacity'                                      => '100',
		'drawer_tab_font_color'                                       => '#808080',
		'drawer_tab_font_family'                                      => 'DroidSansRegular, \"Lucida Grande\", \"Lucida Sans Unicode\", Tahoma, Verdana, sans-serif',
		'drawer_widget_headlines_font_color'                          => '#808080',
		'drawer_widget_headlines_font_family'                         => 'LobsterTwoRegular, \"Lucida Grande\", \"Lucida Sans Unicode\", Tahoma, Verdana, sans-serif',
		'drawer_widget_text_font_color'                               => '#808080',
		'drawer_widget_text_font_color_bind'                          => 'on',
		'drawer_widget_text_font_family'                              => 'Arial, Helvetica, sans-serif',
		'excerpt_grid_cols'                                           => '4',
		'excerpt_grid_rows'                                           => '5',
		'excerpt_style'                                               => 'grid',
		'featured_galleries_converted'                                => 'true',
		'footer_bg_color'                                             => '#c9dacd',
		'footer_bg_color_bind'                                        => '',
		'footer_bg_img_position'                                      => 'top center',
		'footer_bg_img_repeat'                                        => 'repeat-y',
		'footer_btm_cap_img_position'                                 => 'bottom left',
		'footer_btm_cap_img_repeat'                                   => 'no-repeat',
		'footer_font_color'                                           => '#808080',
		'footer_font_color_bind'                                      => 'on',
		'footer_headings_font_color'                                  => '#808080',
		'footer_headings_font_family'                                 => '',
		'footer_headings_font_size'                                   => '18',
		'footer_headings_font_style'                                  => 'italic',
		'footer_headings_text_transform'                              => 'none',
		'footer_link_font_color'                                      => '#AEACBC',
		'footer_link_font_color_bind'                                 => 'on',
		'footer_link_hover_decoration'                                => 'none',
		'footer_link_hover_font_color'                                => '#ffffff',
		'footer_link_hover_font_color_bind'                           => 'on',
		'gen_font_color'                                              => '#808080',
		'gen_line_height'                                             => '1.75',
		'gen_link_font_color'                                         => '#AEACBC',
		'gen_link_font_color_bind'                                    => 'on',
		'gen_link_hover_decoration'                                   => 'none',
		'gen_link_hover_font_color'                                   => '#ffffff',
		'gen_link_hover_font_color_bind'                              => 'on',
		'grid_img_rollover_text_gutter'                               => '25',
		'grid_img_rollover_text_text_link_font_family'                => 'Arial, Helvetica, sans-serif',
		'grid_img_rollover_text_text_link_font_size'                  => '12',
		'grid_img_rollover_text_title_link_font_color'                => '#808080',
		'grid_img_rollover_text_title_link_font_color_bind'           => 'on',
		'grid_img_rollover_text_title_link_font_family'               => 'LobsterTwoRegular, \"Lucida Grande\", \"Lucida Sans Unicode\", Tahoma, Verdana, sans-serif',
		'grid_img_rollover_text_title_link_font_size'                 => '15',
		'grid_img_rollover_text_title_link_hover_decoration'          => 'none',
		'grid_img_rollover_text_title_link_hover_font_color'          => '#808080',
		'grid_img_rollover_text_title_link_hover_font_color_bind'     => 'on',
		'grid_img_text_below_title_link_font_family'                  => 'DroidSansRegular, \"Lucida Grande\", \"Lucida Sans Unicode\", Tahoma, Verdana, sans-serif',
		'grid_img_text_below_title_link_font_size'                    => '13',
		'grid_img_text_below_title_link_font_style'                   => 'normal',
		'grid_img_text_below_title_link_font_weight'                  => '400',
		'grid_img_text_below_title_link_text_transform'               => 'uppercase',
		'header_bg_color'                                             => '#1e1e1e',
		'header_font_color'                                           => '#AEACBC',
		'header_font_family'                                          => 'LobsterTwoRegular, \"Lucida Grande\", \"Lucida Sans Unicode\", Tahoma, Verdana, sans-serif',
		'header_font_size'                                            => '28',
		'header_font_weight'                                          => '400',
		'header_letterspacing'                                        => 'normal',
		'headerlayout'                                                => 'logocenter_nav_masthead',
		'masthead_display'                                            => 'static',
		'masthead_slideshow_bg_color'                                 => '#fdfdfc',
		'masthead_slideshow_bg_color_bind'                            => '',
		'masthead_slideshow_loop_images'                              => '',
		'masthead_slideshow_transition_time'                          => '0.4',
		'mobile_button_bg_color'                                      => '#BDBBC6',
		'mobile_button_border_color'                                  => '#ffffff',
		'mobile_button_font_color'                                    => '#ffffff',
		'mobile_content_bg_color'                                     => '#ECEBEF',
		'mobile_content_bg_color_bind'                                => 'on',
		'mobile_content_bg_img_position'                              => 'top left',
		'mobile_content_bg_img_repeat'                                => 'repeat',
		'mobile_excerpt_list_border_color'                            => '#808080',
		'mobile_excerpt_list_border_width'                            => '0',
		'mobile_font_color'                                           => '#808080',
		'mobile_font_family'                                          => 'Arial, Helvetica, sans-serif',
		'mobile_footer_color_scheme'                                  => 'white',
		'mobile_headline_font_color'                                  => '#808080',
		'mobile_headline_font_family'                                 => 'Arial, Helvetica, sans-serif',
		'mobile_headline_font_weight'                                 => '400',
		'mobile_headline_text_transform'                              => 'uppercase',
		'mobile_link_font_color'                                      => '#BDBBC6',
		'mobile_logo_linkurl'                                         => '',
		'mobile_logo_use_desktop'                                     => 'false',
		'mobile_masthead_display'                                     => 'off',
		'mobile_masthead_use_desktop_settings'                        => 'false',
		'nav_below_link_font_family'                                  => 'DroidSansRegular, \"Lucida Grande\", \"Lucida Sans Unicode\", Tahoma, Verdana, sans-serif',
		'nav_below_link_font_size'                                    => '13',
		'nav_below_link_font_style'                                   => 'normal',
		'nav_below_link_font_weight'                                  => '400',
		'nav_below_link_text_transform'                               => 'uppercase',
		'nav_bg_img_position'                                         => 'top center',
		'nav_bg_img_repeat'                                           => 'no-repeat',
		'override_css'                                                => '/* do not delete, required for designs based on \"Late August\" starter-design */
#contact-form form.with-widget-content {margin-left:43%;}
#contact-form #widget-content {padding-left:7%;}
#contact-form textarea {width: 90%;}
/* end required CSS for \"Late August\" */
',
		'padding_below_post'                                          => '25',
		'page_bg_img_position'                                        => 'top center',
		'page_bg_img_repeat'                                          => 'no-repeat',
		'pagination_next_text'                                        => 'Next »',
		'pagination_prev_text'                                        => '« Prev',
		'portfoliotarget'                                             => '_blank',
		'post_bg_img_position'                                        => 'top center',
		'post_bg_img_repeat'                                          => 'no-repeat',
		'post_divider'                                                => 'image',
		'post_footer_meta_font_color'                                 => '#808080',
		'post_footer_meta_font_color_bind'                            => 'on',
		'post_footer_meta_link_font_color'                            => '#938fa3',
		'post_footer_meta_link_font_color_bind'                       => 'on',
		'post_footer_meta_link_font_family'                           => 'DroidSansRegular, \"Lucida Grande\", \"Lucida Sans Unicode\", Tahoma, Verdana, sans-serif',
		'post_footer_meta_link_font_size'                             => '12',
		'post_footer_meta_link_font_weight'                           => '400',
		'post_footer_meta_link_hover_decoration'                      => 'none',
		'post_footer_meta_link_hover_font_color'                      => '#ffffff',
		'post_footer_meta_link_hover_font_color_bind'                 => 'on',
		'post_footer_meta_link_text_transform'                        => 'lowercase',
		'post_header_align'                                           => 'center',
		'post_header_margin_above'                                    => '58',
		'post_header_margin_below'                                    => '10',
		'post_header_meta_font_color'                                 => '#808080',
		'post_header_meta_font_color_bind'                            => 'on',
		'post_header_meta_link_font_color'                            => '#808080',
		'post_header_meta_link_font_color_bind'                       => 'on',
		'post_header_meta_link_font_family'                           => 'DroidSansRegular, \"Lucida Grande\", \"Lucida Sans Unicode\", Tahoma, Verdana, sans-serif',
		'post_header_meta_link_font_size'                             => '12',
		'post_header_meta_link_font_weight'                           => '400',
		'post_header_meta_link_hover_decoration'                      => 'none',
		'post_header_meta_link_hover_font_color'                      => '#AEACBC',
		'post_header_meta_link_hover_font_color_bind'                 => 'on',
		'post_header_meta_link_text_transform'                        => 'uppercase',
		'post_header_postdate_font_color'                             => '#808080',
		'post_header_postdate_font_color_bind'                        => 'on',
		'post_header_postdate_font_family'                            => 'DroidSansRegular, \"Lucida Grande\", \"Lucida Sans Unicode\", Tahoma, Verdana, sans-serif',
		'post_header_postdate_font_size'                              => '12',
		'post_header_postdate_font_style'                             => 'normal',
		'post_header_postdate_font_weight'                            => '400',
		'post_header_postdate_letterspacing'                          => 'normal',
		'post_header_postdate_margin_bottom'                          => '15',
		'post_header_postdate_text_transform'                         => 'uppercase',
		'post_pic_border_color'                                       => '#ffffff',
		'post_title_link_font_size'                                   => '32',
		'post_title_link_font_style'                                  => 'italic',
		'post_title_link_font_weight'                                 => '400',
		'post_title_link_hover_decoration'                            => 'none',
		'post_title_link_margin_bottom'                               => '20',
		'post_title_link_text_transform'                              => 'none',
		'postdate_bg_color'                                           => '#a8ab9b',
		'postdate_bg_color_bind'                                      => 'on',
		'postdate_border_bottom'                                      => 'on',
		'postdate_border_color'                                       => '#ffffff',
		'postdate_border_style'                                       => 'double',
		'postdate_border_top'                                         => 'on',
		'postdate_border_width'                                       => '3',
		'postdate_lr_padding'                                         => '18',
		'postdate_tb_padding'                                         => '4',
		'primary_nav_menu_align'                                      => 'center',
		'primary_nav_menu_bg_color'                                   => '#88b2ab',
		'primary_nav_menu_bg_color_bind'                              => '',
		'primary_nav_menu_bg_img_position'                            => 'top center',
		'primary_nav_menu_dropdown_bg_color'                          => '#ffffff',
		'primary_nav_menu_dropdown_bg_color_bind'                     => 'on',
		'primary_nav_menu_dropdown_bg_hover_color'                    => '#ECEBEF',
		'primary_nav_menu_dropdown_bg_hover_color_bind'               => 'on',
		'primary_nav_menu_item_1'                                     => '{"type":"internal","internalType":"home","text":"Home"}',
		'primary_nav_menu_item_10'                                    => '{"type":"manual","text":"WordPress Blog","url":"http://wordpress.org/news/"}',
		'primary_nav_menu_item_11'                                    => '{"type":"manual","text":"WordPress Planet","url":"http://planet.wordpress.org/"}',
		'primary_nav_menu_item_12'                                    => '{"type":"internal","internalType":"categories","text":"Categories"}',
		'primary_nav_menu_item_13'                                    => '{"type":"internal","internalType":"rss","text":"Subscribe","anchor":"text"}',
		'primary_nav_menu_item_14'                                    => '{"type":"special","searchBtnText":"search","text":"Search","specialType":"dropdown_search"}',
		'primary_nav_menu_item_15'                                    => '{"type":"special","specialType":"show_contact_form","text":"Contact"}',
		'primary_nav_menu_item_2'                                     => '{"type":"manual","url":"","text":"Portfolio","target":""}',
		'primary_nav_menu_item_3'                                     => '{"type":"internal","internalType":"featured_slideshows","text":"Galleries"}',
		'primary_nav_menu_item_4'                                     => '{"type":"container","text":"Links"}',
		'primary_nav_menu_item_5'                                     => '{"type":"manual","text":"Documentation","url":"http://codex.wordpress.org/"}',
		'primary_nav_menu_item_6'                                     => '{"type":"manual","text":"Plugins","url":"http://wordpress.org/extend/plugins/"}',
		'primary_nav_menu_item_7'                                     => '{"type":"manual","text":"Suggest Ideas","url":"http://wordpress.org/extend/ideas/"}',
		'primary_nav_menu_item_8'                                     => '{"type":"manual","text":"Support Forum","url":"http://wordpress.org/support/"}',
		'primary_nav_menu_item_9'                                     => '{"type":"manual","text":"Themes","url":"http://wordpress.org/extend/themes/"}',
		'primary_nav_menu_link_font_color'                            => '#808080',
		'primary_nav_menu_link_font_family'                           => 'DroidSansRegular, \"Lucida Grande\", \"Lucida Sans Unicode\", Tahoma, Verdana, sans-serif',
		'primary_nav_menu_link_font_weight'                           => '400',
		'primary_nav_menu_link_hover_decoration'                      => 'none',
		'primary_nav_menu_link_letterspacing'                         => '1px',
		'primary_nav_menu_link_spacing_between'                       => '40',
		'primary_nav_menu_link_text_transform'                        => 'uppercase',
		'primary_nav_menu_structure'                                  => '{"primary_nav_menu_item_1":"primary_nav_menu_item_1","primary_nav_menu_item_2":"primary_nav_menu_item_2","primary_nav_menu_item_4":{"primary_nav_menu_item_5":"primary_nav_menu_item_5","primary_nav_menu_item_6":"primary_nav_menu_item_6","primary_nav_menu_item_7":"primary_nav_menu_item_7","primary_nav_menu_item_8":"primary_nav_menu_item_8","primary_nav_menu_item_9":"primary_nav_menu_item_9","primary_nav_menu_item_10":"primary_nav_menu_item_10","primary_nav_menu_item_11":"primary_nav_menu_item_11"},"primary_nav_menu_item_12":"primary_nav_menu_item_12","primary_nav_menu_item_13":"primary_nav_menu_item_13","primary_nav_menu_item_14":"primary_nav_menu_item_14","primary_nav_menu_item_15":"primary_nav_menu_item_15"}',
		'sidebar_border_switch'                                       => 'off',
		'sidebar_on_archive'                                          => '',
		'sidebar_on_home'                                             => '',
		'sidebar_on_page'                                             => '',
		'sidebar_on_single'                                           => '',
		'slideshow_bg_color'                                          => '#ECEBEF',
		'slideshow_btns_color'                                        => '#808080',
		'slideshow_subtitle_font_color'                               => '#808080',
		'slideshow_subtitle_font_color_bind'                          => 'on',
		'slideshow_subtitle_font_family'                              => 'Arial, Helvetica, sans-serif',
		'slideshow_thumb_border_color'                                => '#ffffff',
		'slideshow_title_font_color'                                  => '#808080',
		'slideshow_title_font_family'                                 => 'Arial, Helvetica, sans-serif',
		'tags_in_post_footer'                                         => 'yes',
		'tags_in_post_header'                                         => '',
		'widget_menu_1_item_1'                                        => '{"text":"Let\'s Be Facebook Friends","type":"manual","iconNotConstrained":true,"internalType":"page","pageID":"","categoryName":"","archivesNestThreshold":"","numRecentPosts":"","galleryID":"","galleryDisplay":"","specialType":"email","email":"","twitterID":"","numTweets":"8","searchBtnText":"Search","subscribeByEmailPrefill":"Enter email","subscribeByEmailBtnText":"Subscribe by email","customHTML":"","url":"","target":"_blank","anchor":"img","iconAlign":"left","titleAttr":"","customClasses":"","menu_item_id":"widget_menu_1_item_1","excludedPageIDs":""}',
		'widget_menu_1_item_2'                                        => '{"text":"Follow Late August Tweets","type":"manual","iconNotConstrained":true,"internalType":"page","pageID":"","categoryName":"","archivesNestThreshold":"","numRecentPosts":"","galleryID":"","galleryDisplay":"","specialType":"email","email":"","twitterID":"","numTweets":"8","searchBtnText":"Search","subscribeByEmailPrefill":"Enter email","subscribeByEmailBtnText":"Subscribe by email","customHTML":"","url":"","target":"_blank","anchor":"img","iconAlign":"left","titleAttr":"","customClasses":"","menu_item_id":"widget_menu_1_item_2","excludedPageIDs":""}',
		'widget_menu_1_item_3'                                        => '{"text":"Subscribe","type":"manual","iconNotConstrained":true,"internalType":"page","pageID":"","categoryName":"","archivesNestThreshold":"","numRecentPosts":"","galleryID":"","galleryDisplay":"","specialType":"email","email":"","twitterID":"","numTweets":"8","searchBtnText":"Search","subscribeByEmailPrefill":"Enter email","subscribeByEmailBtnText":"Subscribe by email","customHTML":"","url":"http:\/\/#","target":"_blank","anchor":"img","iconAlign":"left","titleAttr":"","customClasses":"","menu_item_id":"widget_menu_1_item_3","excludedPageIDs":""}',
		'widget_menu_1_item_4'                                        => '{"text":"About the Photographer","type":"manual","iconNotConstrained":true,"internalType":"page","pageID":"","categoryName":"","archivesNestThreshold":"","numRecentPosts":"","galleryID":"","galleryDisplay":"","specialType":"email","email":"","twitterID":"","numTweets":"8","searchBtnText":"Search","subscribeByEmailPrefill":"Enter email","subscribeByEmailBtnText":"Subscribe by email","customHTML":"","url":"http:\/\/#","target":"","anchor":"img","iconAlign":"left","titleAttr":"","customClasses":"","menu_item_id":"widget_menu_1_item_4","excludedPageIDs":""}',
		'widget_menu_1_li_list_style'                                 => 'none',
		'widget_menu_1_li_margin_btm'                                 => '2',
		'widget_menu_1_structure'                                     => '{"widget_menu_1_item_1":"widget_menu_1_item_1", "widget_menu_1_item_2":"widget_menu_1_item_2", "widget_menu_1_item_3":"widget_menu_1_item_3", "widget_menu_1_item_4":"widget_menu_1_item_4"}',
		'widget_menu_1_sub_li_list_style'                             => 'none',
		'widget_menu_1_sub_li_margin_btm'                             => '3',
		'widget_menu_1_sub_sub_li_list_style'                         => 'none',
		'widget_menu_1_sub_sub_li_margin_btm'                         => '3',
		'widget_menu_2_item_1'                                        => '{"text":"What to Expect","type":"manual","iconNotConstrained":true,"internalType":"page","pageID":"","categoryName":"","archivesNestThreshold":"","numRecentPosts":"","galleryID":"","galleryDisplay":"","specialType":"email","email":"","twitterID":"","numTweets":"8","searchBtnText":"Search","subscribeByEmailPrefill":"Enter email","subscribeByEmailBtnText":"Subscribe by email","customHTML":"","url":"http:\/\/#","target":"","anchor":"img","iconAlign":"left","titleAttr":"","customClasses":"","menu_item_id":"widget_menu_2_item_1","excludedPageIDs":""}',
		'widget_menu_2_li_list_style'                                 => 'none',
		'widget_menu_2_li_margin_btm'                                 => '3',
		'widget_menu_2_structure'                                     => '{"widget_menu_2_item_1":"widget_menu_2_item_1"}',
		'widget_menu_2_sub_li_list_style'                             => 'none',
		'widget_menu_2_sub_li_margin_btm'                             => '3',
		'widget_menu_2_sub_sub_li_list_style'                         => 'none',
		'widget_menu_2_sub_sub_li_margin_btm'                         => '3',
		'widget_menu_3_item_1'                                        => '{"text":"Rates & Packages","type":"manual","iconNotConstrained":true,"internalType":"page","pageID":"","categoryName":"","archivesNestThreshold":"","numRecentPosts":"","galleryID":"","galleryDisplay":"","specialType":"email","email":"","twitterID":"","numTweets":"8","searchBtnText":"Search","subscribeByEmailPrefill":"Enter email","subscribeByEmailBtnText":"Subscribe by email","customHTML":"","url":"http:\/\/#","target":"","anchor":"img","iconAlign":"left","titleAttr":"","customClasses":"","menu_item_id":"widget_menu_3_item_1","excludedPageIDs":""}',
		'widget_menu_3_li_list_style'                                 => 'none',
		'widget_menu_3_li_margin_btm'                                 => '3',
		'widget_menu_3_structure'                                     => '{"widget_menu_3_item_1":"widget_menu_3_item_1"}',
		'widget_menu_3_sub_li_list_style'                             => 'none',
		'widget_menu_3_sub_li_margin_btm'                             => '3',
		'widget_menu_3_sub_sub_li_list_style'                         => 'none',
		'widget_menu_3_sub_sub_li_margin_btm'                         => '3',
	),

	'activation_widgets' => array(

		'bio-spanning-col' => 'empty',

		'bio-col-1' => array(
			'1' => array(
				'pp-vertical-nav-menu' => array(
					'title' => '',
					'widget_menu_num' => '3',
				),

			),

		),

		'bio-col-2' => array(
			'1' => array(
				'pp-vertical-nav-menu' => array(
					'title' => '',
					'widget_menu_num' => '2',
				),

			),

		),

		'bio-col-3' => array(
			'1' => array(
				'pp-vertical-nav-menu' => array(
					'title' => '',
					'widget_menu_num' => '1',
				),

			),

		),

		'bio-col-4' => 'empty',

	),

	'imgs' => array(
		'bio_inner_bg'                 => 'late_august_all_inner_content_bg.png',
		'bio_separator'                => 'late_august_bio_separator.png',
		'blog_bg'                      => 'late_august_blog_bg.jpg',
		'blog_bg_inner'                => 'late_august_blog_bg_inner.png',
		'body_bg'                      => 'late_august_all_inner_content_bg.png',
		'call_to_action_separator_img' => 'late_august_call_to_action_separator_img.png',
		'contact_bg'                   => 'late_august_all_inner_content_bg.png',
		'footer_bg'                    => 'late_august_all_inner_content_bg.png',
		'footer_btm_cap'               => 'late_august_footer_btm_cap.png',
		'logo'                         => 'late_august_logo.png',
		'masthead_image1'              => 'late_august_masthead_image1.png',
		'mobile_logo'                  => 'late_august_mobile_logo.png',
		'page_bg'                      => 'late_august_page_and_post_bg.png',
		'post_bg'                      => 'late_august_page_and_post_bg.png',
		'primary_nav_menu_bg'          => 'late_august_primary_nav_menu_bg.png',
		'widget_menu_1_item_1'         => 'late_august_widget_menu_1_item_1.jpg',
		'widget_menu_1_item_2'         => 'late_august_widget_menu_1_item_2.jpg',
		'widget_menu_1_item_3'         => 'late_august_widget_menu_1_item_3.jpg',
		'widget_menu_1_item_4'         => 'late_august_widget_menu_1_item_4.jpg',
		'widget_menu_2_item_1'         => 'late_august_widget_menu_2_item_1.jpg',
		'widget_menu_3_item_1'         => 'late_august_widget_menu_3_item_1.jpg',
	),

	'remote_files' => array(

		'DroidSans-webfont.eot' => array(
			'hash' => '4a27a9e482782774f51ea32d97922389',
		),

		'DroidSans-webfont.svg' => array(
			'hash' => 'cc8179649c06e8ce0afe83238c7095dc',
		),

		'DroidSans-webfont.ttf' => array(
			'hash' => '5abaf7b5fa05765a3d62fc84065d7036',
		),

		'DroidSans-webfont.woff' => array(
			'hash' => '5d747c4b2157cc42a6c8ee77eb092bd8',
		),

		'LobsterTwo-Regular-webfont.eot' => array(
			'hash' => '3ced1ba6fd9c387a402474fe7ea55460',
		),

		'LobsterTwo-Regular-webfont.svg' => array(
			'hash' => '6384f86b64097fc1f5a85dd476eb7248',
		),

		'LobsterTwo-Regular-webfont.ttf' => array(
			'hash' => 'a5cd12200140415a0f5101628e7b43ab',
		),

		'LobsterTwo-Regular-webfont.woff' => array(
			'hash' => '8ac4b969096e50b5d56a32a21b2f20ee',
		),

		'late_august_all_inner_content_bg.png' => array(
			'hash'   => '762ca954ddbf281e6035436a6601abfd',
			'width'  => '980',
			'height' => '40',
			'size'   => '1',
		),

		'late_august_bio_separator.png' => array(
			'hash'   => '28a056ad7bac18d01816b2566ac86081',
			'width'  => '980',
			'height' => '130',
			'size'   => '9',
		),

		'late_august_blog_bg.jpg' => array(
			'hash'   => 'dd7332010b77d1f31f41e47ab892973f',
			'width'  => '221',
			'height' => '221',
			'size'   => '7',
		),

		'late_august_blog_bg_inner.png' => array(
			'hash'   => 'c304931b8fc582dc63880fec18e4a00d',
			'width'  => '90',
			'height' => '171',
			'size'   => '1',
		),

		'late_august_call_to_action_separator_img.png' => array(
			'hash'   => '1e2006273e8164ff7e903fa0144022d7',
			'width'  => '22',
			'height' => '18',
			'size'   => '1',
		),

		'late_august_footer_btm_cap.png' => array(
			'hash'   => 'db85b462ff0289511a6deca4f421db3f',
			'width'  => '980',
			'height' => '75',
			'size'   => '6',
		),

		'late_august_logo.png' => array(
			'hash'   => 'e13ba4aa4f95319e3590ced5c5a66e04',
			'width'  => '980',
			'height' => '265',
			'size'   => '32',
		),

		'late_august_masthead_image1.png' => array(
			'hash'   => 'ac131839ea0677ef503f39b7428ce92e',
			'width'  => '980',
			'height' => '400',
			'size'   => '662',
		),

		'late_august_mobile_logo.png' => array(
			'hash'   => '2aca9ba6f27bf13a20551448be8ed469',
			'width'  => '980',
			'height' => '459',
			'size'   => '41',
		),

		'late_august_page_and_post_bg.png' => array(
			'hash'   => 'a351a59ba0db7a9ec85c4f63cabf9c36',
			'width'  => '935',
			'height' => '100',
			'size'   => '1',
		),

		'late_august_primary_nav_menu_bg.png' => array(
			'hash'   => '457b31b48c74c01093fb5a2dfc174b64',
			'width'  => '980',
			'height' => '40',
			'size'   => '1',
		),

		'late_august_widget_menu_1_item_1.jpg' => array(
			'hash'   => 'a71a152ee9d891620be7a9458881e236',
			'width'  => '280',
			'height' => '41',
			'size'   => '2',
		),

		'late_august_widget_menu_1_item_2.jpg' => array(
			'hash'   => '233489e2178642a4c91b1eb06dcdae0b',
			'width'  => '280',
			'height' => '41',
			'size'   => '2',
		),

		'late_august_widget_menu_1_item_3.jpg' => array(
			'hash'   => 'e139489212c51f56804ac59974c42c9f',
			'width'  => '280',
			'height' => '41',
			'size'   => '3',
		),

		'late_august_widget_menu_1_item_4.jpg' => array(
			'hash'   => 'a14dab552ebf02c5c74c9bef03274662',
			'width'  => '280',
			'height' => '41',
			'size'   => '2',
		),

		'late_august_widget_menu_2_item_1.jpg' => array(
			'hash'   => 'b959942b5ea75f9a73c9950c71bc9ceb',
			'width'  => '280',
			'height' => '216',
			'size'   => '17',
		),

		'late_august_widget_menu_3_item_1.jpg' => array(
			'hash'   => '7153a2f3d47ee1bdbae8219077a88b2b',
			'width'  => '280',
			'height' => '216',
			'size'   => '14',
		),
	),

);


