<?php

$configArray = array(

	'meta' => array(
		'name' => 'Brown',
		'desc' => 'Reminiscent of hand drawn fabric, the Brown template has a unique header design.  The repeating warm floral theme carries through to individual post headers and footers.  There is an offset label area to fully showcase your logo.  Chocolate and caramel coloring create a warm atmosphere for your work to shine.',
	),

	'options' => array(
		'boxy_date_bg_color_bind'                                       => 'on',
		'comment_header_border_bottom'                                  => '',
		'bg_color'                                                      => '#341d12',
		'body_bg_color'                                                 => '#cac5b1',
		'blog_top_margin'                                               => '74',
		'menu_top_splitter'                                             => '51',
		'menu_btm_splitter'                                             => '55',
		'post_splitter'                                                 => '40',
		'archive_post_splitter'                                         => '30',
		'bgimg_repeat'                                                  => 'repeat-x',
		'bgimg_attachment'                                              => 'scroll',
		'bgimg_position'                                                => 'top left',
		'headerlayout'                                                  => 'logocenter_masthead_nav',
		'masthead_top_border_color'                                     => '#000000',
		'masthead_top_border_style'                                     => 'solid',
		'masthead_btm_border_color'                                     => '#000000',
		'masthead_btm_border_style'                                     => 'solid',
		'masthead_display'                                              => 'off',
		'primary_nav_menu_link_font_family'                             => 'Helvetica, Arial, sans-serif',
		'primary_nav_menu_link_font_weight'                             => '400',
		'primary_nav_menu_link_text_transform'                          => 'uppercase',
		'primary_nav_menu_link_font_color'                              => '#ffffff',
		'primary_nav_menu_link_hover_decoration'                        => 'none',
		'primary_nav_menu_link_hover_font_color_bind'                   => 'on',
		'primary_nav_menu_link_visited_font_color_bind'                 => 'on',
		'primary_nav_menu_link_font_size'                               => '15',
		'primary_nav_menu_bg_color_bind'                                => '',
		'primary_nav_menu_dropdown_bg_color_bind'                       => 'on',
		'primary_nav_menu_dropdown_bg_color'                            => '#533324',
		'primary_nav_menu_align'                                        => 'center',
		'primary_nav_menu_link_spacing_between'                         => '40',
		'primary_nav_menu_top_border_color'                             => '#000000',
		'primary_nav_menu_top_border_style'                             => 'solid',
		'primary_nav_menu_btm_border_color'                             => '#000000',
		'primary_nav_menu_btm_border_style'                             => 'solid',
		'primary_nav_menu_link_hover_font_color'                        => '#36e4da',
		'primary_nav_menu_link_visited_font_color'                      => '#ffffff',
		'bio_include'                                                   => 'no',
		'bio_bg_color'                                                  => '#cac5b1',
		'gen_font_size'                                                 => '14',
		'gen_font_weight'                                               => '400',
		'gen_font_style'                                                => 'normal',
		'gen_text_transform'                                            => 'none',
		'gen_font_color'                                                => '#333333',
		'gen_margin_bottom'                                             => '18',
		'gen_link_font_weight'                                          => '400',
		'gen_link_text_transform'                                       => 'none',
		'gen_link_font_color_bind'                                      => 'on',
		'gen_link_font_color'                                           => '#371f14',
		'header_font_size'                                              => '35',
		'header_font_family'                                            => 'Garamond, Palatino, Georgia, serif',
		'header_font_weight'                                            => '400',
		'header_font_style'                                             => 'normal',
		'header_text_transform'                                         => 'uppercase',
		'header_font_color'                                             => '#371f14',
		'post_header_margin_above'                                      => '21',
		'post_header_margin_below'                                      => '50',
		'postdate_display'                                              => 'boxy',
		'boxy_date_font_size'                                           => '15',
		'boxy_date_bg_color'                                            => '#CAC5B1',
		'boxy_date_month_color'                                         => '#371f14',
		'boxy_date_day_color'                                           => '#371f14',
		'boxy_date_year_color'                                          => '#371f14',
		'tags_in_post_header'                                           => 'yes',
		'comment_count_in_post_header'                                  => 'yes',
		'post_title_link_font_size'                                     => '37',
		'post_title_link_text_transform'                                => 'uppercase',
		'post_header_meta_link_decoration'                              => 'underline',
		'post_header_meta_link_hover_decoration'                        => 'none',
		'postdate_border_top'                                           => 'on',
		'postdate_border_bottom'                                        => 'on',
		'postdate_border_left'                                          => 'on',
		'postdate_border_right'                                         => 'on',
		'postdate_border_color'                                         => '#371f14',
		'postdate_border_width'                                         => '1',
		'postdate_border_style'                                         => 'solid',
		'post_pic_border_color'                                         => '#000000',
		'excerpt_image_position'                                        => 'after_text',
		'comments_layout'                                               => 'minima',
		'comments_on_home_start_hidden'                                 => 'open',
		'comments_area_bg_color_bind'                                   => 'on',
		'comments_area_bg_color'                                        => '#EBE8D7',
		'comment_bg_color_bind'                                         => 'on',
		'comment_bg_color'                                              => '#fefefd',
		'comments_header_bg_color'                                      => '#ffffff',
		'comments_area_border_color'                                    => '#F6F5E8',
		'comments_area_border_width'                                    => '2',
		'comments_area_border_style'                                    => 'solid',
		'comments_header_show_article_author'                           => 'false',
		'comments_header_lr_padding'                                    => '58',
		'comments_header_link_font_size'                                => '16',
		'comments_header_link_font_family'                              => '\"Century Gothic\", Helvetica, Arial, sans-serif',
		'comments_header_link_text_transform'                           => 'uppercase',
		'comments_header_font_color_bind'                               => 'on',
		'comments_header_link_font_color_bind'                          => 'on',
		'comments_header_link_hover_decoration'                         => 'none',
		'comments_header_link_hover_font_color_bind'                    => 'on',
		'comments_header_post_interaction_link_font_size'               => '15',
		'comments_header_post_interaction_link_font_weight'             => '400',
		'comments_header_post_interaction_link_font_style'              => 'normal',
		'comments_header_post_interaction_link_text_transform'          => 'uppercase',
		'comments_header_post_interaction_link_decoration'              => 'none',
		'comments_header_post_interaction_link_font_color_bind'         => 'on',
		'comments_header_post_interaction_link_hover_decoration'        => 'none',
		'comments_header_post_interaction_link_hover_font_color_bind'   => 'on',
		'comments_header_post_interaction_link_visited_font_color_bind' => 'on',
		'comments_header_post_interact_link_spacing'                    => '20',
		'comments_header_emailafriend_link_include'                     => 'no',
		'comments_header_emailafriend_link_subject'                     => pp::site()->name,
		'comment_author_link_font_weight'                               => '700',
		'comment_author_link_text_transform'                            => 'uppercase',
		'comment_author_link_font_color_bind'                           => 'on',
		'comment_meta_margin_bottom'                                    => '10',
		'comment_timestamp_display'                                     => 'left',
		'comment_timestamp_font_color'                                  => '#4D3C2F',
		'comment_text_and_link_font_size'                               => '12',
		'comment_tb_padding'                                            => '14',
		'comment_lr_padding'                                            => '14',
		'comments_body_area_lr_margin'                                  => '19',
		'comments_body_area_tb_margin'                                  => '14',
		'comment_tb_margin'                                             => '14',
		'comment_alt_bg_color_bind'                                     => '',
		'comments_header_font_color'                                    => '#371f14',
		'comments_header_post_interaction_link_font_color'              => '#371f14',
		'comments_header_link_font_color'                               => '#371f14',
		'comments_header_link_hover_font_color'                         => '#36e4da',
		'comments_header_post_interaction_link_hover_font_color'        => '#36e4da',
		'comments_header_post_interaction_link_visited_font_color'      => '#371f14',
		'postdate_bg_color'                                             => '#000000',
		'blog_bg_img_repeat'                                            => 'repeat-x',
		'blog_bg_color'                                                 => '#331D10',
		'post_header_meta_font_color'                                   => '#4c2d20',
		'post_bg_img_repeat'                                            => 'no-repeat',
		'post_bg_img_position'                                          => 'top center',
		'post_bg_img_attachment'                                        => 'scroll',
		'comments_scrollbox_height'                                     => '360',
		'comment_author_link_font_color'                                => '#539491',
		'comments_header_tb_padding'                                    => '28',
		'comments_header_bg_img_repeat'                                 => 'no-repeat',
		'comments_header_bg_img_position'                               => 'top left',
		'comments_header_bg_img_attachment'                             => 'scroll',
		'footer_bg_color'                                               => '#543324',
		'footer_link_font_color_bind'                                   => 'on',
		'footer_link_font_color'                                        => '#cac5b1',
		'slideshow_bg_color'                                            => '#543324',
		'bio_bg'                                                        => 'color',
		'bio_border'                                                    => 'noborder',
		'archive_h2_font_size'                                          => '32',
		'archive_h2_text_transform'                                     => 'none',
		'archive_h2_font_color'                                         => '#543324',
		'blog_border'                                                   => 'none',
		'contact_btm_border_width'                                      => '0',
	),


	'activation_widgets' => array(
		'fixed-sidebar' => 'empty',
	),


	'imgs' => array(
		'blog_bg'            => 'brown_blog_bg.jpg',
		'comments_header_bg' => 'brown_comments_header_bg.jpg',
		'logo'               => 'brown_logo.png',
		'post_bg'            => 'brown_post_bg.gif',
	),


	'remote_files' => array(

		'brown_blog_bg.jpg' => array(
			'hash'   => 'a0a3eb9a327deafde95f2397cad2926b',
			'width'  => '376',
			'height' => '1304',
			'size'   => '37',
		),

		'brown_comments_header_bg.jpg' => array(
			'hash'   => 'b88b0a1dcb79459b136770693e331708',
			'width'  => '898',
			'height' => '80',
			'size'   => '5',
		),

		'brown_logo.png' => array(
			'hash'   => '3e1a55405ea2b08205ddaa77fb39b407',
			'width'  => '401',
			'height' => '214',
			'size'   => '20',
		),

		'brown_post_bg.gif' => array(
			'hash'   => 'b2394fdfe7ba1039d613378628b544d9',
			'width'  => '960',
			'height' => '105',
			'size'   => '3',
		),
	),

);

